### ISSUE TITLE
Single post - Odd vertical spacing between a section title and its first element

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#10]
_Page: https://w3c-dev.studio24.dev/posts/post.html_

In the "Related to this post" right menu, I noticed that the vertical spacing between the title of the section and the first element (e.g. between "Tags" and "Tag 1"), is smaller than the vertical spacing between 2 section elements (e.g. between "Tag 1" and "Tag 2"). Which looks a bit odd.

![Screenshot from 2021-07-16 19-28-11](https://user-images.githubusercontent.com/2012282/125986352-efe2c81a-6aea-479c-b35e-4e3652d96e0a.png)

I believe that it woudl render nicer if the vertical spacing between the section title and its first element was at least as wide as the spacing between 2 section element.

**Comment by IanAxton** [comment]
Agree. 
We need to increase the spacing.

**Comment by NicolaSaunders** [comment]
I have pushed a change today which resolves the spacing
