### ISSUE TITLE
"Browse archives" years are sorted incorrectly (should be most recent first)

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#101]
**Describe the issue**

In the "Browse archives" filter the options should be sorted with the most recent year first as shown in the [design system's "Search and filtering options for the hero" code example](https://design-system.w3.org/templates/listings.html#search-and-filtering-options-for-the-hero).

**URL**

https://www-staging.w3.org/news/
https://www-staging.w3.org/blog/
https://www-staging.w3.org/press-releases/

cc: @lcarcone

**Comment by jean-gui** [comment]
Fixed.
