### ISSUE TITLE
HTML page title shows "&amp;"

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#103]
**Describe the issue**

The HTML page title shows "`&amp;`" as it is double encoded.

```html
<title>Network &amp;amp; Communication - W3C</title>
```

Note that the page title for this ecosystem is correctly set in the CMS to `Network & Communications`.

**To reproduce**
See: https://www-staging.w3.org/ecosystems/network-communications/

**Comment by jean-gui** [comment]
Fixed.
