### ISSUE TITLE
Add more translations available in CMS

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#107]
Currently, the following translations are available in CMS:
Chinese, Japanese, French, Brazilian Portuguese, German, Hungarian, Spanish, Arabic

Press Releases list translations for the following extra languages, could they be added:
Russian, Italian, Swedish, Korean, Greek, Bulgarian, Czech, Danish, Estonian, Finnish, Gael, Lithuanian, Latvian, Maltese

(see https://www.w3.org/Press/Releases-2012.html 'W3C Launches Work to Simplify Creation of Content in World's Languages' for a specific example).

**Comment by jean-gui** [comment]
Added
