### ISSUE TITLE
glitch in nav menus when going back/forward in Chrome

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#109]
When I browse around [the www-staging site](https://www-staging.w3.org/) in Chrome on OS X, if I use the back/forward buttons in the browser the navigation menu gets a mysterious glitch, where the first menu item has a chevron the the others do not.

![Screen Shot 2022-01-28 at 3 52 55 PM](https://user-images.githubusercontent.com/7144396/151636949-e0183f31-6918-46f5-865f-861dbfd08f50.png)

It doesn't happen all of the time, but seems to happen about 80% of the time, and a colleague confirmed that the same thing happens on his system when he uses Chrome. I have never seen this happen in Firefox, and it doesn't seem to be an issue in MS Edge version 97.

On [the w3c-dev.studio24.dev site](https://w3c-dev.studio24.dev/) the same thing happens when I go back/forward in my browser history, but there the first two menus have chevrons instead of only the first one.

![Screen Shot 2022-01-28 at 3 53 37 PM](https://user-images.githubusercontent.com/7144396/151637087-2863ffd1-0c7d-435a-abc2-0aab56f992dc.png)

This happens no matter how I go back/forward: I usually do so using gestures on my trackpad but the same thing happens if I use the back/forward buttons or keyboard commands to go back/forward.

**Comment by gosko** [comment]
Oh, I just got it to happen in MS Edge as well, but only the About menu was missing its chevron, and it seems to happen much less often in Edge: maybe 5% of the time instead of 80-90%. What a strange bug!

**Comment by maries24** [comment]
Thanks @gosko I could reproduce that by simple browsing as well (without going back and forth). I suspect an issue of the navigation script sometimes firing too early. I'm adding this to the Beta release board.

**Comment by vivienlacourba** [comment]
Fixed see https://github.com/w3c/w3c-website/issues/129#issuecomment-1053582185
