### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-website#11]
Here are a few comments regarding avatars on https://w3c-dev.studio24.dev/posts/post.html but apply to other pages as well.

1. The small version (24x24, 1.5rem) as used for example in the "My Account link" seems very small. Could this be a little bigger? 32x32, 2rem seems to make the image a bit more readable while still small enough.
 2. The current CSS seems to rely on provided avatars to use a portrait ratio. We expect to provide square pictures in the very near future. Does the current CSS also works with square ones?
 3.  The markup (and style, for example no blue circle around the "no avatar" picture) is different when there is or there isn't an avatar for the user, thus making implementation more difficult as we'll need two different templates. Would it be possible to use the same markup? I think this would mostly require changing https://w3c-dev.studio24.dev/posts/dist/assets/svg/avatar.svg to have the same shape as other pictures (square)

**Comment by vivienlacourba** [comment]
> The small version (24x24, 1.5rem) as used for example in the "My Account link" seems very small. Could this be a little bigger? 32x32, 2rem seems to make the image a bit more readable while still small enough.

Similarly for authors on the [Single blog post page](https://w3c-dev.studio24.dev/posts/post.html).

**Comment by NicolaSaunders** [comment]
Responding to point 2, Yes the current CSS will also work with square avatars.

**Comment by NicolaSaunders** [comment]
Responding to point 3, we need to use a conditional statement in the template to check for the presence of an avatar photo to choose whether or not to display the avatar or the no-avatar fallback image. This same conditional can specify the appropriate markup to use in each case.

**Comment by jean-gui** [comment]
For point 3, yes, we can use two different markups but it seems sub-optimal to have two different pieces of code to achieve the same result. Anyway, it's not a big issue and it can probably be addressed (or not) later.

**Comment by vivienlacourba** [comment]
Hi @NicolaSaunders,

> Responding to point 3, we need to use a conditional statement in the template to check for the presence of an avatar photo to choose whether or not to display the avatar or the no-avatar fallback image. This same conditional can specify the appropriate markup to use in each case.

Please take into account that some of the W3C website pages will end up be created manually, based on what is described in the design system, so if people have to use quite different markups to handle slight differences (e.g. loading a real user avatar or a placeholder image) it woudl be more work for them and also quite error prone and I guess it woudl make the design system more complex than it needs to be.

**Current templates difference for avatar pictures: user profile picture vs default avatar:**

```html
<div class="avatar avatar--med">
  <img alt="" src="https://www.w3.org/2006/05/u/1682ihk1hqqo-sm.jpg" loading="lazy">
</div>
```
```html
<img src="dist/assets/svg/avatar.svg" alt="" aria-hidden="true" width="50" height="50">
```
Could this second block be something like (and have avatar.svg use the same square aspect ratio as other profile pictures):
```html
<div class="avatar avatar--med">
  <img alt="" src="dist/assets/svg/avatar.svg" aria-hidden="true">
</div>
```

**Comment by IanAxton** [comment]
Regarding size: Yes let's increase the size to 2rem. We should do the same for the Author.

**Comment by NicolaSaunders** [comment]
@vivienlacourba you make a very good point about the reusability and maintainability of the code.

I have pushed some updates today. As well as increasing the size of the avatar, I have also changed the SVG to be square so that the same HTML can be used both for the placeholder and for actual photos of people.
