### ISSUE TITLE
Typo in CSS for checkbox/radio item

### ISSUE THREAD

**Issue by NicolaSaunders** [w3c/w3c-website#110]
In `30-base/_forms.scss` there is the following style:

```
[dir="rtl"] {

	.checkbox-item label::after {

		auto: rem(6);
		right: rem(6);

	}

}
```

`auto: rem(6);` needs to be amended to `left: auto;`

**Comment by maries24** [comment]
This will potentially affect all apps using forms and is a quick fix so I'll this to the Beta backlog.
