### ISSUE TITLE
Press release template

### ISSUE THREAD

**Issue by simonrjones** [w3c/w3c-website#116]
**Describe the issue**
Press releases post page appear to be missing:
* Published date
* Primary navigation

**To reproduce**
See https://www-staging.w3.org/press-releases/2021/webauthn-mooc/
Or https://www-staging.w3.org/press-releases/2021/snakenation/

**Expected behavior**
Published date to appear beneath H1, see post template https://design-system.w3.org/templates/post.html

Primary navigation to appear as per any other page, e.g. https://www-staging.w3.org/press-releases/

**Additional context**
Non-English/Chinese/Japanese press release pages are not expected to have primary navigation since we do not have translated versions of these.

**Comment by simonrjones** [comment]
Discussed with @koalie and @vivienlacourba, it looks like the published date is intentionally included in the main body of text due to how W3C want press release content formatted.

It does make sense to bring back:
- Breadcrumb
- Primary navigation

Is it possible for @jean-gui to work on adding this back to this page?

**Comment by JuliaSang** [comment]
To clarify, [we specified](https://docs.google.com/document/d/1NRXvIO4kDs2leAFVF-zqJxNKGMbrRDL3MaQDOjp4WHI/edit#bookmark=id.9uni5lpltcm) that this page should follow the post page layout which as well as the main navigation, would also involve having the styles header area and as shown at https://w3c-dev.studio24.dev/posts/post.html and includes a set of the following data):

Publication date (although this can be removed if not required)

**Taxonomies to display if used:** 

These terms link to a listing of content related to taxonomy term:

- Tags
- Categories

These taxonomy terms are displayed (not linked):

- Working groups
- Business ecosystem
- Specification

**Comment by vivienlacourba** [comment]
> To clarify, we specified that this page should follow the post page layout which as well as the main navigation (...)

I don't recall exactly why we went for the basic template here, and upon further thoughts and discussion with @jean-gui I see more pros than cons in using the "post" template here.

I'm assigning it to @jean-gui and @koalie to address this.

**Comment by jean-gui** [comment]
Press releases now use the post template.
