### ISSUE TITLE
Deploy staging site to beta

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#119]
@AlanJIsaacson @jean-gui 

On the w/c 7 March DAC and Zoonou will be testing the website. They will be exploring pages which are populated by both the CMS and via Symfony. Currently, CMS pages are displaying on the [staging site](https://www-staging.w3.org/), Symfony pages are displaying on the [beta site](https://beta.w3.org/). 

Before the 7 March, please can you copy the content from staging to beta so that all the testing can happen on beta. 

We suggest the following order of events, but if there is a better way let us know

1. Test and document the process
2. Confirm with @koalie when all the content is ready for the pages specified in the user journeys (hopefully by 1 March)
3. Between 1-4 March, copy current staging site content to beta

Please let us know if you have any questions

Cheers!

Julia

**Comment by maries24** [comment]
Hi @jean-gui @AlanJIsaacson 

Isn't this task done? or at least in progress?

Thanks

**Comment by JuliaSang** [comment]
@maries24 just to confirm, if it's been done now, it needs to be done again just before we retest on w/c 7th March, so that all the test journeys are on beta with the latest content.

**Comment by vivienlacourba** [comment]
Closing as this was handled by @jean-gui before the w/c 7th March.
