### ISSUE TITLE
rss feed missing from news type listing pages

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#120]
On discussion, it was felt it would be useful to have the rss feed showing on news-type listing page. Currently it is only available on post pages. 

https://www-staging.w3.org/news/
https://www-staging.w3.org/news/1999/w3c-issues-xslt-and-xpath-recommendations/

**Comment by vivienlacourba** [comment]
With @jean-gui we also noted that RSS feeds were not mentioned in the page meta. They should be added for better discoverability by feed clients.

**Comment by vivienlacourba** [comment]
> On discussion, it was felt it would be useful to have the rss feed showing on news-type listing page. Currently it is only available on post pages.

FYI this is inline with the [specification for News listing pages](https://docs.google.com/document/d/1NRXvIO4kDs2leAFVF-zqJxNKGMbrRDL3MaQDOjp4WHI/edit#bookmark=id.9uni5lpltcm) which mentions:
> This template is made up of the following components:
> (...)
> RSS feed subscription links

@JuliaSang could you confirm if S24's recommendation is to have the RSS feed info displayed on **both** the listing page and the post pages, or only on the listing page.

**Comment by vivienlacourba** [comment]
@JuliaSang indicates that the pre-footer section is missing see: https://design-system.w3.org/components/pre-footer.html

**Comment by vivienlacourba** [comment]
> @JuliaSang could you confirm if S24's recommendation is to have the RSS feed info displayed on **both** the listing page and the post pages, or only on the listing page.

@JuliaSang confirmed that it should be on both pages as documented in the design system.

**Comment by maries24** [comment]
related to issue #122 
Need to add pre-footer to all listing pages: https://design-system.w3.org/components/pre-footer.html

**Comment by jean-gui** [comment]
Pre-footer is now there, but we are still missing links in page meta

**Comment by jean-gui** [comment]
Should be all set:
https://www-staging.w3.org/news/
https://www-staging.w3.org/news/2022/w3c-invites-implementations-of-epub-3-3-epub-reading-systems-3-3-epub-accessibility-1-1/

**Comment by vivienlacourba** [comment]
> Should be all set:
> https://www-staging.w3.org/news/
> https://www-staging.w3.org/news/2022/w3c-invites-implementations-of-epub-3-3-epub-reading-systems-3-3-epub-accessibility-1-1/
> (...)
>  https://www-staging.w3.org/blog/2022/epub-3-3-is-now-in-cr/

@jean-gui looking at those 2 URIs I noticed a small diff in the casing of the text of these RSS links
"Subscribe to our news feed"
"Subscribe to our News feed"
"Subscribe to our Blog feed"

**Comment by vivienlacourba** [comment]
> https://www-staging.w3.org/ecosystems/publishing/

Is this the right URI? as that page does not seem to have an RSS feed.

**Comment by jean-gui** [comment]
Casing should be fixed. Regarding the missing feed on publishing ecosystem, that was a caching issue.

**Comment by jean-gui** [comment]
I've also added the pre-footer to ecosystems: https://www-staging.w3.org/ecosystems/publishing/
