### ISSUE TITLE
Post template with no related content pushes feed to the right

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-website#121]
**Describe the issue**
When a page using the post template doesn't have related content, the RSS feed section takes its place to the right-hand side.

I'm not sure if this is an issue with the design system or how we use it.

**URL**
See https://www-dev.w3.org/blog/2021/blog-post-in-english-and-french/ for example, compared to https://www-dev.w3.org/blog/2021/blog-post-related-to-transportation-ecosystem/.

**Recommended solution**
A potential solution would be to always have a `<section class="related">` even if it's empty. But this seems like a workaround to me.
It may be cleaner to change the CSS so that only this section can go to the right, nothing else.

**Comment by vivienlacourba** [comment]
Another example: https://www-staging.w3.org/press-releases/2021/webauthn-mooc/

**Comment by NicolaSaunders** [comment]
Just looking at the static templates I originally built, the RSS section was never meant to sit within the 'content' grid. It should indeed sit within 'main'. So that fix should work just fine.
