### ISSUE TITLE
Missing "Get press releases by email" and "write to the W3C comms team" info on press releases listing page

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#122]
**Describe the issue**

The [specification](https://docs.google.com/document/d/1NRXvIO4kDs2leAFVF-zqJxNKGMbrRDL3MaQDOjp4WHI/edit#bookmark=id.9uni5lpltcm) mention:
> In the case of Press releases, the page contains two mailto links:
> - Link to ‘Get press releases by email’ (mailto: w3c-news-request@w3.org)
> - Link to ‘write to the W3C comms team’ (mailto: w3t-pr@w3.org)

Those info are not yet present on the new page, they should be added.

**URL**

https://www-staging.w3.org/press-releases/

**Comment by vivienlacourba** [comment]
@JuliaSang indicates that the pre-footer section is missing see: https://design-system.w3.org/components/pre-footer.html#post-listing-generic-pre-footer

**Comment by maries24** [comment]
related to #120 
Pre-footer missing from all listings: https://design-system.w3.org/components/pre-footer.html

**Content per listing type:**
Press release listings: 'generic' pre-footer with links as specified in the design system
Blog listings: RSS feed
Events listings: RSS feed and links to archives
News listings: RSS feed
Category listings: RSS feed

**Comment by jean-gui** [comment]
Pre-footer has been added to all listings following info provided by @maries24.

I don't believe we have category listings though. 

We don't have per listing type category feeds either so if someone is on https://www-staging/blog/category/accessibility/ for example, we don't have a corresponding feed and add a link to the global blog feed.
