### ISSUE TITLE
Content entry has accidentally removed the vertical spacing

### ISSUE THREAD

**Issue by NicolaSaunders** [w3c/w3c-website#126]
While reviewing the vertical spacing today we have spotted at least two pages where the spacing between headings and paragraphs has collapsed. We believe this is the result of content having been copied and pasted and including some unwanted markup.

Here are two examples:

* https://www-staging.w3.org/ecosystems/e-commerce/
(Roughly 3/4 down the page, beneath "Why join" - the subheading "Our values revolve around building the web for all")

* https://www-staging.w3.org/ecosystems/network-communications/
(Roughly halfway down the page, beneath "WebRTC reshaping the communication landscape")

Inspecting the collapsed content, in both examples wrapping `div` elements are responsible for the lack of vertical spacing. Removing these should reinstate the correct spacing.

**Comment by koalie** [comment]
Fixed and I'm now looking at all of the others, into the source, to look for DIVs and remove them.
