### ISSUE TITLE
Toggle group navigation behaves inconsistently in mobile Chrome

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#129]
When I browse around a group page on the beta site, for example [Accessibility Guidelines Working Group](https://beta.w3.org/groups/wg/ag/) using Chrome on my mobile phone (a Pixel 3XL), the 'Toggle group navigation' dropdown behaves inconsistently: if I tap it to toggle it open then select another page like Participants or Tools, the page is loaded with the 'Toggle group navigation' dropdown in an unpredictable state: sometimes it's missing and the list of subpages is presented with no 'Toggle group navigation' toggle to hide them again, and sometimes the Toggle group navigation dropdown appears in its expected collapsed state.

This also happens using the responsive developer tools in Chrome on my desktop system. It doesn't seem to happen in Firefox's responsive design mode.

Also, for what it's worth I would much rather these links were always available, in a more compact form; quick mockup:

Current:
![Screen Shot 2022-02-16 at 10 40 58 AM](https://user-images.githubusercontent.com/7144396/154335201-0f57b5e0-1d8b-47e9-b827-055bad6b9f7c.png)

Suggested revision:
![Screen Shot 2022-02-16 at 10 46 45 AM](https://user-images.githubusercontent.com/7144396/154335264-1098abc6-2742-4bc0-bd0a-15b47f06bfba.png)

**Comment by vivienlacourba** [comment]
> When I browse around a group page on the beta site, for example [Accessibility Guidelines Working Group](https://beta.w3.org/groups/wg/ag/) using Chrome on my mobile phone (a Pixel 3XL), the 'Toggle group navigation' dropdown behaves inconsistently: if I tap it to toggle it open then select another page like Participants or Tools,

I could not reproduce this on my phone.

> the page is loaded with the 'Toggle group navigation' dropdown in an unpredictable state: sometimes it's missing and the list of subpages is presented with no 'Toggle group navigation' toggle to hide them again, and sometimes the Toggle group navigation dropdown appears in its expected collapsed state.

That I could easily reproduce by simply reloading that page a couple of times!

See screenshots of the same page being displayed differently simply after a reload. 
With toggle group navigation             |  With regular group navigation
:-------------------------:|:-------------------------:
![Screenshot_2022-02-24-16-41-19-050_com android chrome](https://user-images.githubusercontent.com/2012282/155558445-d925375d-3367-4fa6-961d-b7422e9c55bd.jpg)  |  ![Screenshot_2022-02-24-16-41-08-409_com android chrome](https://user-images.githubusercontent.com/2012282/155558368-58b96dff-f4b0-4146-9bc7-873015a7c462.jpg)

**Comment by maries24** [comment]
This issue is similar to #109. I have now made all the scripts dependent on the DOM being loaded to only fire after the DOM is indeed loaded. This should therefore be sorted.

Feel free to re-open if not!
