### ISSUE TITLE
Listing page: posts - Pre footer looks a bit dry

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#13]
_Page: https://w3c-dev.studio24.dev/posts/index.html_

At the end of the page, the pre footer section seems unfinished and looks a bit dry (it it only has 2 links) in particular compared to the one used on [the events list page](https://w3c-dev.studio24.dev/listing-events/index.html).

Current pre footer section (between pagination links and page footer):
![Screenshot from 2021-07-16 19-49-16](https://user-images.githubusercontent.com/2012282/125988744-6390f81b-8da1-4583-93b5-590b7b3c4146.png)

**Comment by IanAxton** [comment]
Where possible we should be following the style we have on the events listing page. 
![Screenshot 2021-08-02 at 11 18 28](https://user-images.githubusercontent.com/88315515/127846369-988e1576-603c-4aa7-83aa-c6e98fdf1286.png)

Giving the links a title would help. 
for example. 
'Keep updated' and 'Contact us'

**Comment by NicolaSaunders** [comment]
I have updated the links on the page referenced so they are now preceded by a heading.
