### ISSUE TITLE
Use lazy loading for images in footer

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#130]
When I load a page on the [beta site](https://beta.w3.org/), there are two images in the footer ([twitter.svg](https://cdn.w3.org/assets/website-2021/svg/twitter.svg) and [github.svg](https://cdn.w3.org/assets/website-2021/svg/github.svg)) that are loaded with normal priority, occupying browser download slots that could be put to better use.

I suggest adding loading=lazy to those two image references in [footer.html.twig](https://github.com/w3c/w3c-website-templates-bundle/blob/main/templates/components/styles/footer.html.twig)

**Comment by jean-gui** [comment]
Done.
