### ISSUE TITLE
Deploy revamped W3C logo

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#136]
At some point before we open the beta, I'll want us to deploy the [revamped W3C logo](https://www.w3.org/Press/Plan/Icons/2021-revamp/), including making part of the templates. #kthx!

**Comment by koalie** [comment]
(I applied the "high priority" label so that we don't forget to do it before opening the beta)

**Comment by vivienlacourba** [comment]
Per systeam new convention on serving website assets we should move those logos under cdn.w3.org.

**Comment by vivienlacourba** [comment]
@koalie will work with Bert to provide clean filenames and ensure we have a PNG version available for all SVG files. We agreed that there is no need to copy the old version of the W3C logo.

@jean-gui will then copy those in a new GitHub repository "w3c/logos" (under a "w3c" directory to ease file organization) and deploy the content of this repository directly under https://cdn.w3.org/assets/logos/

**Comment by koalie** [comment]
> @koalie will work with Bert to provide clean filenames and ensure we have a PNG version available for all SVG files. We agreed that there is no need to copy the old version of the W3C logo.

Done and [shared in email](https://lists.w3.org/Archives/Team/team-website-redesign/2022Mar/0000.html) Friday night.

**Comment by jean-gui** [comment]
Logos are now in the cdn, see [my reply to this email](https://lists.w3.org/Archives/Team/team-website-redesign/2022Mar/0002.html).
