### ISSUE TITLE
Issues with link target widths and menu behavior on mobile

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#137]
When I browse [the beta site](https://beta.w3.org/) on my phone and tap Menu to open the Menu, the first level menu allows me to tap anywhere on the line to open a submenu, for example to the right of 'Get involved'. If I then tap to the right of one of those items, for example 'Publishing', it reverts to the parent menu instead of selecting the Publishing entry.

It would be good to make the link targets span the full widths in all the menus to be consistent, and for convenience for right-handed people who tap with their thumbs.

Also, when selecting a menu item (for example Publishing) by tapping on the Publishing text, the menu reverts to the parent menu while the next page is loading which is unexpected/confusing. It would be better for the menu to remain as is, or disappear completely when an item is selected.

**Comment by NicolaSaunders** [comment]
I have refactored the navigation to address this issue - please refer to the branch [hotfix/refactor-global-nav](https://github.com/w3c/w3c-website-templates-bundle/tree/hotfix/refactor-global-nav).

**Comment by deniak** [comment]
Fixed by https://github.com/w3c/w3c-website-templates-bundle/pull/103
