### ISSUE TITLE
Technical reports Searched State (all reports) – appears to have Accessibility tag selected

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#14]
The current staged version of the [Technical Reports Searched State (all reports)](https://w3c-dev.studio24.dev/technical-reports-v2/search-results-all.html) has the 'Accessibility' tag checked, and the text next to Advanced filters indicates the view is limited to Accessibility.

I think this is a small mistake in the staged version (likely copied from the '[reports tagged with accessibility](https://w3c-dev.studio24.dev/technical-reports-v2/search-results-a11y.html)' page)

**Comment by NicolaSaunders** [comment]
Closing as this is specific to an older prototype version.
