### ISSUE TITLE
Alumni page has incorrect breadcrumb

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#141]
The Alumni page at https://beta.w3.org/staff/alumni/ currently uses an incorrect breadcrumb.

It should be "Home > Staff > Alumni" (instead of "Home > Alumni")

**Comment by jean-gui** [comment]
Fixed. I realized that those staff pages are likely only going to exist in English. I'm not sure how we are going to handle that.

**Comment by vivienlacourba** [comment]
Fixed on staging.
