### ISSUE TITLE
Landing Page – Internationalization, Privacy and Security Links Gives User 404 Error Message

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#144]
It has been observed by the tester that when attempting to access the ‘Internationalization’, ‘Privacy’ or ‘Security’ links within the landing page, the user is directed to a 404-error message. It would be expected that when the user accesses any of these links that they are directed to the relevant pages.

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/ 
2.	Click either the ‘Internationalization’, ‘Privacy’ or ‘Security’ link
3.	Observe issue – user is directed to a 404 error page

Environment observed on:
Windows 10 – Chrome 99

This issue is also observed on: 
iPhone 12 Pro – iOS 15 – Safari 15
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Video (attached)

Version: 
https://beta.w3.org/ - 07/03/2022

Severity:
3.Minor Impact on Functionality 

https://user-images.githubusercontent.com/16608216/157017511-fa7ac27c-fafa-48ec-9831-871e4e9ee8f1.mp4

**Comment by Zoonou-Test** [comment]
This issue has also been observed within the 'Our mission' page.

URL: https://beta.w3.org/mission/ - 07/03/2022

Environments:
Windows 10 - Chrome 99
iPhone 12 Pro - iOS 15 - Safari 15

**Comment by koalie** [comment]
The content has been added since then.
