### ISSUE TITLE
Footer – Multiple Links to Pages With No Content

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#146]
It has been observed that multiple links in the websites Footer take the user to pages that do not have any content. It is expected that the pages linked to should have relevant content. 

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/ 
2.	Scroll down to see the footer 
3.	In footer, elect ‘Contact’
4.	Observe – User is taken to Contact page with no content
5.	In footer, select ‘Help’
6.	Observe – User is taken to Help page with no content
7.	In footer, select ‘Sponsor’
8.	Observe – User is taken to Sponsor page with no content
9.	In footer, select ‘Donate’
10.	Observe – User is taken to Donate page with no content
11.	In footer, select ‘Legal’
12.	Observe – User is taken to Legal page with no content

Environment observed on:
Windows 10 – Chrome 98

This issue is also observed on: 
Google Pixel 4a – Android 11, Chrome 98
Windows 10 – Firefox 97
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Screen recording

Version: 
https://beta.w3.org/ - 07/03/2022

Severity:
5.Feature Enhancement/Suggestion/Query

https://user-images.githubusercontent.com/16608216/157023660-53bcbd06-a1e2-41c2-8d50-552adada4be1.mp4

**Comment by vivienlacourba** [comment]
The footer links have all been updated.
