### ISSUE TITLE
Footer – Cookies Link Takes User to Document Not Found Page

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#147]
It has been observed that the Cookies Link in the website footer does not take the user to a Cookies page. It instead takes the user to a page saying ‘DOCUMENT NOT FOUND’ with no information on Cookies. It is expected that the Cookies link should take the user to a Cookies page with relevant information as is stand for websites using cookies

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/cookies or select ‘Cookies’ link in website footer
2.	Observe – ‘DOCUMENT NOT FOUND’ page is displayed to the user with no information on cookies 

Environment observed on:
Windows 10 – Chrome 98

This issue is also observed on: 
Windows 10 – Firefox 97
Google Pixel 4a – Android 11, Chrome 98
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Screenshot

Version: 
https://beta.w3.org/cookies - 07/03/2022

Severity:
5.Feature Enhancement/Suggestion/Query

![Footer – Cookies Link Takes User to Document Not Found Page](https://user-images.githubusercontent.com/16608216/157026843-08d0330e-2249-42dc-8e20-1ef6e4e68061.PNG)

**Comment by maries24** [comment]
Related to issue [#146](https://github.com/w3c/w3c-website/issues/146) and to be addressed at the same time.

**Comment by vivienlacourba** [comment]
Upon further consideration this page has been removed and the link removed from the footer.
