### ISSUE TITLE
[QUERY] Ecosystems – Multiple Placeholder Images Present

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#148]
It has been observed by the tester that within the ‘Ecosystems’ page, there are multiple placeholder images present. It is queried if the images should no longer contain placeholder graphics.

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/ecosystems/ 
2.	Scroll through the page
3.	Observe issue – there are multiple placeholder images present.

Environment observed on:
Windows 10 – Chrome 99

This issue is also observed on: 
iPhone 12 Pro – iOS 15 – Safari 15
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Screenshot (attached)

Version: 
https://beta.w3.org/ecosystems/ - 07/03/2022

Severity:
5.Query
![QUERY  Ecosystems – Multiple Placeholder Images Present](https://user-images.githubusercontent.com/16608216/157027426-3ffbdad7-8a8f-444f-b9ca-3b5c38e507ba.PNG)

**Comment by koalie** [comment]
Photos have now replaced the placeholders.
