### ISSUE TITLE
[QUERY] Automotive & Transportation – Placeholder Image Present

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#149]
It has been observed by the tester that within the ‘Automotive & Transportation’ page of the website, there is a placeholder image present. It is queried if this is intended or if the graphic should have been updated to a relevant image.

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/ecosystems/automotive-transportation/ 
2.	Scroll down the page
3.	Observe issue – there is a placeholder image still present on the page

Environment observed on:
Windows 10 – Chrome 99

This issue is also observed on: 
iPhone 12 Pro – iOS 15 – Safari 15
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Screenshot (attached)

Version: 
https://beta.w3.org/ecosystems/automotive-transportation/ - 07/03/2022

Severity:
5.Query
![QUERY  Automotive   Transportation – Placeholder Image Present](https://user-images.githubusercontent.com/16608216/157029889-4cbceeb1-bda1-4139-861c-f43f0660e8a6.PNG)

**Comment by koalie** [comment]
Photo has now replaced the placeholder image.
