### ISSUE TITLE
Technical Reports Searched State (any report tagged with accessibility) – simplify text of selected filters

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#15]
On the [Technical Reports Searched State (any report tagged with accessibility)](https://w3c-dev.studio24.dev/technical-reports-v2/search-results-a11y.html) page the text next to Advanced filters and following 'Showing 85 reports across 18 families' is quite long and hard to scan quickly:

> Advanced filters (Draft Standards, Candidate Standards, Standards, Draft Notes, Notes — Accessibility)

When all the entries in a given category are selected, I suggest simplifying the text to 'All':

> Advanced filters (Status: All — Tag: Accessibility)

> Showing 85 reports across 18 families, filtered by Status: All — Tag: Accessibility

Similarly when all Tags are selected, for example if displaying all Standards:

> Advanced filters (Status: Standards — Tag: All)

> Showing 85 reports across 18 families, filtered by Status: Standards — Tag: All

Another option would be to omit the text completely when all entries are selected for a given filter, for example:

> Showing 85 reports across 18 families, filtered by Tag: Accessibility

> Showing 85 reports across 18 families, filtered by Status: Standards

**Comment by deniak** [comment]
That's an interesting suggestion as it raises the question of how we should consider the filters if none of the options of a given category are selected.
I expect selecting none would be equivalent to 'All' and if that's the case, it feels weird to display 'All' when nothing is selected. So I guess your last suggestion would work better.

**Comment by deniak** [comment]
We will experiment the different options during the implementation

**Comment by gosko** [comment]
Hi @deniak, related to this issue the text 'Filter by reports' in the advanced filter options seems like it would be better as 'Filter by status' or 'Filter by type'. In my proposed text above I used 'Status' but I don't know what terminology we typically use to distinguish types of reports. I see our [current TR page](https://www.w3.org/TR/) uses 'Status'.

**Comment by deniak** [comment]
@gosko, good catch. @NicolaSaunders, can you please update the `h2` from 'Filter by reports' to 'Filter by status'?

**Comment by NicolaSaunders** [comment]
@deniak @gosko This change has now been made to the static prototype site and the design system site.
