### ISSUE TITLE
Automotive & Transportation – Common Vehicle Interface Initiative Links Gives User a 404 Error Message

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#150]
It has been observed by the tester that when attempting to select the ‘Common Vehicle Interface Initiative’ link within the page, the user is directed to a 404-error message. It would be expected that when the user accesses the link, they are directed to a page containing the relevant information.

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/ecosystems/automotive-transportation/ 
2.	Navigate to the ‘Common Vehicle Interface Initiative’ section
3.	Click the ‘Common Vehicle Interface Initiative’ link
4.	Observe issue – user is directed to a 404-error message

Environment observed on:
Windows 10 – Chrome 99

This issue is also observed on: 
iPhone 12 Pro – iOS 15 – Safari 15
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Video (attached)

Version: 
https://beta.w3.org/ecosystems/automotive-transportation/ - 07/03/2022

Severity:
3.Minor Impact on Functionality 

https://user-images.githubusercontent.com/16608216/157031827-4a66f594-93ed-4708-ad18-4ad9faee42a6.mp4

**Comment by vivienlacourba** [comment]
Fixed on staging.
