### ISSUE TITLE
[QUERY] Membership – Placeholder Image Present

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#151]
It has been observed by the tester that within the ‘Membership’ section, there is a placeholder image present within the page. It is queried if this placeholder image is intentional or if it should have been updated to a relevant image.

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/membership/ 
2.	Scroll down to the ‘Quick list of Member benefits’ section
3.	Observe issue – there is a placeholder image present

Environment observed on:
Windows 10 – Chrome 99

This issue is also observed on: 
iPhone 12 Pro – iOS 15 – Safari 15
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Screenshot (attached)

Version: 
https://beta.w3.org/membership/ - 07/03/2022

Severity:
5.Que
![QUERY  Membership – Placeholder Image Present](https://user-images.githubusercontent.com/16608216/157036505-5158844d-d1e0-408d-9413-93d31821715a.PNG)
ry

**Comment by koalie** [comment]
A photo has now replaced the placeholder.
