### ISSUE TITLE
Membership – W3C Membership Application 404 Error Message

### ISSUE THREAD

**Issue by Zoonou-Test** [w3c/w3c-website#152]
It has been observed by the tester that when attempting to access the ‘W3C Membership Application’ link within the ‘Filling out the application’ section, the user is directed to a 404-error message.

Steps to Recreate: 
1.	Go to URL: https://beta.w3.org/membership/join/#signing 
2.	Navigate to the ‘Filling out the application’ section
3.	Click the ‘W3C Membership Application’
4.	Observe issue – the user is directed to 404 error message

Environment observed on:
Windows 10 – Chrome 99

This issue is also observed on: 
iPhone 12 Pro – iOS 15 – Safari 15
Believed to be global

Reproduction rate:
100% - Consistently reproducible. Can reproduce every time attempted.

Supporting material:
Video (attached)

Version: 
https://beta.w3.org/membership/join/#signing - 07/03/2022

Severity:
3.Minor Impact on Functionality 

https://user-images.githubusercontent.com/16608216/157037609-646a8be6-e468-4bb4-b037-e95a66bb4d74.mp4

**Comment by koalie** [comment]
The redirects being in place, the link no longer returns a 404 error.
