### ISSUE TITLE
Column breaks missing from nav menus on beta site

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#157]
The [Navigation component](https://design-system.w3.org/components/navigation.html) includes a way to add a break after a given menu item, for more logical grouping of items in the 'Get involved' and 'News and events' menus. This can be seen on the [header nav page](https://design-system.w3.org/code/header-nav.html) of the design system docs, in Chrome:

![Screen shot of Get involved menu expanded in header nav in Chrome](https://user-images.githubusercontent.com/7144396/157740339-e00a215a-f0b7-4664-83c5-eb7a21ff9869.png)

This is implemented using a `break-after` class on the 'Web of things' list item.

This markup is missing from the nav menus on the [beta site](https://beta.w3.org/), resulting in the list of ecosystems being split across columns:

![Screen Shot of Get involved menu expanded on beta site in Chrome](https://user-images.githubusercontent.com/7144396/157745345-4b81d449-abf8-4bc2-8024-385ae4cc4273.png)

Similarly for the 'News and events' menu, a `break-after` should be added to the last item in the News column.

It might be worthwhile to consider adding these breaks to the Groups and About menus as well, and possibly reordering items.

![Screen Shot of current Groups menu](https://user-images.githubusercontent.com/7144396/157744357-79aa2aba-88b2-40d9-8840-e741aa00a7eb.png)
For the Groups menu maybe 'Advisory board' should be in the left column, and 'Participant guidebook' should be at the top of the right column? (or maybe it's fine as is; just an idea)

![Screen Shot 2022-03-10 at 11 57 09 AM](https://user-images.githubusercontent.com/7144396/157744503-df2369d0-5ad4-42e3-b2f6-60f73956d6f2.png)

For the About menu I suggest moving 'Sponsoring W3C' to the top of the right menu, Evangelists to the bottom of the left menu, and possibly moving Careers lower down somewhere on the right column, or to the bottom of the left column.

note: the `break-after` class to force a second column does not work in Firefox, as documented in our [internal discussion on basecamp](https://3.basecamp.com/3091560/buckets/15695452/todos/3799181667). (I am not suggesting we do anything about this, just noting it in case others are trying to reproduce this issue using Firefox.)

**Comment by vivienlacourba** [comment]
> For the About menu I suggest moving 'Sponsoring W3C' to the top of the right menu, Evangelists to the bottom of the left menu, and possibly moving Careers lower down somewhere on the right column, or to the bottom of the left column.

HI @gosko, I did this reorder on www-staging as your suggestion made sense to me (but the proper handling of the 2 column break is still to be done).

**Comment by maries24** [comment]
Hi @vivienlacourba 
I went for the second option. You can now 'tick' the option of starting a new column after a navigation item.

**Comment by vivienlacourba** [comment]
Tested successfully on dev and staging. I will be deployed on beta later.
