### ISSUE TITLE
News and events menu is missing entries

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#158]
Based on our internal sitemap sheet, the 'News and events' menu of the [beta site](https://beta.w3.org/) should have more entries under the Events column: Talks, Workshops, Happenings, TPAC, Conferences.

The [design system site](https://design-system.w3.org/code/header-nav.html) also includes another entry called Meetings, but that isn't in the current sitemap sheet so I gather it's no longer needed.

**Comment by vivienlacourba** [comment]
Upon review of the sitemap @alexandralacourba and @koalie decided to only keep the "Events" entry in the menu.
From the [Events page](https://beta.w3.org/events/) you can see the lists of all events and can filter that list by event type.
