### ISSUE TITLE
Technical Reports pages – minor editorial / text issues

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#16]
The text under the Standards filter on the [Technical reports pages](https://w3c-dev.studio24.dev/technical-reports-v2/index.html) currently says:

> Standards are normative. They are widely reviewed and legal requirements. Learn about our Standards process.

I believe there is a word missing here, maybe it should be 'They are widely reviewed and _have_ legal requirements' or '... _have IPR commitments_' (the specific text is likely a content question for our team to decide)

> Notes are informative. They give you use cases, practices, and code examples.

I believe practices might be better as 'best practices' (again, likely a content question)

**Comment by gosko** [comment]
While reviewing the [blog post](https://w3c.studio24.net/updates/redesigning-the-landing-page-for-technical-reports/) just now I see 'legal requirements' appears there several times as well, so this doesn't seem to be a typo. I believe there may be a misunderstanding about the legal status of our standards – there may be some jurisdictions that have some of our specifications as legal requirements but I don't think it's right to refer to them this way in general. (In my initial comment above I was assuming this had something to do with our IPR process but that doesn't seem to be the case)

**Comment by JuliaSang** [comment]
@deniak @koalie please can you review the page micro copy - this can be updated by W3C when the template is implemented.

**Comment by koalie** [comment]
I'm on it, @JuliaSang

**Comment by koalie** [comment]
I believe the description under the "Standard" filter should be updated in this manner:
s/They are widely reviewed and legal requirements./They are endorsed by W3C and its Members, and should be widely deployed./

If ",and should be widely deployed" makes the description too long, it can be ignored.

Coralie

**Comment by JuliaSang** [comment]
Thanks @koalie 

@fiinix and I have just been talking to @deniak and wanted to double check if the final copy should mention 'standards can sometimes to called recommendations' to help users who might not be so familiar. Here is what we have for [version 4](https://w3c-dev.studio24.dev/technical-reports-v4/index.html):  

> Standards
> Standards are normative. They are widely reviewed and legal requirements. They are endorsed by W3C and its Members. Sometimes we call them Recommendations. Learn about our Standards process.

Would you be able to review the whole bit of copy and confirm the final text in full? Many thanks!

**Comment by koalie** [comment]
> > Standards
> > Standards are normative. They are widely reviewed and legal requirements. They are endorsed by W3C and its Members. Sometimes we call them Recommendations. Learn about our Standards process.
> 
> Would you be able to review the whole bit of copy and confirm the final text in full? Many thanks!

Let's go for something that is less suggestive of whim :) Here is the full revised snippet:

> > Standards
> > W3C publishes Recommendations which are considered Web standards. Standards are normative. They are endorsed by W3C and its Members. Learn about our Standards process.

**Comment by JuliaSang** [comment]
Thank you @koalie! I will assign to @NicolaSaunders to implement this final copy. 

@NicolaSaunders please make the following copy changes to:

- https://w3c-dev.studio24.dev/technical-reports-v4/index.html
- https://w3c-dev.studio24.dev/technical-reports-v4/search-results.html

1. Change 'Advanced search options' to 'Advanced filter options'
2. Change 'Search by reports' to 'Filter by reports'
3. Change 'Search by tags' to 'Filter by tags'
4. Change the copy from:
'Standards
Standards are normative. They are widely reviewed and legal requirements. Sometimes we call them Recommendations. Learn about our Standards process.

to

Standards
W3C publishes Recommendations which are considered Web standards. Standards are normative. They are endorsed by W3C and its Members. Learn about our Standards process.

**Comment by NicolaSaunders** [comment]
These changes have been made and can be seen on the [static prototype site](https://w3c-dev.studio24.dev/technical-reports-v4/search-results.html), and have been added to the [design system](https://design-system.w3.org/templates/tr.html).

**Comment by JuliaSang** [comment]
@deniak @gosko Please can you review the changes, and if you are happy with them close the ticket (or leave us a comment if there is further work related to this issue). Many thanks, Julia.

**Comment by deniak** [comment]
Looks good to me!

**Comment by gosko** [comment]
Looks good, thank you!
