### ISSUE TITLE
Scale user menu to width of contents

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#160]
Currently the user menu on the [beta site](https://beta.w3.org/) uses a fixed width, which looks a bit strange for users whose names and email addresses are shorter since the menu contents are on the left while the menu header is on the right.

![Screen Shot of user menu with short email address](https://user-images.githubusercontent.com/7144396/158439144-093090ce-c65c-4722-a148-36c6f4c874da.png)

But more importantly, users with longer email addresses will have them wrapped to multiple lines, broken in the middle somewhere.

![Screen Shot of user menu with long email address](https://user-images.githubusercontent.com/7144396/158438933-f028f2cf-b457-41b2-8ba5-0bde6d672d35.png)

I know there are CSS rules we could add to cause these to wrap better (for example wrapping at word boundaries), but it might be better to make the width of the menu proportional to its contents, if that's easy to do.

I think all that would be needed would be to remove `width: rem(250);` from `.account-menu` in [_header.scss](https://github.com/w3c/w3c-website-templates-bundle/blob/main/assets-src/styles/sass/60-advanced-components/_header.scss)

I checked our user database to get an idea of typical lengths of email addresses used at our site and the median length is 21 characters, and 95th percentile is 30 characters. The wrapped example in the screenshot above is 28 characters. I would guess something like 1/3 of users would have their email addresses wrapped with the current CSS.

**Comment by vivienlacourba** [comment]
I agree that we should try to accommodate longer names and email addresses.
