### ISSUE TITLE
Technical Reports pages – list the specific translations available

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#17]
On [Technical reports v3: showing, all reports](https://w3c-dev.studio24.dev/technical-reports-v3/search-results-all.html) when there are translations available for a given report the text reads (for example):

> 4 translations for Architecture of the World Wide Web, Volume One

![screen shot showing current text](https://user-images.githubusercontent.com/7144396/130833583-85e1d722-90a4-4d8a-bd6b-ddfbfb5480ec.png)

I expect anyone looking for a translation would find it quite frustrating to have to follow the link to determine if a translation is available in their preferred language.

I saw in the [blog post](https://w3c.studio24.net/updates/redesigning-the-landing-page-for-technical-reports/) that one goal of this design is to reduce the number of tab stops per report for the benefit of keyboard users, so I gather it is undesirable to include a direct link to each translation.

A good compromise might be to list the individual languages available within the link, for example

> Translations: Italiano, français, česky, Português-BR

![screen shot showing proposed text](https://user-images.githubusercontent.com/7144396/130834728-00c8bdb4-09a1-4a90-8a8a-a0260ddb5419.png)

This assumes there will be a landing page available that shows translations for a given report, but that seems to be the case with the proposed design as well.

**Comment by JuliaSang** [comment]
Discussed with @fiinix and @deniak and think this is a good idea. Going to assign to @NicolaSaunders to implement. 

@NicolaSaunders I'm sure you are on it, but if you want to have a chat with Carlos on his thoughts about implementing it in a way for screen-readers to understand, he had a couple of thoughts.

**Comment by fiinix** [comment]
The purpose of the original microcopy suggestion was to remove tab stops and make the link sensible for assistive technology (AT), such as screen readers which may not have the surrounding context when the link is announced. As in, "4 translations for Architecture of the World Wide Web, Volume One" is understandable in its own right.

The change suggestion is good. It does. however, bring back the issue of the link text now not working in its own., "Translations: Italiano, français, česky, Português-BR" doesn't make sense if you don't know what report it is referring to. This may not be an issue but it's worth raising.

To address this I suggest the following:

1. Keep current link text and add the languages. So using the previous example, the link text would be: "4 translations (Italiano, français, česky, Português-BR) for Architecture of the World Wide Web, Volume One"

Whilst we could recommend using an `aria-label` to enhance the link text the reality is that screen readers are inconsistent in how they read link texts when combined with aria-labels, some only read one value, others read both, leading to a confusing and inconsistent user experience.

**Comment by NicolaSaunders** [comment]
These changes have now been made and can be seen on the [static prototype site](https://w3c-dev.studio24.dev/technical-reports-v4/search-results.html), and have been added to the [design system](https://design-system.w3.org/templates/tr.html).

**Comment by JuliaSang** [comment]
@deniak @gosko Please can you review the changes, and if you are happy with them close the ticket (or leave us a comment if there is further work related to this issue). Many thanks, Julia.

**Comment by deniak** [comment]
While I agree with @gosko that having a direct link to the translated document can be more useful, it also adds more links which I understand doesn't help with the accessibility of the page. I would say let's use @fiinix suggestion for the beta version and we can still easily revise the translations if needed. @gosko WDYT?

**Comment by gosko** [comment]
The proposed change sounds good to me. It's a shame the spec title needs to be duplicated because it will add clutter to the otherwise clean list of reports. Hopefully screen reader software will converge on a common behavior someday.

Thanks for making this improvement!
