### ISSUE TITLE
Usability - logged in status

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#170]
There is no indication provided to users that they have successfully logged in.

Reference: Usability

**Issue ID: DAC_Logged_in_status_01**

URL: https://beta.w3.org/
Page title: We believe in one web for all 
Journey 3, Step 2
<img width="355" alt="logged in mobile" src="https://user-images.githubusercontent.com/20167528/159258256-41eb0099-54c1-45f4-af4e-521c20a38cfe.png">
<img width="829" alt="logged in" src="https://user-images.githubusercontent.com/20167528/159258266-7e4ee4ed-e466-4f06-a204-b56ce3a51a06.png">

Upon logging in, it is not easy for users to determine whether they have done so successfully.

As no 'Log out' button is available, which would by default indicate that a person had signed in, the only way that users were able to determine that they had managed to log in was by exploring the page to see whether additional content is available.

Once users reach 'My account' they were able to expand this to reveal additional content, which takes the user to their profile pages: however, relying on this alone to indicate that a user is logged in is not intuitive in that it requires users to navigate a reasonable amount of content before they are able to determine that they are in fact logged in.

**Current Code Ref(s):** 

```
<button type="button" class="button button--ghost with-icon--larger" data- trigger="account-menu" aria-expanded="false">
  <span class="sr-only">My account </span>
<div class="avatar avatar--small icon"><img alt="" src="https://www.w3.org/2006/05/u/3gv70icr4ckk-sm.jpg" /></div> </button>
```

**Screen reader user comments:**
> “Having entered my credentials, I was taken back to the page from which I had originally activated the ‘My account’ link’, but I received no ‘success’ alert, or explicit indication that I was now logged in. Having expanded ‘My account’, which had now become a button instead of a link, I found profile information which would suggest I am logged in, however this is not obvious on page load after signing in. The issue is present with JAWS, NVDA.”

**Screen reader comments:**
> “While navigating the screen which appears after entering the login credentials using VoiceOver, I found no obvious change in the page that indicates that I am successfully signed in. I had to explore the page to determine whether additional content was now available. I tested in: iOS VoiceOver This also applies to TalkBack”

**Solution:**
Consider adding 'logged in' in parenthesis in the 'My account' link once users have logged in. Additionally, the span containing the 'My account' label has an 'sr-only' class implemented, but the corresponding CSS to hide the content has not been implemented, so this information remains visible. As this information should be visible to all users, the 'sr-only' class should be removed.

**Example** 

```
<button type="button" class="button button--ghost with-icon--larger" data- trigger="account-menu" aria-expanded="false">
<span>My account (logged in)</span>
<div class="avatar avatar--small icon">
<img alt="" src="https://www.w3.org/2006/05/u/3gv70icr4ckk-sm.jpg" />
</div> 
</button>
```

It is also advisable to implement a mechanism to enable users to log out again; all users that tested the service remarked that the lack of a 'Log out' link or button made it difficult to be certain that they were logged in. This is particularly important for instances where a user might be using a public computer.

**Comment by NicolaSaunders** [comment]
@maries24 The proposed solution of adding '(logged in)' as visually hidden text to the button which toggles the user account menu will meet accessibility requirements. Please note that the classname in the design system to use for this is `visuallyhidden`.

I also strongly agree with the testing feedback that there should be a clear mechanism for logging out which should be added to the account menu.

**Comment by jean-gui** [comment]
The logout link has now been implemented.

> Others will know they have successfully signed in as their avatar will now appear next to the 'My Account' copy.

@maries24 @NicolaSaunders This is not reliable as users who don't have a profile picture can't use that clue to know if they are logged in.

**Comment by vivienlacourba** [comment]
> The logout link has now been implemented.
> 
> > Others will know they have successfully signed in as their avatar will now appear next to the 'My Account' copy.
> 
> @maries24 @NicolaSaunders This is not reliable as users who don't have a profile picture can't use that clue to know if they are logged in.

I like @gosko initial suggestion of replacing "My account" by "Sign in" when the person is not logged in (like most sites do).

**Comment by NicolaSaunders** [comment]
I think it should be fine to use the suggestion from @gosko - have a link labelled "Sign in" and replacing this with the "My account" toggle button once a user has signed in.
