### ISSUE TITLE
Usability - login modal Dragon users cannot interact

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#171]
Dragon users found that they were unable to interact with the username and password form fields within the login modal in the expected manner.

Reference: Usability

**Issue ID: DAC_Login_modal_01**

URL: https://beta.w3.org/ 
Page: Sign in page 
Journey 2, Step 2a & 2b
<img width="863" alt="dragon" src="https://user-images.githubusercontent.com/20167528/159258580-5aa70c94-d8ff-4802-a93a-2b46823287ae.png">

Voice activation users found that they were not able to pick the Username and Password forms fields within the login modal by referencing either their visible label or component type.

They had to resort to using commands such as mouse grid to be able to focus the input fields in order to enter data into them.

Although it is suspected that this is due to the site being in staging, the authorisation modal should not prevent users from being able to interact with content in the expect manner.

**Voice activation user comments:**

> “I found that I was unable to move the focus into the input fields using voice activation commands such as ‘Click box’ and ‘Click Username/Password’. In order to move the focus into either of the input fields, I would have to use commands such as ‘Move Mouse’ or ‘Mouse grid’, which some users may not be aware of as they are not used on a regular basis.”
> I tested in: Microsoft Edge

**Voice activation user comments:**
>“I found I was unable to dictate into either of the 2 input fields in the normal manner, resulting in me having to use keyboard commands to dictate each letter or character which added a lot more time to the process.”
>I tested in: Microsoft Edge

**Solution:**
Although it is suspected that this is due the site being in staging, it is important that users are able to interact with all form fields in the anticipated manner.

**Comment by jean-gui** [comment]
Form-based auth using our authentication platform has been implemented instead of HTTP basic auth.
