### ISSUE TITLE
Usability - No error identification - sign in process

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#172]
Users are not presented with any form of error handling on incorrect or empty submission of form fields as it appears that no error validation is implemented.

Reference: Usability

**Issue ID: DAC_No_Error_identification_01**

URL: https://beta.w3.org/account/login/?redirect_url=https://beta.w3.org/ 
Page: Sign in
Journey 3, Step 2b
<img width="795" alt="error missing" src="https://user-images.githubusercontent.com/20167528/159259073-19d7501a-2cfb-440e-a4f1-7f8bae3e3536.png">

When users submit the Username and Password with errors, for example left empty or with incorrect data, no error handling is triggered. Users are not advised that an error has occurred, yet as they have not been logged in it is reasonable to assume that the form submission was not successful.

The page in this instance simply refreshes and users are presented with the login modal again. This is not the expected behaviour and will be confusing for most user groups, but particularly for users who rely on audio feedback to navigate or users who have a cognitive disability.

**Screen reader user comments:**
>“I activated the ‘Sign in’ button having left the ‘Username’ and ‘Password’ fields blank, and was surprised to see that exactly the same screen was re-displayed, with no indication that I had made one or more errors. I found that the same behaviour occurred when I entered incorrect credentials, with no indication being provided that an error had occurred (I would not expect to be told which field was in error, for security reasons, but only to be given an explicit warning that something was wrong.
As this may cause confusion for some people who utilise adaptive technology, an indication that an error has been committed should be incorporated into the dialog if possible.
>The issue is present with JAWS, NVDA.”

**Screen reader user comments:**
>“While navigating the login screen using VoiceOver and submitting the form with errors, I found that blind users are not able to identify any error message information at the time of testing. This will confuse users, as they will not be aware of what needs to be corrected, and what has happened on screen.
>This also applies to TalkBack.” I tested in: iOS VoiceOver.

**Voice activation user comments:**
>“When I tested for error handling by leaving the 2 input fields blank, I don’t get any error messages. It just reloads the ‘Sign in’, modal but doesn’t inform me where the error is. For example, if I fill in the username field but not the password field and click the ‘Sign in’ button, I don’t get an error message. It just reloads the sign-in modal with both fields blank so I wouldn’t know which fields the error was in.”  
>I tested in: Chrome

**Keyboard only user comments:**
>“When I tested for error handling by leaving the 2 input fields blank, I did not get any error messages, it just reloaded the sign-in modal. It did not inform me where the error was, for example, if I filled in the username field but not the password field and clicked the sign-in button, I did not get an error message, it just reloaded the sign-in modal with both fields blank, meaning I would not know which fields the error was in.”

>“I found when signing in and entering my password, I had no way of checking the spelling of what I had typed, I think it could be beneficial if there was a show password option.“
>I tested in: Chrome

**Solution:**
When errors occur throughout the service, errors must be notified to users in text; users should be made aware that an error has occurred, in addition to being informed as to where.

It is recommended that the word ‘Error:’ should be added to the beginning of the page `<title>` so screen readers read it out as soon as possible.

Additionally there should be some form of visual indication as to which fields have errors on a page to ensure that they stand out on the page to enable users to pick them out easily in order to correct them; this can take the form of an error message in a different colour adjacent to the field with errors.

Another suggestion, which might also help prevent submission with incomplete or incorrect data would be to provide a 'show password' mechanism to enable users to view the text that they are inputting into the form fields.

**Comment by vivienlacourba** [comment]
Same reason as https://github.com/w3c/w3c-website/issues/171#issuecomment-1084379680

**Comment by jean-gui** [comment]
Form-based login using our authentication platform has been implemented, and the form displays form errors.
