### ISSUE TITLE
Accessibility of non-contextual links

### ISSUE THREAD

**Issue by simonrjones** [w3c/w3c-website#175]
**Describe the issue**
Links on business ecosystems are "Learn more" without any context, this is an a11y issue.

**URL**
https://beta.w3.org/ecosystems/

**Recommended solution**
 Ideally change the link text to be contextual, e.g. "Learn more about e-Commerce."

**Comment by vivienlacourba** [comment]
I had already fixed this, but this is only visible on the staging site.
https://www-staging.w3.org/ecosystems/
