### ISSUE TITLE
Previous / Next page links missing disabled use case

### ISSUE THREAD

**Issue by dkyrychenko** [w3c/w3c-website#176]
**Describe the issue**
Pagination example does not offer suggestion for the use case when previous/next pages links are disabled.
When first page is active, previous page shouldn't be available, same for the last page. Paginator has to provide solutions on how to implement accessible paginator with disabled elements.

**URL**
[The URL where this problem occurs.](https://design-system.w3.org/components/pagination.html)

**Recommended solution**
- Add aria-disabled=true for previous / next pages (if so, decide whether such elements should still receive keyboard focus or not).
- Alternatively, prevent keyboard focus and hide from screen readers entirely.

**Comment by jean-gui** [comment]
Pagination does not include previous/next links anymore when on the first/last page

**Comment by meibegger** [comment]
@jean-gui Thanks a lot for the clarification. Would probably be useful to add this info to the description ... :)
