### ISSUE TITLE
Localized sites should have pages with translated title and breadcrumb

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#178]
**Describe the issue**
Titles and breadcrumbs are displayed in English on translated pages. These should also be translated in the right language.

**URL**
https://www-staging.w3.org/zh-hans/news/

/cc @xueyuanjia

**Comment by jean-gui** [comment]
I believe this is a content issue: those have to be translated in the CMS.

**Comment by xueyuanjia** [comment]
hi @jean-gui, do you mean that the existing English text on [https://www-staging.w3.org/zh-hans/news/](https://www-staging.w3.org/zh-hans/news/), e.g., "Homepage > News listing", "_menu" "Next", will need to be translated into Chinese via the CMS, when I editing each News item? I am ok with doing so though it seems a bit odd.🤔

**Comment by jean-gui** [comment]
Not per news item, the main navigation is defined only once in the CMS and needs to be translated, as well as a few other pages.

**Comment by koalie** [comment]
I believe this has been fixed in the meantime. Proof with a screenshot from today where the breadcrumbs and title are in the target language:
<img width="1346" alt="Screenshot 2024-08-27 at 16 09 29 " src="https://github.com/user-attachments/assets/a374123f-b7fb-4527-809e-b0cb9ae235c3">
