### ISSUE TITLE
Component needed to indicate current page is access-controlled

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#183]
We need a way to indicate that a given page is Member-confidential or otherwise access-controlled.

In the past on the W3C site we have used different colored backgrounds, icons and inline text to indicate the level of access for non-public pages.

<img width="789" alt="screenshot of W3C Member home page" src="https://user-images.githubusercontent.com/7144396/203391909-45458417-60f9-474a-89c5-56d167d78955.png">
<img width="737" alt="screenshot of W3C Member-restricted mailing list archives" src="https://user-images.githubusercontent.com/7144396/203391952-62286917-4d3b-4ae7-aa8d-4864bee3eb70.png">

It would be good to come up with something that works well with the redesigned site styles, allowing for the text to vary from page to page. (for example 'Member confidential' or 'Member restricted', 'Team confidential', 'Group-restricted')

The access-control indicator should be available as text in addition to any optional visual enhancements (colors, icons)

It should be fairly obvious and easy to spot, i.e. not too subtle.

One possibility for where to put it might be below the user menu, in line with the breadcrumbs but floated right.

<img width="1334" alt="mockup" src="https://user-images.githubusercontent.com/7144396/203392002-f6062610-f0af-440e-9e73-1ddeb57a62f0.png">

**Comment by gosko** [comment]
Hi @jean-gui, thanks for implementing this. Can you please document it on the design system site?

**Comment by vivienlacourba** [comment]
Re-opening so that it gets documented in: https://design-system.w3.org/components/

**Comment by jean-gui** [comment]
Done, see: https://design-system.w3.org/components/access-control-banner.html
