### ISSUE TITLE
Navigation link not displayed if the title contains the character '&' 

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#184]
When the option 'Display "On this page" navigation' is switched to 'On', the navigation link is not displayed if the title of the header contains the character '&'.
See for example the page https://www-staging.w3.org/sponsor/ 
The fourth link is empty because the title of the header 'Technology & Industry Sponsor' contains the character '&' .
If we replace '&' with 'and' the navigation link is displayed (this is what I did for the following link 'Event and Inclusion Sponsor')

**Comment by jean-gui** [comment]
Tentative fix at: https://github.com/strata/frontend/pull/97

**Comment by jean-gui** [comment]
Fixed
