### ISSUE TITLE
Blog filter alignment issue

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-website#188]
**Describe the issue**
In the post filter component, the button is not properly aligned with the search field, i is a bit too high.

**URL**
On https://design-system.w3.org/code/filters-posts.html

**Comment by NicolaSaunders** [comment]
Resolved by https://github.com/w3c/w3c-website-templates-bundle/commit/db7fa926d8ad0763b8ca024b2c8c19ef741d2089
