### ISSUE TITLE
Don't display the avatar and the label 'By: ' for blog posts without author

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#190]
We have some imported blog posts without author (likely when we deleted WP users without reassigning their posts), in this case, it would be better to not display the line 'By: ' on both blog post [1]  and blog listing [2], and the avatar on blog post.

[1] https://www-staging.w3.org/blog/2013/automotive-and-web-platform-bu/
[2] https://www-staging.w3.org/blog/2013/?page=7

**Comment by jean-gui** [comment]
@lcarcone The issue is that when you import, an empty author is created. If i remove this empty author as I've done for 2013/automotive-and-web-platform-bu then you don't see an empty author anymore. Do you know if you can prevent the import from creating those empty authors?

**Comment by lcarcone** [comment]
Addressed by removing the author from the imported blog posts where it was null or empty.
