### ISSUE TITLE
How to display comments in translated blog entries ?

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#192]
We have imported some blog posts from the Chinese website that were translations of existing English posts (without local comments).

Looking at one of them [1], we can see that the comments from the corresponding English posts are displayed in the Chinese post, mixing the two languages without specific language attributes.

Currently we cannot specify the language of a comment, what would be the best way to display comments for translated blog posts:
  . display comments only in the primary site and link to them for other sites (like what is done for testimonials and press releases)
  . display comments in translated blog posts with an  attribute lang="en" for each of them

The problem may be more complicated when we open comments for blog posts. Should they be opened only for posts in English or allowed for the other sites but in this case they will also be displayed (without the lang attribute) in the English version of the post when exists.

[1] https://www-staging.w3.org/zh-hans/blog/2020/happy-31st-birthday-world-wide-web/

**Comment by jean-gui** [comment]
It's possible to specify a siteId when creating comments. I can easily do that with the comment form, and you should be able to do it as well when importing. 

We can then decide to display only comments in a language, or all of them, with the proper lang attribute. I don't know what's better.

**Comment by jean-gui** [comment]
Blog posts should now only display comments in the same language.
