### ISSUE TITLE
avatar images are slow to load

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#194]
While browsing [a blog post on the beta site](https://beta.w3.org/blog/2022/w3c-developer-meetup-in-vancouver-canada-13-september/) I noticed mcf's avatar image was slow to load. When I open Developer Tools in firefox, select the Network tab then shift-reload I see there are a number of redirects involved: first https://www.w3.org/avatars/bf60d62e9d21103b36bbd487d7ebda81?s=48 which 301 redirects to https://www.w3.org/avatars/bf60d62e9d21103b36bbd487d7ebda81/?s=48 which 302 redirects to https://cdn.w3.org/thumbnails/48/avatars/4bpqodzdhewwowc8g4owkgw4skwo4kc.webp?x-version=1

It would be good to avoid either or both of these redirects if possible.

Also I noticed the avatar for my account in the user menu is a 200x200 image instead of 48x48, which is a bit surprising given that it is scaled down to 30x30.

**Comment by jean-gui** [comment]
There is now one fewer redirect (the first one). I believe the redirect to the cdn could be cached as the destination never changes. I'll look if I can add caching headers to it.

I have also changed the size of the avatar in the user menu to be 48x48.

**Comment by jean-gui** [comment]
Caching headers for the redirect were already there, so I believe there's nothing else to do.
