### ISSUE TITLE
Attributes for Ordered List element are not taken into account in the new style

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#195]
The following blog post contains an ordered list with the attribute start="2" (Point of Views from attendees) but its first item is displayed with '1'

https://beta.w3.org/blog/2018/chinese-museums-meet-to-talk-about-making-the-web-a-better-place-for-museums/

The default style for this type of list is replaced by specific rules in the new style but these rules do not take into account the 'start' attribute, resulting in a list starting with '1' instead of '2'.

There is a similar problem with the attributes 'reversed' (list items are in reverse order) and 'type' (using letters or roman numerals), ordered lists always display a decimal number from 1 to last item number

**Comment by lcarcone** [comment]
Those attributes for the element 'ol', as well as the attribute 'type' for the element 'ul', are only available for imported entries in the backend.
They should also be available for new entries

**Comment by NicolaSaunders** [comment]
I think the ordered lists not honouring the `start` attribute is a CSS issue, as we recently discovered on another project. It relates to using a custom counter on a pseudo element:

```
ol:not([class]) {

	counter-reset: count;
	list-style-type: none;
	padding-inline-start: 1.25em;

	> li {

		counter-increment: count;

		&::before {

			content: counters(count, ".") " ";
			padding-inline-end: 0.5em;

		}

	}

}
```

Refactoring as follows should resolve the issue:

```
ol ::marker {
	content: counters(list-item, ".") ". ";
}
```

**Comment by deniak** [comment]
Fixed by https://github.com/w3c/w3c-website-templates-bundle/pull/102/
