### ISSUE TITLE
City field suggestions are not working

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#197]
On the [user edit profile page](https://beta.w3.org/users/myprofile/edit/) after setting a country and region, I am not proposed with city name suggestions when I start entering a name in the city field (from either Firefox on my desktop or Chrome Android on my mobile).

**Comment by vivienlacourba** [comment]
Please note that the same issue exists when trying to set the address of a new organization when [changing of affiliation](https://beta.w3.org/users/myprofile/edit/affiliations/).

**Comment by deniak** [comment]
This has been addressed!
