### ISSUE TITLE
Redesign the W3C authentication portal

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#199]
As discussed with @koalie and @jean-gui the W3C Authentication portal (https://auth.w3.org/) should be redesigned.

This new design should be deployed for the launch of the beta website.

**Comment by jean-gui** [comment]
The redesigned auth portal is now in production at https://auth.w3.org/. 
@iadawn will review it for accessibility issues.

**Comment by vivienlacourba** [comment]
@iadawn the only pages to check are the ones starting with https://auth.w3.org/ namely:
- The login form on https://auth.w3.org/login (To see the login form you might first need to log out)
- https://auth.w3.org/ and its "Log out" and "Log out from all devices" actions

**Comment by jean-gui** [comment]
I'm leaving this open because if there is an error in the 2FA form we cannot currently indicate that in the page title. Everything else should be fine.
