### ISSUE TITLE
Links as button cut off

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-website#20]
On https://design-system.w3.org/styles/links.html, second example, the top of the buttons is cut off.

**Comment by NicolaSaunders** [comment]
It's because links with the `.button` class still have the default inline display setting. I will update this to `inline-flex`.

**Comment by NicolaSaunders** [comment]
Fix deployed to the staging site for review https://staging-design-system.w3.org/styles/links.html

**Comment by jean-gui** [comment]
Looks good!
