### ISSUE TITLE
Making feedback clearer

### ISSUE THREAD

**Issue by simonrjones** [w3c/w3c-website#204]
I think it would be useful to make the feedback instructions clearer before the Beta launch.

At present the Beta site feeback links to this repo at: https://github.com/w3c/w3c-website

We could do a few things, which I'm happy to help with:

- Update README.md instructions to make it clearer for users
- Is there any way for users to send feedback not on GitHub or would you prefer it all comes via GitHub issues
- Do we need to review the issue types I originally setup? See https://github.com/w3c/w3c-website/issues/new/choose - at the very least it would be useful to add URLs so its clear what issue types refer to. Or this could be added to the README.md
- Do we want a specific feedback tag for Beta website feedback to make it easier to manage these from the public?
- Update the [working in the open site feedback page](https://w3c.studio24.net/feedback/) to have the same instructions

**Comment by vivienlacourba** [comment]
Hi @simonrjones ,

> I think it would be useful to make the feedback instructions clearer before the Beta launch.
> 
> At present the Beta site feedback links to this repo at: https://github.com/w3c/w3c-website
> 
> We could do a few things, which I'm happy to help with:
> 
> * Update README.md instructions to make it clearer for users

+1

>  * Is there any way for users to send feedback not on GitHub or would you prefer it all comes via GitHub issues

The later, we woudl prefer for all feedback to happen thru GitHub issues.

> * Do we need to review the issue types I originally setup? See https://github.com/w3c/w3c-website/issues/new/choose - at the very least it would be useful to add URLs so its clear what issue types refer to. Or this could be added to the README.md

Those issues types looks good to me. Feel free to propose improvements if you believe some edits would better guide users..

>  * Do we want a specific feedback tag for Beta website feedback to make it easier to manage these from the public?

I don't think we need such a tag.
 
> * Update the [working in the open site feedback page](https://w3c.studio24.net/feedback/) to have the same instructions

Yes that woudl be useful.

Thx.

**Comment by simonrjones** [comment]
@vivienlacourba Suggested changes: https://github.com/w3c/w3c-website/blob/beta-feedback/README.md

Pull Request: https://github.com/w3c/w3c-website/pull/217
