### ISSUE TITLE
Use details/summary element for collapsible containers

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#205]
The [collapsible containers component](https://design-system.w3.org/components/collapsible-containers.html) seems to reproduce exactly what the [details/summary elements are meant to do](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). Is there any reasons for not going with these native elements?

The issue with these containers is that a button is added by JS on each `<h3 data-heading="collapsibles">` element, which is fine unless they are used inside a form. Clicking on the button will not only toggle the container but also submit the form...

**Comment by NicolaSaunders** [comment]
Hi @deniak 

There are some concerns about using the native details/summary element for collapsible containers, which have been identified thanks to the [research by the GDS Team at GOV.UK](https://design-system.service.gov.uk/components/details/#research-on-this-component)

Further issues, including screen reader support, are discussed in this [article from Adrian Roselli](https://adrianroselli.com/2019/04/details-summary-are-not-insert-control-here.html)

Making the current collapsible containers component work within forms should be straightforward. The JavaScript needs updating to set a further attribute of `type="button"` to each button that is created. This should prevent them from triggering form submission when the component is used within a form.
