### ISSUE TITLE
Groups menu needs context

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#211]
**Describe the issue**
The Groups drop-down needs some guidance for new people, what are these different types of groups?

**Recommended solution**
Rename the “Discover W3C groups” key link to “About W3C groups” and have it go to a page which describes what each type of group is. (If the intended target of this link was something else, like searching the list of groups, add it as a regular navigation link.)

**Comment by koalie** [comment]
The page that describes the different types of groups is the page we had for the key link. So I've renamed the title/label "About W3C groups" instead of "Discover W3C groups".
