### ISSUE TITLE
Capitalization of group names, abbreviations

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#212]
**Describe the issue**
We usually capitalize Working Group and Interest Group and Technical Architecture Group, etc. but they are using sentence case in the menu

**Recommended solution**
Fix capitalization

**Additional context**
I would also recommend including their abbreviations in parentheses. This helps people recognize them.

**Comment by simonrjones** [comment]
+1 to this. The original intent was to use sentence case unless it's a proper noun.

To note the pages Working Groups / Interest Groups / Business Groups / etc are all capitalized on their H1s. Pages where it's not a proper noun are not, e.g. Invited experts.

**Comment by vivienlacourba** [comment]
I capitalized all group names in the menu but also "Invited Experts" as this is how we write that term including in the W3CProcess.

**Comment by vivienlacourba** [comment]
> I would also recommend including their abbreviations in parentheses. This helps people recognize them.

Unfortunately adding some abbreviations in the menu would make entries longer and for example adding " (TAG)" after "Technical Architecture Group" would make it reflow to the next line :/

We could also add those to the headings on the Groups page https://beta.w3.org/groups/ (note that its already there for some groups such as AC, AB ad TAG) but similarly the heading "Community and Business Groups (CG & BG)" would be on 2 lines...

**Comment by koalie** [comment]
This is done, as far as I can tell.
Groups for which our community is familiar with abbreviations now have them added.
