### ISSUE TITLE
Excerpt not displayed in "You may also be interested in" listing

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#215]
At the bottom of https://beta.w3.org/about/
The far-right box "Business Ecosystems" does not display the content of the excerpt.

**Comment by koalie** [comment]
The same bug happens at the bottom of https://beta.w3.org/policies/no-nda/
I've checked and there is an excerpt in the CMS for "events".

The common denominator might be that there's a bug to display excerpts from any  of the "*-listing" entries from https://cms.w3.org/admin/entries/singles

**Comment by jean-gui** [comment]
Fixed.
