### ISSUE TITLE
Add a search page for site-wide search via ddg

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#216]
Currently the magnifying glass icon in the header of [the beta site](https://beta.w3.org/) is a direct link to [a DDG search restricted to w3.org](https://duckduckgo.com/?q=site%3Aw3.org&ia=web), and the user is expected to know that they should click on the input box, keep 'site:w3.org' but add a space then enter their search text. This is likely confusing/unexpected for most users.

It would be good for the magnifying glass icon to link instead to a simple page on our site with a text input box that redirects to ddg after combining the user's input with the site:w3.org operator. This could either be done using javascript or by redirecting through a server-side script. I suggest we do the latter since it would allow us to monitor what people are searching for. I am happy to implement this if it sounds good to @koalie and @vivien but maybe it would be better implemented by @jean-gui in symfony.

Someday later, we could update the search page to use javascript to show a find-as-you-type list of links for the most commonly searched things. (I like [MIT's implementation of this](https://web.mit.edu/), except theirs doesn't work without js)

**Comment by gosko** [comment]
Yes, ideally we would have a custom search function directly on our site.

A few years ago I created [an experimental form](https://www.w3.org/2020/12/search-test/) to search our web site, groups, repos, spec titles and a few other things, hoping to come up with something that would be useful to people very familiar with W3C in addition to the general public. It aims to provide quick access to various parts of our site for queries like 'css wg', 'tag', 'privacy'. Even though the data is now very out of date I still use it regularly from my browser start page to find pages on our site as well as look up things like 'http 429' or 'css break-after' in MDN.

If we were to use something like this we would want to incorporate data from Craft to search the current site, and use realtime data instead of the hardcoded data currently used by my prototype. In the absence of an internal system capable of indexing the entire site we could offer a link to the DDG search as a fallback below a list of links generated by our simple search tool. This is something I'm interested in working on, hopefully later this year.

**Comment by tagawa** [comment]
> It would be good for the magnifying glass icon to link instead to a simple page on our site with a text input box that redirects to ddg after combining the user's input with the site:w3.org operator.

I've probably missed something but what's wrong with having a useable search box in the menu bar, how the current site search works? I.e. you type into the search box in the menu bar and the results are displayed on the external search site.

**Comment by gosko** [comment]
Hi @vivienlacourba @koalie, I think it would be good to prioritize this issue since the current search behavior is confusing and it would be really easy to make it much better.

I noticed we already have [a search page](https://www.w3.org/Help/search) that behaves like I [suggested above](https://github.com/w3c/w3c-website/issues/216#issue-1595968488), currently backed by a PHP script. I think it would be very easy to (1) create a similar page in the CMS with the same functionality but updated style (`/help/search/`?), or (2) create a replacement for both the PHP script and web form in symfony (slightly more work, but still easy)

WDYT? I am happy to do (1) if that would be helpful (with form action pointing to the existing PHP script)

We can improve it further as discussed above, as time permits.

**Comment by koalie** [comment]
+1

**Comment by gosko** [comment]
I created a simple [search page](https://www.w3.org/help/search/) in the CMS; @koalie does this look OK as a replacement for the direct link to ddg? I thought about including some quick links under the search input field but wasn't sure what to include.

**Comment by tagawa** [comment]
I'm not part of the project (just a lurker) but really like this functionality and design.
One small suggestion – reduce the whitespace at the top so it fits above the fold on small screens:

![w3c-search_320px](https://github.com/w3c/w3c-website/assets/94173/710a8a33-fdcb-4d76-a0cf-908b63beaa53)

**Comment by koalie** [comment]
> I created a simple [search page](https://www.w3.org/help/search/) in the CMS; @koalie does this look OK as a replacement for the direct link to ddg? I thought about including some quick links under the search input field but wasn't sure what to include.

It looks perfect! Thanks!

**Comment by gosko** [comment]
Done, and now deployed on the site.
