### ISSUE TITLE
improve Participation and Links sections of Permanent Group pages

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#221]
The Permanent Groups ([AC](https://beta.w3.org/groups/other/ac/), [Board](https://beta.w3.org/groups/other/board/), [TAG](https://beta.w3.org/groups/other/tag/), [AB](https://beta.w3.org/groups/other/ab/)) pages each have an empty Participation section, and most of them have a Links section that links to a member- or group-restricted archive.

It would be good for these pages to be improved a bit given their prominence (for example TAG which is linked from the main nav menu). Maybe Participation could be omitted, and the Links section could be updated to include links to the group's home page and public mailing lists, and add (restricted) when linking to non-public lists. Also it doesn't really make sense to have a public mailto: pointing to w3c-members, and likely not for ab and tag as well (we don't want to encourage the general public to send email there)

**Comment by vivienlacourba** [comment]
Similar to #272

**Comment by gosko** [comment]
Thanks for fixing the Participation section. The issues I noted with the Links section are still present. Should I open a new issue for those?

**Comment by deniak** [comment]
No need to create another issue. I'll re-open this one and will revisit how we deal with links

**Comment by deniak** [comment]
We now link to the contact mailing list archive and there's a tag 'Restricted archive' if it's not public.
