### ISSUE TITLE
Re-coding W3C Invited Experts application URIs

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#222]
_(Add link to current page and new page on beta)_

This is about coding the drop-down menu which let applicant Invited Experts select which group to apply to by enabling the link to the application form to be updated depending on the group selected. 
cf. https://cvs.w3.org/Team/WWW/Consortium/Legal/2015/06-invited-expert.html#rev1.9 (w3t team link)

Current page: https://www.w3.org/Consortium/Legal/2015/06-invited-expert.html
New page: https://beta.w3.org/invited-experts/agreement-2023/

**Comment by vivienlacourba** [comment]
@denis the tricky part is that I don't hink that CMS backend allows to integrate custom JS within a given page.

**Comment by deniak** [comment]
Inline scripts are being stripped so the only options I see is to:
1. update `main.js` to take care of that use case but that seems sub-optimal as that script is being loaded by all the other pages as well
2. add a specific script for that page in craft
3. start allowing `<script>` in the frontend

**Comment by vivienlacourba** [comment]
@koalie discussing with @deniak we decided not to re-add this JavaScript selector as it woudl have been too complex _(Note: that's something we will will be looking at as it might be needed for other use cases)_ and instead we spent some time to review and simplify the workflow.

So now: https://beta.w3.org/invited-experts/agreement-2023/#how-to-apply
points directly to: https://beta.w3.org/invited-experts/#instructions
which says:
> After you receive your W3C login name and password, find the [Working Group](https://beta.w3.org/groups/wg/) or [Interest Group](https://beta.w3.org/groups/ig/) you want to join. Select this group, click the "How to join" link and follow instructions from the "If you do not work for a W3C Member organization" section.

So for users that wants to join the EOWG as an Invited Expert this will lead him them:
https://beta.w3.org/groups/wg/eowg/instructions/
And that page should now be much more digestible thanks to the use of the collapsible component plus the removal of some of the non essential text.

**Comment by koalie** [comment]
Sounds good to me.
I went in both the agreement page and the IE homepage to straighten a bit the language and links (part of some quality assurance, not substantive change).
