### ISSUE TITLE
"email link" at the bottom of the "press releases" listing

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#224]
At the bottom of https://beta.w3.org/press-releases/ the "Get press release by email" mailto link is missing the attribute to include subscribe in the subject line.

I didn't find where to edit the listing page. 
Here's the markup that should be used: 

`<a href="mailto:w3c-news-request@w3.org?subject=subscribe">Get press releases by email</a>`

**Comment by jean-gui** [comment]
Fixed in https://github.com/w3c/w3c-website-templates-bundle/commit/9119f28503b1cb58ab2bdd49e59c9abf584cff0f. This will be deployed later.
