### ISSUE TITLE
wording for "on this page" navigation

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#225]
The string that is attached to the “on this page” navigation reads “_Page contents skip to links_” (cf. https://design-system.w3.org/components/toc.html )

This sentence is a little difficult to parse - skip looks like a verb, with ‘to links’ as a prepositional phrase. 

This was a recommendation from the a11y testing company DAC, they said:
“I located a series of in page links situated within the ‘Page contents section.’ Although these were marked-up correctly and performed as expected NVDA does not presently support the announcing of in page links, presenting them as standard links. This may mean that NVDA users are not aware that focus will move which could be disorientating. Adding a small phrase to the beginning of each in page link text for example ‘Move to’ or ‘Jump to’ would ensure that all screen reader users with all software are aware that focus will move.”
And they recommended:
Solution:
Consider either introducing the links via a descriptive heading describing their purpose or add some additional hidden text to convey the functionality of the link.
Examples:
Using a heading
`<h2>Page contents skip to links</h2>`

If we use a simpler string like "_Page content_" then the a11y testing comment will apply again. 

@simonrjones suggests it may be possible to overcome with DAC's suggestion of visually hidden text which would then make it clearer for users, and can be done in Amplify via .visuallyhidden

**Comment by simonrjones** [comment]
I agree simplifying the language is good. I think you have 2 options:

1) Use Richard's suggested text as the TOC heading: Skip-to links for this page.

```
<h2>Skip-to links for this page</h2>
<ul class="clean-list" role="list">
    <li><a href="#link-to-anchor-1">First heading</a></li>
    <li><a href="#link-to-anchor-2">Second heading</a></li>
    <li><a href="#link-to-anchor-3">Third heading</a></li>
</ul>
```

2) Keep the TOC heading shorter, e.g. Page contents, and add visually hidden text noting each link is a skip link in the link text. 


```
<h2>Page contents</h2>
<ul class="clean-list" role="list">
    <li><a href="#link-to-anchor-1">First heading<span class="visuallyhidden"> in-page skip link</span></a></li>
    <li><a href="#link-to-anchor-2">Second heading<span class="visuallyhidden"> in-page skip link</span></a></li>
    <li><a href="#link-to-anchor-3">Third heading<span class="visuallyhidden"> in-page skip link</span></a></li>
</ul>
```

**Comment by gosko** [comment]
Maybe something like this would work?

`<h2>Page contents<span class="visuallyhidden"> skip to links</span></h2>`

I find the longer phrases a bit distracting (including Richard's revision)

**Comment by shawna-slh** [comment]
WAI sub-site has had simply "Page Contents" introducing the list for ages &mdash; on several pages since the 2005 redesign, and on almost all pages since 2018 redesign. [example](https://www.w3.org/WAI/fundamentals/accessibility-intro/) We have not found problems in usability testing (albeit minimal), nor from user feedback.

@daniel-montalvo @iadawn have you additional input?

**Comment by daniel-montalvo** [comment]
+1 to simply "Page contents" label.

**Comment by NicolaSaunders** [comment]
I'm happy to go with the shorter label, particularly given that it has worked fine on WAI sub-site.

**Comment by agreiner** [comment]
I'm happy with @iadawn's proposition.

**Comment by shawna-slh** [comment]
+1 for "Page contents"

fyi (particularly for @iadawn ), we did usability testing last week on another prototype and it was clear that folks needed the "Page contents" label. Some participants' initial reaction was that links go elsewhere, rather than in-page.
