### ISSUE TITLE
Poor checkmark position in Segmented Options

### ISSUE THREAD

**Issue by iadawn** [w3c/w3c-website#229]
[Segmented options](https://design-system.w3.org/styles/forms.html#segmented-options)

This design pattern seems to be an alternative to radio or checkbox group. However, it positions the checkmark to the right of the label. This design approach is explicitly called out twice in the Design System as a poor approach as it can make it difficult for some users to find the checkmark, for example, screen magnifier users.

**Recommended solution**

Don't use this pattern.

Or... change the pattern so the checkmark is on the left

**Additional context**

<img width="676" alt="screen shot of the segmented options in the design system" src="https://user-images.githubusercontent.com/2444840/221600357-dad38762-0c07-4e86-b3b4-68c2c80c3975.png">

**Comment by NicolaSaunders** [comment]
Hi @iadawn - you are completely right, and thank you for spotting this.

@vivienlacourba Do you have a preference for removing this pattern from the design system (I don't know whether it's being used anywhere) or updating the Sass to address the issue? If the latter, I am happy to advise on the necessary Sass amends.

**Comment by vivienlacourba** [comment]
> @vivienlacourba Do you have a preference for removing this pattern from the design system (I don't know whether it's being used anywhere) or updating the Sass to address the issue? If the latter, I am happy to advise on the necessary Sass amends.

Hi @iadawn @NicolaSaunders I woudl say the latter because we are already using this design pattern on the 2nd step of the [W3C Account request form](https://beta.w3.org/account/request/). See screenshot below:

![image](https://user-images.githubusercontent.com/2012282/225988563-6faee664-7e34-4def-81a3-bc5e818eb075.png)

**Comment by NicolaSaunders** [comment]
Thanks @vivienlacourba - here are the changes that need to be made to `https://github.com/w3c/w3c-website-templates-bundle/blob/main/assets-src/styles/sass/30-base/_forms.scss`:

- Line 588: change `right: rem(10);` to `left: rem(10);`
- Line 601: change `right: rem(16);` to `left: rem(16);`
- Line 631: change `padding-right: rem(44);` to `padding-left: rem(44);`
- Line 682: change `left: rem(10);` to `right: rem(10);`
- Line 683: change `right: auto;` to `left: auto`;
- Line 688: change `left: rem(16);` to `right: rem(16);`
- Line 689: change `right: auto;` to `left: auto;`
- Line 703: change `padding-left: rem(44);` to `padding-right: rem(44);`

**Comment by vivienlacourba** [comment]
@NicolaSaunders looks like I had forgotten about that issue, could you create an issue and assign it to @deniak for review? Thx.

**Comment by NicolaSaunders** [comment]
I have added a fix for this issue in the branch [hotfix/segmented-options-check](https://github.com/w3c/w3c-website-templates-bundle/tree/hotfix/segmented-options-check).

**Comment by deniak** [comment]
Closing after merging https://github.com/w3c/w3c-website-templates-bundle/pull/107
