### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by bramus** [w3c/w3c-website#23]
Running [the installation instructions](https://design-system.w3.org/getting-started.html) for a standalone project will give you this:

```
$ composer require w3c/website-templates-bundle
                                                                                                                    
  [InvalidArgumentException]                                                                                        
  Could not find a version of package w3c/website-templates-bundle matching your minimum-stability (stable). Requi  
  re it with an explicit version constraint allowing its desired stability.                                         
                                                                                                                    

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

Thankfully I know how to wield `composer`, so I ran this …

```
$ composer require w3c/website-templates-bundle:*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package w3c/website-templates-bundle * is satisfiable by w3c/website-templates-bundle[dev-design-system-docs, dev-main] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
```

… and derived the version to use (`dev-main`) from that.

```
$ composer require w3c/website-templates-bundle:dev-main 
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 25 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-ctype (v1.23.0): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.23.1): Downloading (100%) 
 …
Writing lock file
Generating autoload files
21 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

The installation instructions could use an update regarding this, as I suspect lots of users not familiar with PHP will be stuck on it.

Or perhaps — and even better — a first version _(`0.1.0` or already ` 1.0.0`?)_ could be tagged?

**Comment by bramus** [comment]
_(Sidenote: I'm wondering if this is even the correct repo. The page https://design-system.w3.org/getting-started.html was linking to here, but it seems wrong …)_

**Comment by simonrjones** [comment]
Thanks for the feedback @bramus - the design system work isn't actually 100% finished, so how to actually load it on external sites and make use of it is something we've not really completely solved. The current setup is due to the requirement to use the design system within a Symfony bundle. We're talking to W3C about how to best use it on other sites - so this may need to change / be improved.

But yes, we certainly will create a tagged version once we've finished the current work and UAT rounds. We may update the design system docs just to make this a little clearer.

**Comment by simonrjones** [comment]
To help with this, I've updated the [getting started](https://design-system.w3.org/getting-started.html) docs.

**Comment by bramus** [comment]
Much better now indeed. Closing this issue. Thanks!
