### ISSUE TITLE
Consider adding an accessibility statement

### ISSUE THREAD

**Issue by luce-carevic** [w3c/w3c-website#230]
**Describe the issue**
There is no sign of an accessibility statement on the beta website.

**URL**
https://beta.w3.org/

**Recommended solution**
Since one of the goal of the redesign is better accessibility and since accessibility in general is part of core principles of th W3C, it would be great that the W3C website would lead by example and be transparent about the conformance status of the website.

**Additional context**
Take example on the WAI website: https://www.w3.org/WAI/about/accessibility-statement/

**Comment by koalie** [comment]
Yes thank you, we're considering it for the future.

The redesign presented in the beta affects only a subset of the W3C website at the moment, but in future phases, we'll expand the redesign to the rest of the site.
You can find more information about [the goals & scope](https://www.w3.org/Press/slides/202002-website-redesign/#rfp).
