### ISSUE TITLE
`dev` icon on Developer page is a brand logo

### ISSUE THREAD

**Issue by danburzo** [w3c/w3c-website#233]
**Describe the issue**

On the [Developers](https://beta.w3.org/developers/) page, the `dev` icon is the logo of [dev.to](https://dev.to/). The icon may be present on other pages as well, such as [this](https://github.com/w3c/w3c-website/issues/233#issue-1601874294).

**Comment by koalie** [comment]
> The icon may be present on other pages as well, such as [this](https://github.com/w3c/w3c-website/issues/233#issue-1601874294).

the link for "this" is a self-reference to this issue. If you found the icon present elsewhere, please kindly follow-up.

**Comment by danburzo** [comment]
Oops, that was meant to be https://beta.w3.org/developers/tools/

**Comment by koalie** [comment]
Thanks! and thanks for letting us know!
