### ISSUE TITLE
Beta: hamburger menu does not work after resizing browser window

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/w3c-website#234]
**Describe the issue**
The medium/small screen navigation hamburger menu on https://beta.w3.org/ does not work when the page is initially loaded at large/desktop size, and the browser window is then resized. Clicks on the "Menu" button have no effect. Resizing the browser window up again (so that it is replaced with the large-screen navigation), and then back down, fixes this issue. Issue resurfaces the next time the window is sized up and then down again...in effect, it works only every second time the browser window is resized.

**To reproduce**
Load the website on large screen, resize browser window down until hamburger menu appears, try to activate it. Resize the window back up to large size, then down again, and try to activate the menu again. Rinse and repeat.

**Expected behavior**
Menu button always works

**Screenshots**

Video showing the behaviour.

https://user-images.githubusercontent.com/895831/221678290-b084c9d6-1722-4683-ba74-ad9d1b4a2ed0.mp4

**Comment by NicolaSaunders** [comment]
I have refactored the navigation to address this issue - please refer to the branch [hotfix/refactor-global-nav](https://github.com/w3c/w3c-website-templates-bundle/tree/hotfix/refactor-global-nav).

**Comment by patrickhlauke** [comment]
I assume this fix won't make it (yet) to the deployment today?

**Comment by patrickhlauke** [comment]
related, but mostly a suggestion, not a bug: https://github.com/w3c/w3c-website/issues/235

**Comment by NicolaSaunders** [comment]
I'm happy to upvote this suggestion

**Comment by deniak** [comment]
Fixed by https://github.com/w3c/w3c-website-templates-bundle/pull/103
