### ISSUE TITLE
Beta: "Search" in hamburger menu should ideally show text, not just the icon

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/w3c-website#235]
**Describe the issue**
For the large-screen navigation, it makes sense that the search option is just showing the magnifying glass. But on medium/small screens, when the navigation is in the hamburger menu, there's sufficient space for it to also show text. In fact, it's confusing that there isn't text, as it almost looks like it's an inline search input, not just a link to the search engine.

**To reproduce**
In medium/large screen, open the hamburger menu

**Expected behavior**
Add visible text to the menu option for search

**Screenshots**
![screenshot of the medium/small screen hamburger menu, with the search option only shown as a magnifying glass icon in an otherwise empty row](https://user-images.githubusercontent.com/895831/221679387-6caa764a-5c3e-464a-9ed2-bc12187a14d4.png)

**Additional context**

Mockup of how it could look with text (can keep the icon for clarity/consistency)

![screenshot of the medium/small screen hamburger menu, with the search option now showing the icon and visible "Search" text](https://user-images.githubusercontent.com/895831/221680670-71b19aa2-6119-4bef-8f73-9b9db4fb1c80.png)

**Comment by NicolaSaunders** [comment]
Proposed fix at https://github.com/w3c/w3c-website-templates-bundle/pull/112
