### ISSUE TITLE
Inconsistent punctuation of headings; Capitalize the word "Web".

### ISSUE THREAD

**Issue by rachelyager-nyc** [w3c/w3c-website#238]
**Describe the issue**
Capitalize the word "Web."

**URL**
https://beta.w3.org/

**Recommended solution**
You may consider consistent punctuation of headings.

**Additional context**
See the inconsistent punctuation is obvious on Website. 

<img width="1212" alt="Screenshot 2023-02-27 at 4 10 30 PM" src="https://user-images.githubusercontent.com/61160050/221688140-34cf334b-68dd-4d45-8009-4cc49bf3f8a4.png">

**Comment by koalie** [comment]
We try to use "Web" as proper noun for the invention and concept, and "web" as common name where it doesn't work as well. 
But usage varies even among the W3C Team (despite sharing the above guidance a few years ago.)
