### ISSUE TITLE
Entire teaser content is inside `figcaption`

### ISSUE THREAD

**Issue by zichy** [w3c/w3c-website#239]
**Describe the issue**

On the front page, the large teaser elements have their entire content inside `figcaption`. However, the content does not describe the image.

**To reproduce**

1. Go to https://beta.w3.org.
2. Scroll to the large teaser elements ("Web standards", "Get involved").
3. Check the source code via developer tools.
4. See how the teasers consist of only one `figure` element each and therefore have their entire content inside `figcaption`.

**Expected behavior**

The content should not be inside of `figcaption`. It should be considered whether using `figure` is necessary at all, since there is no visible image caption. I would recommend using `article` as a wrapper for those teaser elements.

**Screenshot**

<img width="1335" alt="screenshot" src="https://user-images.githubusercontent.com/173749/221694534-84a31e05-2d53-42b4-b0cc-19b30ee35467.png">

**Comment by vivienlacourba** [comment]
Similar to #274

**Comment by NicolaSaunders** [comment]
Thank you @zichy - please see #274 for a proposed solution.
