### ISSUE TITLE
Concerns about representation and inclusion in website graphics

### ISSUE THREAD

**Issue by finnatsea** [w3c/w3c-website#240]
**Describe the issue**
It appears that non-handicapped Asian and white males are excluded from the current set of graphics on the website, which may lead to a sense of under-representation or marginalization.

**URL**
https://beta.w3.org/
https://beta.w3.org/about/

**Recommended solution**
It is important to create a website that represents a diverse range of voices and experiences, while also acknowledging the validity of individual perspectives. Therefore, I recommend that the website creators consider ways to incorporate a broader range of representation in their graphics and visual content, without excluding or diminishing any particular group. This could include showcasing a more representative range of individuals, using less idealized imagery, and avoiding stereotypes or assumptions about any particular group.

**Additional context**
The issue of representation is an important one, and I expect some thought has gone into the creation of these graphics. I wanted to bring these issues of representation to the attention of the designer to ensure no group is excluded or marginalized.

**Comment by wbison** [comment]
Maybe you could present a list of groups to be represented in the new image? Let me just start with what comes to my mind:
- Native Americans
- Sikhs
- Dutch
- Gays
- Transgenders
- Heterosexuals

Lets make this a community effort!

**Comment by koalie** [comment]
We aim to evoke the Web for all in the limited choice of illustrations we use on the site. It is important to be representative of the diverse range of voices and experiences. 
We do not have a designer but if the community, as @wbison suggests, is willing to propose variations using the [humaaans library](https://humaaans.com/), we'll gladly consider contributions!
