### ISSUE TITLE
Non Inclusive

### ISSUE THREAD

**Issue by wbison** [w3c/w3c-website#244]
**You Are So Non Inclusive**
Your beta website containts an image with three persons: a man of color (possibly african american), a person in a wheelchair (maybe handicapped) and a person with a scarf (presumably islamic).

Someone has made a heartwarming attempt to show how inclusive he/she/they/it is.

But how about native americans? Jews? Gays?
Are they not welcome in the World Wide Web?

**Comment by ntounsi** [comment]
I don't think of non-inclusiveness here. IMHO the image as it is fair and sufficient to evoke the **_Web for all_**.
"Keep it simple" :-)

**Comment by koalie** [comment]
I concur with @ntounsi and am sorry that @wbison and possibly others see us being non-inclusive.
