### ISSUE TITLE
Missing status text

### ISSUE THREAD

**Issue by iadawn** [w3c/w3c-website#249]
**Describe the issue**

Status message heading seems to be undefined:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/2444840/222103680-ec57ff3a-f5d4-4d2f-91a1-13720ff49e0c.png">

**To reproduce**

* Visit profile
* Select 'Edit emails'
* Add an email
* 'Undefined' appears in message block

**Expected behavior**

Message block should have some sort of header, 'Succes' or whatever.

**Comment by deniak** [comment]
This is now fixed.
