### ISSUE TITLE
Beta feedback: Change "Show reports" button to "Show results"

### ISSUE THREAD

**Issue by tagawa** [w3c/w3c-website#252]
**Describe the issue**
The search button for Groups search says "Show results". The search button for Standards says "Show reports". Perhaps it's a typo but if not, I suggest changing it to "Show results" for consistency and to avoid confusion of terminology.

**Comment by deniak** [comment]
@tagawa, the button has been updated to ensure consistency.
Thanks for the report.

**Comment by tagawa** [comment]
Bonjour @deniak. That was quick. Merci!
