### ISSUE TITLE
Beta feedback: Show illustrative icons next to menu items

### ISSUE THREAD

**Issue by tagawa** [w3c/w3c-website#253]
**Describe the issue**
There's a lot of text (understandably for a standards organisation) which could be overwhelming for non-native English speakers in particular.

**Suggestion**
It might help to have little illustrative icons alongside menu items, if that can be done in an accessible way. For example an "i" in a circle next to the "About" link, a group of people next to the "Groups" link, etc.

**Comment by koalie** [comment]
This would mix odd styles in the current design. I'm not sure it's worth taking the risk to visually clash because people would have to parse icons in addition to text, thus adding load and possibly confusion.

**Comment by tagawa** [comment]
Fair enough. I got #254 accepted so I’m still happy. 🙂
