### ISSUE TITLE
visibility / link to Chapters program

### ISSUE THREAD

**Issue by JAlanBird** [w3c/w3c-website#257]
I was trying to see where the link to the W3C Chapters Program is within the beta site.  There should be a pointer at a relatively high level that points to https://chapters.w3.org/.  I would propose it's in the list that's under the About header near the Evangelists link.  I would also propose that we replace the Evangelist link on the Regional W3C contacts (on Contact list) with the same Chapters link.

**Comment by koalie** [comment]
> I would also propose that we replace the Evangelist link on the Regional W3C contacts (on Contact list) with the same Chapters link.

Done! See https://beta.w3.org/contact/#region

**Comment by koalie** [comment]
> I was trying to see where the link to the W3C Chapters Program is within the beta site. There should be a pointer at a relatively high level that points to https://chapters.w3.org/.

Chapters are linked in 
* our About page, in the "International Participation" section.
https://beta.w3.org/about/
* our "Logos and icons" page
https://beta.w3.org/policies/logos/

Chapters are mentioned –but not linked– in the W3C Evangelists page.
https://beta.w3.org/evangelists/program/

Chapters are **now** link in our "Contact" page.
https://beta.w3.org/contact/#region

**Comment by koalie** [comment]
> There should be a pointer at a relatively high level that points to https://chapters.w3.org/. I would propose it's in the list that's under the About header near the Evangelists link.

@JAlanBird please raise a different issue for "visibility" o f W3C Chapters, please.

Rationale:
The current production site and the Information Architecture work done to redesign the site do not provide as much / any visibility to W3C Chapters. 
We have not planned for them to have more visibility so we need to plan that.
That involves creating content which is best done as its own issue .
