### ISSUE TITLE
Ecosystem RSS feed links are 404

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#259]
On each ecosystem page the link at the bottom of the page to the RSS feed for that ecosystem is broken:

e.g. on https://beta.w3.org/ecosystems/e-commerce/

> **Related RSS feed**
> 
> [Subscribe to our E-commerce feed](https://beta.w3.org/feeds/ecosystem/e-commerce/)

**Comment by jean-gui** [comment]
Fixed.
