### ISSUE TITLE
/community links on beta.w3.org are not served properly

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#260]
I noticed that community site links on the beta site are not served correctly as links such as https://beta.w3.org/community/about/#cg
or https://beta.w3.org/community/about/process/cla/ both redirects to https://www.w3.org/community/ while they should serve the requested page at the requested URI without any visible redirect.

**Comment by deniak** [comment]
wordpress does that redirect as the CG instance is configured with www.w3.org.
We could duplicate the sites with the hostname beta.w3.org, but I'm not sure it's a great idea and I'm not even mentioning all the other CG sites...

If there's a specific list of pages such as the ones listed above, maybe it could be dealt with the wordpress .htaccess file.

@jean-gui WDYT?

**Comment by gosko** [comment]
Hopefully fixed, by rewriting the Host header to www.w3.org in the community-groups backend in haproxy. (this was also reported to me by Dom)

**Comment by gosko** [comment]
I did the same for the cg-cache backend because this same issue was impacting URIs like https://beta.w3.org/community/groups/ and https://beta.w3.org/community/reports/

**Comment by deniak** [comment]
Nice fix @gosko !
