### ISSUE TITLE
1st level Breadcrumb page has no main menu item

### ISSUE THREAD

**Issue by prabhu9484** [w3c/w3c-website#262]
**Describe the issue**
A clear and concise description of what the issue is.
1st level Breadcrumb page has no main menu item for eg there is no main menu navigation for pages like:
https://beta.w3.org/standards/ 
https://beta.w3.org/groups/ 

**To reproduce**
Steps to reproduce the behavior, including URLs. It's useful to include your web browser and version number to help 
review any potential browser issues.

For example,
Go to main menu navigation Standards
Click the 1st item About W3C Web Standards
In the breadcrumb, click 1st level breadcrumb ie 2nd item **Web Standards** 

**Expected behavior**
Either **Web Standards** should be in the main menu navigation or the Breadcrumb should not have the **Web Standards** item

**Screenshots**

**Additional context**

**Comment by koalie** [comment]
"Web Standards" is actually the first item. On large screen in the navigation it is displayed in the column at the left, at the bottom:

<img width="758" alt="Screenshot 2023-03-02 at 11 03 07 " src="https://user-images.githubusercontent.com/3716853/222397079-105de7d7-ec3f-4fdf-9b0e-e4e45f221034.png">

**Comment by prabhu9484** [comment]
Thanks - missed that somehow

**Comment by koalie** [comment]
If you did, chances are others might too. I wonder how else to position it in order to make it more visible but I have no idea. Coralie(Sent from my phone)On 3 Mar 2023, at 11:55, Prabhu Shiv Singh ***@***.***> wrote:﻿
Thanks - missed that somehow
