### ISSUE TITLE
Update custom description for "Content from another source" for the component "You May Also Like Related Entries"

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#265]
**Describe the issue**
The description for "Type of content", under "Content from another source" for the component "You May Also Like Related Entries" includes "Technical report" which isn't a terminology we want to use in the redesign because it is meaningless to most people.

> Type of content
> Is it a 'News', 'Blog', 'In the media', 'Technical report'?

**Recommended solution**
I suggest we replace it by 'Specification'.

**Screenshots**

<img width="704" alt="Screenshot 2023-03-02 at 10 52 48 " src="https://user-images.githubusercontent.com/3716853/222394004-700bb2f9-9d4e-4b28-870d-a1ec3f52b142.png">

**Comment by vivienlacourba** [comment]
Side note, `'In the media'` was deprecated so it should be removed from that list.

So that field hint message shoudl be:
` Is it a 'News', 'Blog'', 'Specification?`

**Comment by koalie** [comment]
You're right. Using the types we're using, the hint message should be:

> 'News', 'Blog'', 'Page, "Directory list", 'Specification'
