### ISSUE TITLE
Menu items are semantic buttons instead of links

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/w3c-website#268]
Menu items are semantic buttons instead of links

* https://beta.w3.org/
* expand menu
* tab through the menu items

This breaks user expectations that the navigation menu items are links.

**Comment by vivienlacourba** [comment]
Hi @daniel-montalvo

In the main navigation menu the top items are actually buttons that when clicked will open a sub menu that will contain the sub menu links.
So for example selecting the first "Standards" top menu item, will open a sub menu with the heading "Standards", some intro text and intro page link and then the list of links to its various sub menu items.

Could you clarify what are the issues you are facing with that menu?

cc: @iadawn

**Comment by daniel-montalvo** [comment]
I find it strange that top level menu items are semantic buttons. A use case would be for a screen reader user to get to the page, bring up their list of links and try to find the top level menu items. They won’t find them because they are buttons, and they will have to tab around until they come across the menu. 

> On 13 Mar 2023, at 15:12, Vivien Lacourba ***@***.***> wrote:
> 
> 
> Hi @daniel-montalvo
> In the main navigation menu the top items are actually buttons that when clicked will open a sub menu that will contain the sub menu links.
> So for example selecting the first "Standards" top menu item, will open a sub menu with the heading "Standards", some intro text and intro page link and then the list of links to its various sub menu items.
> Could you clarify what are the issues you are facing with that menu?
> cc: @iadawn
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

---
Daniel Montalvo Charameli
Accessibility Education and Training Specialist
W3C/WAI
