### ISSUE TITLE
Adjust group template to non-joinable groups

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-website#272]
https://beta.w3.org/groups/tf/board-personnel/ has a confusing empty "Participation" section; I understand that's where one would find the link to join a group when that's an option, but when it's not, the section should not be there, or should have relevant content (e.g. that the group can't be joined)

**Comment by vivienlacourba** [comment]
Similar to #221

**Comment by deniak** [comment]
This should now be fixed.
