### ISSUE TITLE
Alternative text for icons

### ISSUE THREAD

**Issue by iadawn** [w3c/w3c-website#275]
Location: [Group page](https://beta.w3.org/groups/wg/eowg/)

Links to email group, chairs etc include an icon to indicate it is an email action.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/2444840/223709716-75268308-4f50-4b48-b37a-1ddfe164aba2.png">

The icon is implemented as:

```
<img class="icon" src="https://cdn.w3.org/assets/website-2021/svg/envelope.svg" alt="" aria-hidden="true" width="20" height="20">
```

This means that the purpose of the link isn't communicated to assistive technology users. A better approach in this case would be:

```
<img class="icon" src="https://cdn.w3.org/assets/website-2021/svg/envelope.svg" alt="Email" width="20" height="20">
```

**Comment by vivienlacourba** [comment]
@iadawn, do you recommend that we do similarly for the Links section right below and also on the [Group participants page (requires login)](https://beta.w3.org/groups/wg/eowg/participants/ ) or is the fact that we are displaying an email address along with a `mailto:` link explicit enough?

![image](https://user-images.githubusercontent.com/2012282/224033445-9ebe9d93-ae2e-4e79-a06c-78b289e44ebd.png)

**Comment by deniak** [comment]
The fix has now been deployed.
