### ISSUE TITLE
Various RSS feeds issues

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#278]
I noticed a few issues with RSS feeds:
- They use a default "`Description`" string for their `<description>`
- The `<title>` of the ecosystem feed should probably be "`W3C - E-commerce ecosystem`" instead of "`W3C - E-commerce`"
- Title of the blog feed should be "W3C - Blog"
- As discussed with @jean-gui group feed URIs should start with https://beta.w3.org/feeds/group/... instead of 
https://beta.w3.org/feeds/groups/... (using singular "group").
- Some feeds seem to have an hard-coded `<link>https://www.w3.org/</link>` value
- A group feed as an incorrect "self" link (it points to https://beta.w3.org/feeds/ecosystem/default/)

**Example of those issues:**

https://beta.w3.org/news/feed/
```xml
    <title>W3C - News</title>
    <description>Description</description>
    <link>https://beta.w3.org/news/</link>
```

https://beta.w3.org/blog/feed/
```xml
    <title>W3C</title>
    <description>Description</description>
    <link>https://beta.w3.org/blog/</link>
```

https://beta.w3.org/feeds/ecosystem/e-commerce/
```xml
    <title>W3C - E-commerce</title>
    <description>Description</description>
    <link>https://www.w3.org/</link>
```

https://beta.w3.org/feeds/groups/wg/webrtc/
```xml
    <title>W3C - Web Real-Time Communications Working Group</title>
    <description>Description</description>
    <link>https://www.w3.org/</link>
    <atom:link rel="self" type="application/rss+xml" href="https://beta.w3.org/feeds/ecosystem/default/"/>
```

**Comment by vivienlacourba** [comment]
Another issue, the [Events page](https://beta.w3.org/events/) has an incorrect title for its RSS auto-discoverable link:

```html
<link href="/events/feed/" title="W3C Press Releases" rel="alternate" type="application/rss+xml" />
```

**Comment by gosko** [comment]
It's strange that we are using both `/feeds/` as a URL prefix and `/feed/` as a suffix. Is there a reason for that? (if I had to pick one I would probably choose `/feed/` as a suffix)

**Comment by jean-gui** [comment]
I believe I've fixed all the points mentioned by @vivienlacourba.

@gosko These URLs match what's in the specification, but I agree they are strange.
I could propose the following URLs instead:
- /blog/feed/ (unchanged)
- /news/feed/ (unchanged)
- /press-releases/feed/ (unchanged)
- /categories/{slug}/feed/ that's a new top-level directory, and /categories/{slug} doesn't exist
- /ecosystems/{slug}/feed/
- /groups/{type}/{shortname}/feed/
- /events/feed/ (unchanged)

@vivienlacourba @simonrjones @maries24 what do you think about these proposed URLs?

Category and group feeds will required changes in our proxy frontend.

**Comment by vivienlacourba** [comment]
> @vivienlacourba @simonrjones @maries24 what do you think about these proposed URLs?

:+1:

**Comment by simonrjones** [comment]
Agree, they look good to me 👍 

From memory, and checking the [URL list](https://docs.google.com/spreadsheets/d/1a9pm5HWzcidtLPCeFRz4F0Ir4TT3oOK54FlEEd3IXUE/edit#gid=315005175), we had also suggested /feed as a suffix. 

Using a suffix also suggests the same content is accessed on that URL but it's outputted in a different format.

E.g. HTML = https://beta.w3.org/groups/wg/webrtc/
RSS = https://beta.w3.org/groups/wg/webrtc/feed

**Comment by vivienlacourba** [comment]
> I believe I've fixed all the points mentioned by @vivienlacourba.

[That issue](https://github.com/w3c/w3c-website/issues/278#issuecomment-1466709315) is still there.

Otherwise your other fixes looks good thanks!

**Comment by gosko** [comment]
Thanks @jean-gui.

I was wondering why /categories/{slug}/feed/  needs to exist instead of /blog/category/{slug}/feed/ but @vivienlacourba explained that /categories/{slug}/feed/ will be a feed that combines entries from blog, news, and other sources for the given category. This sounds fine to me but I wonder where these feeds will be exposed if we don't have corresponding pages for them.

(also I was wondering why 'categories' instead of 'category' as used by wordpress, but I see from [this commit](https://github.com/w3c/w3c-website-frontend/pull/85/commits/f8269c7e039379a1174d9a01098c3025207854be) that 'category' is what's implemented - great)

**Comment by jean-gui** [comment]
> I was wondering why /categories/{slug}/feed/ needs to exist instead of /blog/category/{slug}/feed/ but @vivienlacourba explained that /categories/{slug}/feed/ will be a feed that combines entries from blog, news, and other sources for the given category. This sounds fine to me but I wonder where these feeds will be exposed if we don't have corresponding pages for them.

We expose them in some blog and event pages, for example https://beta.w3.org/blog/category/privacy-and-security/, https://beta.w3.org/blog/2023/privacy-principles-for-the-web/ or https://beta.w3.org/events/talks/2022/epub-3-3-a-w3c-standard-with-a-test-suite/
 
> (also I was wondering why 'categories' instead of 'category' as used by wordpress, but I see from [this commit](https://github.com/w3c/w3c-website-frontend/pull/85/commits/f8269c7e039379a1174d9a01098c3025207854be) that 'category' is what's implemented - great)

I actually originally wanted to use 'categories' but forgot to change it. Not talking about feeds specifically, the rationale is that /categories/ can be seen as an endpoint for a collection of categories, hence the plural form, while /categories/{slug}/ is a specific element of that collection.
Using /categories would also be more consistent. Note that wordpress does a poor job at being consistent, using /category/ and /tags/.
I don't have a strong preference though, and can implement either.

Finally, although we don't have that now, it could be useful to create /categories/{slug}/ listing all entries belonging to a category, regardless of their types. And /categories/ could be a cover page listing all categories (although I don't think such a page would be very useful).

**Comment by jean-gui** [comment]
Changes have been deployed. I'm keeping this issue open for the "category" vs. "categories" question

**Comment by gosko** [comment]
> Using /categories would also be more consistent. Note that wordpress does a poor job at being consistent, using /category/ and /tags/.
> I don't have a strong preference though, and can implement either.

OK, good points, +1 to categories then. Thanks!
