### ISSUE TITLE
Semantics of in-page navigation

### ISSUE THREAD

**Issue by iadawn** [w3c/w3c-website#279]
Location: [Group Publications page](https://beta.w3.org/groups/wg/eowg/publications/)

On the Publications page there is an in-page navigation just below the page main heading.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/2444840/223730431-958fe3a2-c5b7-4128-9632-570bc1819179.png">

The heading text for the links seems superfluous and the semantics of the code are slighty off.

```
<section class="toc">
  <h2>Page contents skip to links</h2>
  <ul class="clean-list" role="list">
    <li><a href="#NOTE">Notes</a></li>
    <li><a href="#WD">Working Drafts</a</li>
  </ul>
</section>
```

A better coding could be:

```
<nav class="toc" aria-labeledby="nav-label">
  <h2 id="nav-label" class="visuallyhidden">Page contents</h2>
  <ul class="clean-list">
    <li><a href="#NOTE">Notes</a></li>
    <li><a href="#WD">Working Drafts</a</li>
  </ul>
</nav>
```

**Comment by iadawn** [comment]
I am easy about the visibility of "Page contents".

I think it adds visual clutter for something where the purpose is contextually fairly obvious. I would include the heading visually hidden as the purpose may not be immediately obvious without the visual context. So naming the navigation area clarifies this.

Having said all that, I do tend to have a strong 'visually obvious' brain and can appreciate that my threshold may be set to high.

**Comment by jean-gui** [comment]
Done, markup now looks like this:
```html
<nav class="toc" aria-labelledby="toc-label">
    <h2 id="toc-label">Page contents</h2>
    <ul class="clean-list">
        <li><a href="#NOTE">Notes</a></li>
        <li><a href="#WD">Working Drafts</a></li>
    </ul>
</nav>
```
