### ISSUE TITLE
`x-ua-compatible` is unnecessary

### ISSUE THREAD

**Issue by myakura** [w3c/w3c-website#28]
I see a meta tag in the base template:

https://github.com/w3c/w3c-website-templates-bundle/blob/756bcf833fbb6c68dc4f6dcac2b085168ea9275e/templates/base.html.twig#L11

and I don't think it's necessary. The `x-ua-compatible` meta tag was introduced in IE8 for sites that need to render them in a particular version (document mode) of older IE. [That document mode concept was deprecated in IE11](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg182625(v=vs.85)?redirectedfrom=MSDN#document-mode-changes). And in IE11, [the default document mode is (of course) IE11](https://docs.microsoft.com/en-us/archive/blogs/ie/living-on-the-edge-our-next-step-in-helping-the-web-just-work), so setting `ie=edge` is not really meaningful.

If the new site still needs to render in IE<11, it might be needed. But... with IE being phased out soon, do you really need to do so?

**Comment by vivienlacourba** [comment]
Thanks for your report.
This was addressed in https://github.com/w3c/w3c-website-templates-bundle/commit/23f3a585c9335a193116d73b67d4df6a52b2441f.
