### ISSUE TITLE
Enumeration of principles doesn't match mission

### ISSUE THREAD

**Issue by agreiner** [w3c/w3c-website#281]
**Describe the issue**
The intro on the home page of the beta site says, "The World Wide Web Consortium (W3C) develops standards and guidelines to help everyone build a web based on the principles of accessibility, internationalization, privacy and security." These four considerations are extremely important, but they are not the only principles on which we base standards development work. More fundamental are concepts like one web for all, web on everything, and open standards, as described in our mission [https://www.w3.org/Consortium/mission].

**URL**
[The URL where this problem occurs.](https://beta.w3.org/)

**Recommended solution**
Reword the statement to highlight the principles in our mission.

**Additional context**

**Comment by koalie** [comment]
I don't see the need that both have to match.
