### ISSUE TITLE
Mismatched links for "In this Section"

### ISSUE THREAD

**Issue by agreiner** [w3c/w3c-website#282]
**Describe the issue**
The "In this section" links area doesn't quite match the section content
The list appears for several but not all pages in the About section, and it is not consistently present.
**URL**
[The URL where this problem occurs.](https://beta.w3.org/about/press-media/)
https://beta.w3.org/about/positive-work-environment/
https://beta.w3.org/about/leadership/
https://beta.w3.org/about/history/ (the history page needs a link from somewhere, though)

**Recommended solution**
Remove the extra menu or show it on all pages and match its content to the actual content of the section.

**Additional context**

**Comment by koalie** [comment]
The navigation menu includes pages that are relevant for a given menu category but that may live at different top-level directories.
Perhaps one way to reduce confusion would be to rename "In this section" into "Related"
