### ISSUE TITLE
Only serve content from beta.w3.org

### ISSUE THREAD

**Issue by acme** [w3c/w3c-website#289]
**Describe the issue**
[beta.w3.org](https://beta.w3.org/) currently loads most of its resources from cdn.w3.org. Browsers have to open another HTTP connection and this means that the page takes longer to load. Instead, all content should be served from beta.w3.org.

Notice that request 2 in the waterfall below needs to make another DNS request, then negotiate TLS before it can request the critical CSS and JavaScript.

**To reproduce**
Visit https://beta.w3.org/

**Expected behavior**
Content loads quickly without having to open other HTTP connections.

**Screenshots**
https://www.webpagetest.org/result/230310_AiDc7Y_8R8/3/details/
![image](https://user-images.githubusercontent.com/19988/224330867-5229739a-8dcf-4fc6-8414-d287ba74b55e.png)

**Additional context**

**Comment by acme** [comment]
Thanks, I can confirm that cdn.w3.org is no longer being used. However it looks like some images are now being loaded from www.w3.org. Notice that request 12 in the waterfall below needs to make another DNS request, then negotiate TLS before it can request the images.
![image](https://github.com/w3c/w3c-website/assets/19988/96d4877d-dd9d-453f-bb0c-5f347666d484)

https://www.webpagetest.org/result/230512_AiDc8D_5XD/3/details/

**Comment by jean-gui** [comment]
Thanks @acme, I've fixed a few more. The remaining ones can't be fixed, but this won't be an issue when we're out of beta, as the whole site will then be served from www.w3.org.

**Comment by gosko** [comment]
Fully resolved now that we're out of beta; down from 3.3 seconds to 2.2 🎉

<img width="1026" alt="screenshot of request waterfall from webpagetest" src="https://github.com/w3c/w3c-website/assets/7144396/9922674d-ec12-4378-ab07-7e91689b6409">

Thanks @acme for the report and @jean-gui and @deniak for the fixes.
