### ISSUE TITLE
beta button styling is hard to read

### ISSUE THREAD

**Issue by deborahgu** [w3c/w3c-website#290]
**Describe the issue**

The font size for buttons on the new beta site is hard to read.

Tested in Firefox and Chromium browsers, on Windows 10 Pro.

The default rendering of the button text, on my browser, is in Noto Sans Bold, white on blue, with 0.875 rem.

In the image below, I've changed the left hand button to display at 1 rem, and left the right hand button at 0.875. Notice how some of the rounded corners of Noto Sans Bold get weirdly choppy at the smaller size. At least on my computer, increasing browser zoom doesn't fix the shape-skewing of .875 rem, it just makes the text bigger.

![Two buttons side by side, the left with readable text, and the right with choppier](https://user-images.githubusercontent.com/260800/224376080-eff2fb90-7875-4958-80b3-aa75595bb329.png)

**URL**

https://beta.w3.org/evangelists/

**Recommended solution**

Change the button text to render at 1 rem. It looks perfectly nice and is easier to read.

**Additional context**

I am fully sighted, just aging and perforce have the myriad combined vision difficulties of being middle aged.

**Comment by vivienlacourba** [comment]
This issue looks similar to #29 where letters such as 'g' or 't' looked similarly strange likely because of not using a 1 rem size. 

@NicolaSaunders any suggestion?

**Comment by NicolaSaunders** [comment]
@vivienlacourba I think you are right.

@deborahgu Please see #29 for a proposed solution.

**Comment by NicolaSaunders** [comment]
I have regenerated the font files in the branch [hotfix/update-webfont](https://github.com/w3c/w3c-website-templates-bundle/tree/hotfix/update-webfont).

**Comment by NicolaSaunders** [comment]
I am now closing this issue, as the [related issue has been reported as fixed](https://github.com/w3c/w3c-website/issues/29#issuecomment-1598803679)
