### ISSUE TITLE
Link by-laws from policies page

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-website#291]
The [by-laws](https://www.w3.org/2022/10/w3c-bylaws-20221019.docx) can be found from the [board homepage](https://www.w3.org/groups/other/board/) but should presumably also be linked from the [Policies and legal information](https://beta.w3.org/policies/) page

(the same probably applies to the certificate of incorporation?)

**Comment by koalie** [comment]
@swickr took the action a few months ago to come back to me when there is clarity which other documents in addition to the by-laws ought to be linked from the policies and legal information page. So this is still pending.

**Comment by mnot** [comment]
CC @ianbjacobs. We're having a discussion about what's appropriate to put in 'board' space vs. corporate information -- it's a somewhat important distinction.

**Comment by koalie** [comment]
I will implement this after the holiday break.
