### ISSUE TITLE
no more anchors to people's descriptions on the staff page

### ISSUE THREAD

**Issue by pchampin** [w3c/w3c-website#295]
**Describe the issue**
I would like to be able to point to a specific staff member on https://beta.w3.org/staff/, as I did on the previous website, e.g. 
https://www.w3.org/People#p20n

**To reproduce**
Granted, this was a rather hidden feature -- you needed to inspect the page source or use a [specific browser extension](https://addons.mozilla.org/en-US/firefox/addon/jump-to-anchor/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) to get those links. But that was a useful feature.

**Expected behavior**
I would expect *some* anchor on each individual person's "card" in https://beta.w3.org/staff/. It would be better for backward compatibility of it was that person's login (as is currently the case), but I could live with other anchors, as long as the ability to link to a specific person remains.

**Comment by vivienlacourba** [comment]
+1 to re-add those user ids.

**Comment by simonrjones** [comment]
Interestingly I tried to do exactly this earlier today and agree it would be useful! You could add the HTML in to make this possible now. There is a `slugify` Twig filter available in the frontend code to help generate IDs, if you wish ([docs](https://github.com/strata/frontend/blob/main/docs/templating/twig.md#slugify)).

Perhaps a future enhancement could be to make this more discoverable to users, a bit like you see on other sites (e.g. hover over a heading on this [docs page](https://w3c.studio24.net/docs/technical-systems-audit#how-urls-and-redirects-are-currently-managed) to see the link icon appear)
