### ISSUE TITLE
Post listing page - search - non descriptive input

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#3]
Raised by the Digital Accessibility Centre as part of their accessibility testing: 

Non descriptive input
The search input not descriptive.

WCAG Reference(s):
2.4.6 Headings and Labels (Level AA)
Understanding Headings and Labels |How to Meet Headings and Labels

URL: https://w3c-dev.studio24.dev/posts/index.html 

Although this has been updated and includes a label, this is still a little confusing.  The aria-label is now just ‘search’ but it’s not clear that you are searching by posts – the text that a screen reader will hear when navigating in context states ‘Browse our posts by search, category or archive.’, but it is not clear from the label ’search’ exactly what the user will be searching through.  This could also be the case for sighted users.

 
Current code ref(s):
```
<h1>Posts</h1>
<p class="lead">Browse our posts by search, category or archive.</p>
<div class="l-sidebar search">
<form role="search" onsubmit="return false" novalidate="">
<div class="not-sidebar">
<input type="search" id="search" name="search" aria-label="Search">
</div>
<div class="sidebar">
<button type="submit" class="button" name="search">Show results</button>
</div>
</form>
```

**Solution:**
If the ‘Browse our posts by search, category or archive.’ Is introducing that section then it should really be marked up as a heading. 
The label for the field could then be made more descriptive by using the text ‘Browse/search posts’.

**Comment by NicolaSaunders** [comment]
Addressed by https://github.com/w3c/w3c-website-redesign-html/commit/8676968f96f95ef163b28beb5486544d3edaf339
