### ISSUE TITLE
Copy change on labels for switching between different localised websites

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#30]
In the CMS, you can select which language you are viewing the site in. 

![Screenshot 2021-10-19 at 15 23 18](https://user-images.githubusercontent.com/20167528/137930398-8d4c1ef5-8c48-42d5-b816-19f1ea06f3b6.png)

For the entries under 'W3C localised websites' can the copy be updated for each site in the following way:
"W3C CMS" to "English"
"W3C 日本" to "Japanese 日本"
"W3C 中国" to "Chinese 中国"

This will make it easier for English speakers to know the different between the Japanese and Chinese sites.

**Comment by vivienlacourba** [comment]
As we are entering data in the CMS for pages that have several translations (e.g. Press Releases and old news items) it is becoming very painful to recognize which one is the Chinese version and which one is the Japanese.

Please update those labels with the text from https://github.com/w3c/w3c-website/issues/30#issuecomment-946963809

**Comment by maries24** [comment]
Hi @vivienlacourba I've made the update and deployed to development and staging.
