### ISSUE TITLE
Проблема в открытии выпадающего меню

### ISSUE THREAD

**Issue by Alex-De-Vep** [w3c/w3c-website#300]
**Describe the issue**
A clear and concise description of what the issue is.
- на основной странице выпадающее меню подкатегорий открывается п оклику на всю область. На других страница только по клику на стрелку. Думаю есть какая то проблема.
- карточки последних новостей сделайте ссылками. Появляются ограничения при работе с ними. Например нет возможности открыть их в новой вкладке.

**To reproduce**
Steps to reproduce the behavior, including URLs. It's useful to include your web browser and version number to help 
review any potential browser issues.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vivienlacourba** [comment]
Hi @Alex-De-Vep unfortunately none of the persons working on this project speaks Russian, would you mind updating the title and description of that issue to be in English). Thanks!
