### ISSUE TITLE
Several Semantic HTML5 Elements are not allowed

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#303]
There is no way to add some semantic HTML5 elements like 'section', 'article', 'header' and maybe others via the editor.

We had to import some pages containing such elements, we did a copy/paste in the source view but they were replaced with 'paragraph' and their 'id' was removed.

The first screenshot presents an example of semantic elements entered in the source code of a page.

The second screenshot presents the source of the same page after we switch to the wysiwyg view and then back to the source view.

The elements 'section', 'article' or 'header' of the example have been removed along with their 'id'.

Those elements are a way to improve the usability and the accessibility of a document.

![semantic-elements-1](https://user-images.githubusercontent.com/1674025/226699472-3051b2f6-ee12-46d3-b0d2-20736cc72390.png)

![semantic-elements-2](https://user-images.githubusercontent.com/1674025/226699524-93aa453c-254a-4dac-a8a9-f6d9da6f84cb.png)

**Comment by jean-gui** [comment]
Note that the h1 was also removed in the screenshots above, but I think that's what we want because we only want one h1, the page title

**Comment by simonrjones** [comment]
Just to note we originally put in HTNML filtering in the CMS text editor to ensure only allowed HTML elements. This is a standard security process when setting up a CMS. 

We do appreciate W3C want to add a far wider set of HTML elements so we'll review how this is setup and whether we should remove this filtering entirely / or add further HTML tags to it. 

best wishes,
Simon

**Comment by vivienlacourba** [comment]
Add @jean-gui as co-assignee as we might want to change our previous strategy with the move to the new CKEditor version.

**Comment by JamieC24** [comment]
This issue should now be resolved as a result of the deployment of the Craft 4 upgrade in June.
