### ISSUE TITLE
same-origin error for nav-icons.svg

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#306]
When I load [the staff page from the beta site](https://beta.w3.org/staff/) in either Firefox or Chrome on MacOS, the developer console says the request for [nav-icons.svg](https://cdn.w3.org/assets/website-2021/svg/nav-icons.svg) was blocked due to 'Not same-origin'

Firefox console says:

>  Security Error: Content at https://beta.w3.org/staff/ may not load data from https://cdn.w3.org/assets/website-2021/svg/nav-icons.svg. 

Chrome console says: 

> Unsafe attempt to load URL https://cdn.w3.org/assets/website-2021/svg/nav-icons.svg from frame with URL https://beta.w3.org/staff/. Domains, protocols and ports must match.

**Comment by jean-gui** [comment]
I believe this should be fixed now that we use www.w3.org instead of cdn.w3.org. @gosko can you confirm?
