### ISSUE TITLE
Broken link in group IPR disclosures

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#308]
There is a broken link in each group's IPR disclosures section, for example [the Math WG's](https://beta.w3.org/groups/wg/math/ipr/#disclosures)

```
<p>This section summarizes patent disclosures by participants in W3C&apos;s <a
href="/groups/wg/math//">Math Working Group</a>
```

(note double slash following `/groups/wg/math`)

**Comment by deniak** [comment]
Good catch! It should now be fixed.
