### ISSUE TITLE
Dark theme not available .

### ISSUE THREAD

**Issue by SpongeBob0103** [w3c/w3c-website#309]
This is an important site , I think that there are many people who will stumble across this website . It will make easier for them to operate this site for a longer period of time as Dark-mode enables less damage to eye .

**Comment by rairules** [comment]
Seconding that this would be really helpful. In the meantime, High Contrast mode in my windows operating system can force a pseudo dark-mode that works alright for most of the pages.

**Comment by xictul** [comment]
agreed, light theme websites are the leading cause of blindness amongst developers across the world.

**Comment by h-a-n-n-e-s** [comment]
Yes pleeease!
A site super relevant for coding without a dark mode?  😵‍💫

**Comment by gosko** [comment]
(This is now marked as 'not planned' but that's not accurate, it's just a duplicate)
