### ISSUE TITLE
Internationalization issues to review in UAT phase

### ISSUE THREAD

**Issue by simonrjones** [w3c/w3c-website#31]
@r12a undertook some testing of a test content page with localised text. I'm noting down his findings here so we can review these again in the UAT phase, when hopefully there will be some real translated content to test!

**Remove the “Read this page in” text from the translated page links block**

- Richard suggested removing this. For now we've left it since it was an agreed design element in the template, with the aim to review in UAT with real content

**Move the translated page links block above the H1, below the breadcrumbs**

- For the landing page template we have an issue #44 to move the translated page links to directly below the H1 (there is a gap at present due to the hero image)
- We plan to leave the translated page links below the H1 at present, since we feel this is more clearly part of the page content. We don't want any confusion with the global nav, which already includes translated links to the Japanese and Chinese sites.

**Add locale-specific CSS styles**

- Richard pointed out we may need some locale-specific CSS to help render localised content
- This needs testing with real content and specific guidance added as GitHub issues to be actioned
- Richard's notes copied below:

> You may, however, get some mileage by looking at  the following basics on a language by language basis:
> 
> 1. font-face (and maybe webfonts to support your choice) - you'll want to ensure that you choose a nice, readable font and that there aren't any gaps that will lead to a ransom-note effect as the browser falls back to another font.  My system-font lister may be useful https://r12a.github.io/scripts/fontlist/ (you can test for custom sets of characters - and for that, my character use app may be useful eg. https://r12a.github.io/app-charuse/?language=arb (but not for CJK)
> 
> 2. font-size (rendered glyph size can vary dramatically in non-latin fonts from font to font, for the same language)
> 
> 3. line height – some scripts will need more inter-line spacing than others; probably relevant for Arabic and CJK.

**Look into how inline text is marked up to ensure this works OK**

- Richard had some suggestions on how to markup text which is a different text direction to the global page. We feel this needs testing with real content.
- Richard's notes copied below:

> https://www-dev.w3.org/ar/standards/about-w3c-standards
> 
> The content "W3C, Arnaud Le Hors" is a bit odd, and i'm not entirely sure what the intent was.
> The markup you applied is possibly ok, 
> Note, however, that you could also use <bdi> rather than a span in this case, eg.
> <bdi>W3C, Arnaud Le Hors</bdi>
> It will automatically apply a LTR base direction and isolate the text inside from that outside the element.
> 
> However, if this is conceptually two separate pieces of information listed in the Arabic order, you'd need to mark it up as (constituents shown here in memory order - a regular problem when dealing with bidi examples...):
> ARABIC TEXT: <bdi>W3C</bdi>ARABIC_COMMA <bdi>Arnaud Le Hors</bdi>
> 
> Btw, one other thing to watch out for with bidi markup, fwiw, is to never leaving a space immediately before a closing tag, see https://www.w3.org/International/questions/qa-bidi-space.en   I don't think your edits did that, but i remember seeing it somewhere else (probably in the boilerplate text) yesterday.

**Comment by maries24** [comment]
Hi @vivienlacourba @simonrjones 
We followed the generic recommendations above during development and addressed specific issues #112, #104 , #95 , #100 , #44 related to internationalisation more recently.

**Comment by r12a** [comment]
Fwiw, i edited the quotes above to surface the `<bdi>` elements that had been swallowed up by GH's markdown processor.
