### ISSUE TITLE
Bogus markup/link on the Invited Expert application page 

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#310]
On the page to join as an Invited Expert e.g. https://beta.w3.org/groups/wg/epub/apply-as-invited-expert/?viewas=vivtest the markup for the link to the Invited Expert Agreement is not interpreted correctly.

See screenshot:

![image](https://user-images.githubusercontent.com/2012282/228500134-63394351-d4a0-4825-a18d-f302db7f6e6a.png)

**Comment by deniak** [comment]
Issue fixed!
