### ISSUE TITLE
<ul> on TR cards

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#311]
**Describe the issue**
The design system describes [how a technical report should be listed](https://design-system.w3.org/templates/tr.html#technical-report-item) and provides the associated markup.
While working on https://github.com/w3c/w3c-website/issues/97, we were wondering if the list of tags, editors and translations shouldn't be listed inside a `<ul>`. This seems to be better semantically and for https://github.com/w3c/w3c-website/issues/97 (where we need to re-order the languages), it's easier to reorder a list than parsing a paragraph.

**URL**
https://beta.w3.org/TR/

**Recommended solution**
We would basically end up with the following markup: 
```html
<div class="tr-list">
    <div class="tr-list__item">
        <div class="tr-list__item__header">
            <h3>
                <a href="https://www.w3.org/TR/2014/REC-wai-aria-20140320/">Accessible Rich Internet Applications (WAI-ARIA) 1.0</a>
            </h3>
            <span class="maturity-level maturity-level--highlighted">Standard</span>
        </div>
        <time>20 March 2014</time>
        <p><span class="bold">Tags:</span></p>
        <ul>
            <li>Accessibility</li>
        </ul>
        <p><span class="bold">Editors:</span></p>
        <ul>
            <li>James Craig</li>
            <li>Michael Cooper</li>
        </ul>
        <p>2 translations for Accessible Rich Internet Applications (WAI-ARIA) 1.0:</p>
        <ul>
            <li><span lang="ja">日本語</span></li>
            <li><span lang="hu-HU">Magyar</span></li>
        </ul>
    </div>
</div>
```

Note that the CSS would need to be updated to allow the list to be displayed inline (we could rely on the [cluster layout](https://design-system.w3.org/layouts/cluster.html)) and to separate the items with a comma.

That being said, there may be a good reason to *not* go with the lists, especially in terms of accessibility. 

@NicolaSaunders, @iadawn, do you think the lists are acceptable here?

**Comment by vivienlacourba** [comment]
@NicolaSaunders, @iadawn, ping. We would appreciate your input on the above question. Thanks.

**Comment by iadawn** [comment]
List might be good but not `<ul>`. A `<dl>` might be semantically better. So you would have:

```
<div class="tr-list">
    <div class="tr-list__item">
        <div class="tr-list__item__header">
            <h3>
                <a href="https://www.w3.org/TR/2014/REC-wai-aria-20140320/">Accessible Rich Internet Applications (WAI-ARIA) 1.0</a>
            </h3>
            <span class="maturity-level maturity-level--highlighted">Standard</span>
        </div>
        <time>20 March 2014</time>
        <dl>
          <dt>Tags:</dt>
          <dd>Accessibility</dd>
        
          <dt>Editors:</dt>
          <dd>James Craig</dd>
          <dd>Michael Cooper</dd>

          <dt>2 translations for Accessible Rich Internet Applications (WAI-ARIA) 1.0:</dt>
          <dd><span lang="ja">日本語</span></dd>
          <dd><span lang="hu-HU">Magyar</span></dd>
        </ul>
    </div>
</div>
```

And then style the `<dt>` and `<dd>` elements accordingly.

Although, I am curious about the structure for the translations. It seems to repeat the title and give the number of items and I am not sure why. An alternative structure would be:

```
<dt>Translations:</dt>
<dd><span lang="ja">日本語</span></dd>
<dd><span lang="hu-HU">Magyar</span></dd>
```

**Comment by deniak** [comment]
The original idea of repeating the title is discussed in https://github.com/w3c/w3c-website/issues/17#issuecomment-916205675.
However, the prototype was relying on the translations being a single link to the translations page. We then decided to link directly to each translations so the `<dt>`/`<dd>` might be more acceptable now.

**Comment by NicolaSaunders** [comment]
I like the proposal of using the `<dl>`. If the `<dd>` for each translation becomes a link then the markup would become:

```
<dt>2 translations for Accessible Rich Internet Applications (WAI-ARIA) 1.0:</dt>
<dd><a href="/path/to/translation" hreflang="ja" lang="ja">日本語</a></dd>
<dd><a href="/path/to/translation" hreflang="hu-HU" lang="hu-HU">Magyar</a></dd>
```

I think we should still repeat the item title within the preceding `<dt>` to help users ascertain the context of the links. I was concerned about [SC 2.4.9](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-link-only.html) but by repeating the title here I think we are at least okay for [SC 2.4.4](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html)

**Comment by deniak** [comment]
I'm guessing the idea is to still display the `<dd>` inline and comma-separated to avoid long cards when we have a lot of editors/translations/tags.

**Comment by deniak** [comment]
I gave it a try and started a [PR to allow displaying items inline](https://github.com/w3c/w3c-website-templates-bundle/pull/89). Not sure that's the best way to handle this though.

**Comment by NicolaSaunders** [comment]
Is it possible to give each instance of `<div class="tr-list__item">` a unique `id` attribute and add a skip link to reduce the number of tab stops for people navigating via e.g. keyboard.

Something like:

```
<dt>2 translations for Accessible Rich Internet Applications (WAI-ARIA) 1.0 <a href="#id-of-next-tr">(Skip to next report)</a>:</dt>
<dd><a href="/path/to/translation" hreflang="ja" lang="ja">日本語</a></dd>
<dd><a href="/path/to/translation" hreflang="hu-HU" lang="hu-HU">Magyar</a></dd>
```

**Comment by deniak** [comment]
> Is it possible to give each instance of `<div class="tr-list__item">` a unique `id` attribute and add a skip link to the `<dt>` advising on the number of translation, to reduce the number of tab stops for people navigating via e.g. keyboard?

Yes, we could generate an id for each `<div class="tr-list__item">`. If this is only to help with tabs navigation, we might want to add the class `visuallyhidden` to the `<a>` as the `<dt>` can already be quite long.
@iadawn would this be acceptable in terms of a11y?

**Comment by deniak** [comment]
This was fixed in https://github.com/w3c/w3c-website-templates-bundle/pull/89
