### ISSUE TITLE
Can't add a new event to calendar using keyboard only

### ISSUE THREAD

**Issue by jnurthen** [w3c/w3c-website#315]
**Describe the issue**
On the beta site the Add an event link is after the calendar in the navigation sequence. I have a lot of events in my calendar. While I might eventually be able to add an event it would take me a long time to get to the link
**To reproduce**
Got to calendar page and use the tab key to try to get to the Add an event link
**Expected behavior**
I expect to be able to do this efficiently
**Screenshots**

**Additional context**

**Comment by jean-gui** [comment]
That is indeed very inefficient. Profile pages (https://www.w3.org/users/myprofile/) have the same issue where you have to  go through the whole page before being able to edit your profile or emails.
Menus for these pages should probably be similar to the ones on https://beta.w3.org/groups/tf/aria-editors/ instead, but the template for these pages is very much centered around groups and should probably be made more generic.

**Comment by iadawn** [comment]
+1 to moving the 'In this section' below the main h1 and above the main content in the DOM.

I probably wouldn't replicate the ARIA editors style of making hiding the menu in a show/hide widget when the view port is smaller.

**Comment by NicolaSaunders** [comment]
I have created a branch called [feature/profile-page-template](https://github.com/w3c/w3c-website-templates-bundle/tree/feature/profile-page-template) to tackle this issue.

Related pull request is at https://github.com/w3c/w3c-website-templates-bundle/pull/115

**Comment by aody9992o** [comment]
ในวันที่ จ. 31 ก.ค. 2023 17:43 น. Nicola Saunders ***@***.***>
เขียนว่า:

**Comment by jean-gui** [comment]
The fix has been deployed. @jnurthen @iadawn Is it easier to navigate to the "add an event" link now?

**Comment by iadawn** [comment]
Awesome :)

**Comment by japuiglaucia** [comment]
Can't add a new event to calendar using keyboard only #315
