### ISSUE TITLE
Connecting Github Account Gives Redirect Mismatch Error

### ISSUE THREAD

**Issue by akdombrowski** [w3c/w3c-website#317]
**Describe the issue**
A clear and concise description of what the issue is.
On the new site, under my account, connected accounts, under Available Services, when clicking Github Connect, I get returned to the original site with a redirect mismatch error in the url.

`https://www.w3.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=5e150d15a232c10bf1bc5913ee776c71`

**To reproduce**
Log into an account. 
Go to click on profile image to go to My Account. 
Click on Connected accounts in table of contents on right. 
Click on Connect under Available Services.

**Expected behavior**
I should see something asking if I want to link my Github account.

**Screenshots**
[https://i.imgur.com/XgJLSrF.png](url)

**Additional context**
It's asking me to link my Github account before I can join a group.
Here's the request url when clicking "Connect" as captured by dev tools in the browser:
`https://github.com/login/oauth/authorize?response_type=code&client_id=c0f5bef3d66c40d429e7&state=f9ea1422d010b883972a231913313701&redirect_uri=https://beta.w3.org/users/connect/service/github`

**Comment by kenpa567** [comment]
> **Describe the issue** A clear and concise description of what the issue is. On the new site, under my account, connected accounts, under Available Services, when clicking Github Connect, I get returned to the original site with a redirect mismatch error in the url.
> 
> `https://www.w3.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=5e150d15a232c10bf1bc5913ee776c71`
> 
> **To reproduce** Log into an account. Go to click on profile image to go to My Account. Click on Connected accounts in table of contents on right. Click on Connect under Available Services.
> 
> **Expected behavior** A clear and concise description of what you expected to happen. I should see something asking if I want to link my Github account.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. [https://i.imgur.com/XgJLSrF.png](url)
> 
> **Additional context** Add any other context about the problem here. It's asking me to link my Github account before I can join a group. Here's the request url when clicking "Connect" as captured by dev tools in the browser: `https://github.com/login/oauth/authorize?response_type=code&client_id=c0f5bef3d66c40d429e7&state=f9ea1422d010b883972a231913313701&redirect_uri=https://beta.w3.org/users/connect/service/github`

**Comment by kenpa567** [comment]
![Uploading Screenshot_20230418-140917_Chrome.jpg…]()

**Comment by elf-pavlik** [comment]
I encountered the same problem, I assume that the redirect URLs present in OAuth client registration on Github don't include the `https://beta.w3.org/users/connect/service/github`, probably it only includes one without `beta`.

I think that W3C admin who manages the GitHub integration can find it at https://github.com/settings/developers once selected the application for the W3C Beta it will be listed as *Authorization callback URL*

**Comment by jean-gui** [comment]
Connecting an Github account should work now that we've deployed the new design on www.w3.org. @elf-pavlik is correct that the issue was related to the Authorization callback URL, but unfortunately it GH only allows one such URL per application, and we didn't want to create another one just for beta, as otherwise people would grant oauth permissions to that temporary application rather than the production one.
