### ISSUE TITLE
"W3C CMS" in open graph title

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-website#340]
**Describe the issue**
The (presumably CMS-generated) open graph and twitter title in `<meta>` elements in the head are suffixed with "- W3C CMS" which creates unwelcomed noise in the OpenGraph previews.

**URL**
e.G. https://beta.w3.org/liaisons/

**Recommended solution**
Remove the " - W3C CMS" from the generated title.

**Comment by jean-gui** [comment]
@koalie What do you think about the SEO tab when editing entries? Is it useful to you? Have you ever used it to customize SEO or social snippets? I am contemplating removing the SEO plugin which would solve this issue and simplify the UI.

**Comment by jean-gui** [comment]
I've removed the plugin, and modified opengraph/twitter sections to re-use the main title/excerpt/thumbnails
