### ISSUE TITLE
HTTP 500 on account/resetpassword page with beta design

### ISSUE THREAD

**Issue by halilemreozen** [w3c/w3c-website#344]
**Describe the issue**

Password reset process got HTTP 500 Internal Server Error on  https://beta.w3.org/account/resetpassword 

**To reproduce**

- Go to the login page https://www.w3.org/community/wp-login.php
- Click on [Lost your password?](https://www.w3.org/community/community/wp-login.php?action=lostpassword) link
- Pass the captcha and enter your email address
- Click to Recover password button

- Go to email inbox
- find the w3 password recovery email
- click on the password reset link
- enter a password and click to reset button

https://beta.w3.org/account/resetpassword

**Expected behavior**
Webpage should confirm the password change or should show a clear error statement to the user about insufficient password entry

**Screenshots**
N/A - Generic W3 Beta 500 Internal Server Error page

**Additional context**
The reset password page works with a classic design.

**Comment by jean-gui** [comment]
Fixed. @halilemreozen Thanks for the report.
