### ISSUE TITLE
Upgrade CMS from Craft 3.x to latest 4.x release

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#345]
c.f. https://craftcms.com/docs/4.x/upgrade.html

**Comment by JamieC24** [comment]
cc: @simonrjones @AlanJIsaacson

Successfully upgraded CMS from Craft 3 to Craft 4 locally.

Next steps I think are to test the front-end with the new Craft 4 CMS as an API Endpoint just to make all functionality is still in-tact.

Encountered a few issues when attempting to test the front-end locally which are as follows:

- The Symfony build rejects the SSL Cert of the MAMP VirtualHost, even when mapped to `pem` files generated with `mkcert`

Other things to note are:

- We should look at upgrading the version of deployer used on this project to Deployer 7 (Which is compatible with PHP 8.2 which is required for Craft 4) to make sure we can continue to deploy as needed.

- Update the Front-End (Symfony and Strata) to make it compatible with PHP 8.2

**Comment by jean-gui** [comment]
> * Update the Front-End (Symfony and Strata) to make it compatible with PHP 8.2

Yes, we should also upgrade the front-end to Symfony 6 and PHP 8 at some point

**Comment by simonrjones** [comment]
Just to note these are dependencies we need to resolve before we can deploy the Craft or frontend repos to a PHP 8.2 server:

- Upgrading the version of Deployer used on this project to Deployer 7
- Update the Front-End (Symfony and Strata) to make it compatible with PHP 8.2 (ideally Symfony 6 as noted above)

We plan to look at these next week & will update this ticket then. Please note it's a bank holiday in the UK on Monday. 

The following is an internal task we'll need to complete at Studio 24 to help Jamie test the site locally:

- Ensure local SSL cert works when Craft API is accessed via PHP (not a web browser). This can be tested in the CLI via the curl command.

**Comment by jean-gui** [comment]
Craft 4 has been deployed
