### ISSUE TITLE
Improve text in Participation section of group pages

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#347]
The text for unauthenticated users in the Participation section of [a group page](https://beta.w3.org/groups/wg/ag/) says:

> You need to [log in](https://auth.w3.org/?url=https%3A%2F%2Fbeta.w3.org%2Fgroups%2Fwg%2Fag%2F) to join or leave the group.

This seems a bit harsh/unfriendly. I suggest updating the text to something like:

> To join or leave this group, please [sign in](https://auth.w3.org/?url=https%3A%2F%2Fbeta.w3.org%2Fgroups%2Fwg%2Fag%2F) to your account.

**Comment by deniak** [comment]
The sentence has been updated. Thanks for the suggestion.
