### ISSUE TITLE
Each event type listing page should have their own intro text and title

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#35]
Looking at events pages with @koalie we noted that the introduction/summary appearing at the top of the page was the same for all events types (@jean-gui pointed me to the ["W3C events" single](https://cms-dev.w3.org/admin/entries/eventsListing/751-w3c-events?site=default)).

As we do today we would like to set a different text content for each event types listing, to present to users what those specific events are. Similarly I believe that each specific event listing page should have its own title (i.e. the title of /events/workshops/ should be "Workshops" and not "W3C events").

From the implementation point of view, as done in WordPress for taxonomies description, could those event types intro text be defined directly within the relevant category ("Categories / Event Type") and not as part of a "Single"?

FYI, here are the intro texts we use today.
- /events/
> W3C engages with the community in a number of venues. This page lists upcoming events of various types, both inside and outside W3C. Additional event details may be found on linked pages.

- /events/workshops/
> W3C organizes Workshops to promote early involvement in the development of W3C activities from Members and the public. The goal of a workshop is usually either to convene experts and other interested parties for an exchange of ideas about a technology or policy, or to address the pressing concerns of W3C Members

- /events/ac/
> [Advisory Committee Meetings](https://www.w3.org/Consortium/Process/organization#ACMeetings) are Members-only meetings that focus on strategic issues facing the Consortium and future directions envisioned by the Membership and Staff.

- /events/tpac/
> TPAC ("Technical Plenary / Advisory Committee"), the W3C annual conference, is an important rendez-vous for the Web community. During that week, a number of W3C Working and Interest Groups gather, network, and work to resolve challenging technical or social issues. Since 2001, this well-attended and popular week of meetings has been an important means for W3C to coordinate solutions to technical issues that transcend group borders. Breakout sessions are public, as are most meeting records.
> 
> Watch the [video](https://www.youtube.com/watch?v=7GZu9LP6KRo) to learn more about this meeting, the Web Consortium and our mission.

- /events/talks/
> Many in the W3C community — including staff, chairs, and Member representatives — present W3C work at conferences and other events. Below you will find a list of some of the talks. All material is copyright of the author, except where otherwise noted.

- /events/conferences/
> At times W3C sponsors or endorses external conferences (and in some cases, W3C speakers present talks). Please send email to the W3C Communications Team at w3t-pr@w3.org with questions about conference sponsorship.

**Comment by maries24** [comment]
Hi @jean-gui (CC @vivienlacourba)

I've added a field to event types taxonomy terms so we can add a description to them.

I've tried adding the field to the GraphQL query in the front-end app but I'm not sure how to do that... @jean-gui Could you please take a look?

To summarise what we want to achieve:
When a user views the events listing and filters by an event type (e.g. 'Talks'), the listing title becomes 'Talks' and the lead copy is the description of the event type 'Talks'.
The field 'machine name' in the CMS is 'pageLead'. I have staged content for the description of the 'Talk' event type on dev.

**Comment by JuliaSang** [comment]
@jean-gui @maries24 is this ticket in progress or has it not been started? If in progress, can you clearly assign who is working on it (i.e. is it Jean-Gui or Marie?)

Thanks both!

**Comment by maries24** [comment]
Hi @JuliaSang and @jean-gui 

I've added the field to the CMS. Now it needs pulling into the front-end app which is why I assigned it to @jean-gui.

**Comment by jean-gui** [comment]
Apologies, I had missed that one. Done, see https://www-dev.w3.org/events/conferences/. I have also fixed a bug where filtering by event type wasn't actually doing anything.
Note that event type titles are singular, so the title is as well. We should probably pluralize them.

**Comment by vivienlacourba** [comment]
@jean-gui I added the above text to the staging site could you check why those pages return 404?

ie. https://www-staging.w3.org/events/tpac/ vs. https://www-dev.w3.org/events/tpac/

FYI, I also updated various page leads on staging and at some point reached the same caching issues (my changes were not reflected even in preview mode), for example the page intro text which I added in the CMS is not yet showing up on:
https://www-staging.w3.org/staff/alumni/
