### ISSUE TITLE
https://beta.w3.org/groups is 404

### ISSUE THREAD

**Issue by plehegar** [w3c/w3c-website#353]
**Describe the issue**

https://beta.w3.org/groups is 404. It should redirect to https://beta.w3.org/groups/ or something similar.

**To reproduce**

1. Load https://beta.w3.org/groups/wg/
2. Follow the link to Groups in the nav bar "Home > Groups > Working Groups"
3. Get a 404 

**Expected behavior**

200 or redirect to groups/

**Screenshots**

N/A

**Additional context**

None

**Comment by gosko** [comment]
I fixed the 404, but it would be good to update the link in the breadcrumbs to include the trailing slash. @jean-gui do you know where that is maintained?

**Comment by jean-gui** [comment]
Fixed. I've also changed the title of the breadcrumb so that it matches /groups/
