### ISSUE TITLE
Ordered Lists visual display improvement

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#354]
**Describe the issue**
The way ordered lists are rendered can be improved. 

**URL**
For example, this blog post uses a few ordered lists: https://beta.w3.org/blog/2023/answering-what-aria-can-i-use/ 

**screenshot**
<img width="440" alt="Screenshot 2023-06-01 at 19 47 04 " src="https://github.com/w3c/w3c-website/assets/3716853/340f19e8-c07d-4daa-96f0-b46650ca7821">

**Recommended solution**
Adding a dot after the numbers might help readability.

**Comment by vivienlacourba** [comment]
This has been fixed in https://github.com/w3c/w3c-website-templates-bundle/pull/102

See: https://www.w3.org/blog/2023/answering-what-aria-can-i-use/
