### ISSUE TITLE
Blockquotes look better in the backend than in the frontend

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#355]
**Describe the issue**
The way blockquotes are rendered should be improved. 

**URL**
For example, this blog post uses a blockquote: https://beta.w3.org/blog/2023/answering-what-aria-can-i-use/ 

**screenshot**
<img width="440" alt="Screenshot 2023-06-01 at 19 49 27 " src="https://github.com/w3c/w3c-website/assets/3716853/7fe7f8cf-b0c6-4255-bc71-d6b284d729d6">

**Recommended solution**
I would be happier with any rendering that is close to what we see in the Craft CMS backend, for example:

<img width="595" alt="Screenshot 2023-06-01 at 19 50 48 " src="https://github.com/w3c/w3c-website/assets/3716853/b754e471-4a55-4896-8232-0ea8070d0460">

**Comment by vivienlacourba** [comment]
Indeed this issues appears to be fixed now.
