### ISSUE TITLE
Space missing between paragraphs on logo policy page

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#357]
On the [Logos and icons policy page](https://beta.w3.org/policies/logos/#org-logos) there are table cells containing a number of `<p>` elements, currently displayed with no space between the paragraphs which makes the text difficult to read.

<img width="671" alt="screenshot of beta site" src="https://github.com/w3c/w3c-website/assets/7144396/9821ecd0-5f24-4512-bf1d-678b211bdee8">

I don't know if there is an issue with the markup used on this page in particular or if this is a more general problem with the CSS. I think paragraphs should be displayed with space between them by default with no extra markup or special context needed.

**Comment by koalie** [comment]
I tried to remove the style that was presumably from the previous design but it does not change spacing between paragraphs wihtin the table, and it worsened the layout of the logos. I left the inline style as it was.

**Comment by vivienlacourba** [comment]
Assigning to @NicolaSaunders to look at. I think that issue actually exists anytime there are 2 paragraph used outside of a text component.

**Comment by gosko** [comment]
Vertical space is sometimes missing around other elements as well, like the headings and blockquotes in [this press release](https://www.w3.org/press-releases/1999/rdf/):

<img width="705" alt="screenshot showing no vertical space between headings, paragraphs, and blockquotes" src="https://github.com/w3c/w3c-website/assets/7144396/b92994b8-f4ed-466c-9307-6958e92760fd">

**Comment by NicolaSaunders** [comment]
Proposed fix at https://github.com/w3c/w3c-website-templates-bundle/pull/111
