### ISSUE TITLE
Form checking: Ensure that the end date is after the start date

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#36]
**Describe the issue**
For content entries that have a start date and an end date it is possible to set the end date before the start date.

**To reproduce**
On any content entry that accept start and end dates (e.g. Alumni).
- In the Start date field enter "9/1/2021"
- In the End date field enter "1/1/2021"
- Click Save
- Craft will save the entry without reporting any error

**Expected behavior**

The form submission should fail indicating that the end date is before the start date.

**Comment by koalie** [comment]
@vivienlacourba is it related to #32 ?

**Comment by vivienlacourba** [comment]
> @vivienlacourba is it related to #32 ?

They both relates to dates but otherwise those are different issues.

**Comment by vivienlacourba** [comment]
Fixed with: https://github.com/w3c/w3c-website-craft/pull/33

**Comment by vivienlacourba** [comment]
There was a remaining issue that @jean-gui fixed in https://github.com/w3c/w3c-website-craft/commit/94afd79babfedb672e8fc7e3c75b5b42cdcdbaf5
It now appears to be working as expected.
