### ISSUE TITLE
home page <title>

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#366]
**Describe the issue**
home page title is:
> <title>We believe in one web for all - W3C    </title>

which is not optimum for accessibility or usability.

**Additional context**
Guidance for page titles:
* https://www.w3.org/WAI/test-evaluate/preliminary/#title (expand "Tips")
* https://www.w3.org/WAI/tips/writing/#provide-informative-unique-page-titles
* https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html

I suppose this would be acceptable:
> W3C - We believe in one web for all

**Comment by koalie** [comment]
Thanks!
@jean-gui and I just went over this and decided on "W3C"
