### ISSUE TITLE
Web Accessibility -> Accessibility

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#367]
Change "Web Accessibility" to "Accessibility" throughout. e.g.:

![image](https://github.com/w3c/w3c-website/assets/6991814/32813018-fbea-4631-bc2c-89b278373bb3)

_[image description: https://beta.w3.org/mission/accessibility/ with "Web Accessibility" circled 3 places]_

and ```<title>Web Accessibility - W3C    </title>```

I'm happy to provide rationale if useful.

**Comment by koalie** [comment]
<img width="615" alt="Screenshot of https://www.w3.org/mission/accessibility/ with updated strings" src="https://github.com/w3c/w3c-website/assets/3716853/643c370b-5d06-490e-a907-f217abcb0af3">

Done!

**Comment by shawna-slh** [comment]
Many thanks! and great apologies that I didn't submit it sooner :-(

Do you also want to update the order of "In this section" so it's alphabetical?
<img width="615" alt="Screenshot of https://www.w3.org/mission/accessibility 'In this section' highlighted" src="https://github.com/w3c/w3c-website/assets/6991814/ade36eb5-c1d1-4fa1-91f8-13a19629ee65">

and matches:
<img width="615" alt="Screenshot of https://www.w3.org/mission/ with 'principles of accessibility, internationalization, privacy, and security' highlighted" src="https://github.com/w3c/w3c-website/assets/6991814/6876f0f5-2e10-445e-ba5f-f91ab88ee348">

**Comment by koalie** [comment]
Purging the cache fixed this.
