### ISSUE TITLE
Incorrect redirect from original site to beta site

### ISSUE THREAD

**Issue by AustinAggiss** [w3c/w3c-website#368]
**Describe the issue**
The Mission page on the original W3C website does not redirect to the correct page on the beta site, and returns a 404 as it is not redirecting to the [correct page](https://beta.w3.org/about/mission/).

**To reproduce**
1. Visit [https://www.w3.org/Consortium/mission](https://www.w3.org/Consortium/mission)
2. It redirects to [https://beta.w3.org/about/mission/](https://beta.w3.org/about/mission/), which is a 404 page.

**Expected behavior**
Redirects here instead: [https://beta.w3.org/mission/](https://beta.w3.org/mission/)

**Comment by vivienlacourba** [comment]
Fixed.
Thx for your report!
