### ISSUE TITLE
On news items (and blog posts with no author) the "Published date" and its date are misaligned

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#37]
**Describe the issue**

On a blog post with no author set the "Published date" and its date are misaligned.

**Recommended solution**

The "Published date" and its date should be aligned properly horizontally.

**Screenshots**

A Blog post with an author has the content of its "Published date" line aligned correctly.

![blog-post-with-author](https://user-images.githubusercontent.com/2012282/139253180-6fe671de-788e-4c6a-bbf6-9662f083195a.png)

A Blog post **without** any author set has the content of its "Published date" line misaligned.

![blog-post-without-author-with-bogus-published-date-alignement](https://user-images.githubusercontent.com/2012282/139253198-85b65e8f-7718-42b6-873b-5bb9e3e06791.png)

**Comment by vivienlacourba** [comment]
Actually I see that this issue also exists for all News items as they don't have any author.
e.g. https://www-staging.w3.org/news/2021/test-new/

**Comment by JuliaSang** [comment]
@NicolaSaunders Please can you review this ticket, leave advice for @maries24 on how to implement, and then reassign to @maries24 before 8/2/22. Cheers!

**Comment by NicolaSaunders** [comment]
@maries24 In `80-templates/_post.scss` there is a declaration for `dt:first-of-type` with a `padding-top` value equivalent to 8px. Leave the padding value as is, but change the declaration to:

```
dt:first-of-type,
dd:first-of-type {}
```
