### ISSUE TITLE
correct accessibility technical text

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#371]
**URL**
https://beta.w3.org/mission/accessibility/

**Incorrect wording on page**
First sentence of:
> The Web is fundamentally designed to work for people of different geographical locations, cultures, languages, accessibility needs, gender identities, and more. When the web meets this goal, it is accessible to people with a diverse range of hearing, movement, sight, and cognitive ability.

**Source wording**
From https://www.w3.org/WAI/fundamentals/accessibility-intro/ :
> The Web is fundamentally designed to work for all people, whatever their hardware, software, language, location, or ability. When the Web meets this goal, it is accessible to people with a diverse range of hearing, movement, sight, and cognitive ability.

**Fix**
Replace:
> The Web is fundamentally designed to work for people of different geographical locations, cultures, languages, accessibility needs, gender identities, and more.

with:
> The Web is fundamentally designed to work for all people, whatever their hardware, software, language, location, or ability.

**Rationale**
The point is about the fundamental **technical** architecture of the Web. It is not a social statement.

**Comment by iadawn** [comment]
Is the 'fundamentally' necessary?

Actually, is that whole paragraph and title at all necessary? (The paragraph under the heading 'The power of the web')

The intro quote from timbl frames the theme. Then the section headed 'Including everyone' expands on what universality means. The point about technical architecture may be lost but I don't know if it would be clear enough with the rewrite anyway.

**Comment by vivienlacourba** [comment]
Text fixed.
