### ISSUE TITLE
TR page formatting inconsistent across views

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/w3c-website#378]
**Describe the issue**
The base TR page  (w3.org/TR) does not feature the new site designs, but when query params are added, it does.

**To reproduce**
New style shown: https://www.w3.org/TR/?title=
Old style shown: https://www.w3.org/TR/

Also, with some views I get back this error:

<blockquote>
There is a problem

    [This form should not contain extra fields.](https://www.w3.org/TR/?title=secure&tag=&status=&version=#)
    [This value is not valid.](https://www.w3.org/TR/?title=secure&tag=&status=&version=#_status)
</blockquote>

**Expected behavior**
New style everywhere.

**Comment by gosko** [comment]
Hi @ianbjacobs, this must be a cache issue. Can you please try a shift-reload?

If you're still getting stale results it could be a cache issue with our CDN, but it shouldn't be.

**Comment by ianbjacobs** [comment]
Looks like a cache issue that resolved itself. Thanks!
