### ISSUE TITLE
Redirect missing for previous query parameters used by TR page

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#381]
The [previous version](http://web.archive.org/web/20230619043311/https://www.w3.org/TR/) of the [TR page](https://www.w3.org/TR/) allowed filtering by title, tag, status, version; the new one does too but the query parameters have changed. It would be good to redirect them if possible, at least for the most common cases.

Some examples of pages that link directly to specific views of the TR page:

https://www.w3.org/wasm/ -> https://www.w3.org/TR/?title=webassembly
https://www.w3.org/2013/data/ -> https://www.w3.org/TR/?tag=data
https://www.w3.org/Consortium/facts.html -> https://www.w3.org/TR/tr-date-stds.html -> https://www.w3.org/TR/?status=rec
https://www.w3.org/2020/05/w3c-highlights/ -> https://www.w3.org/TR/?title=css (and many others)
https://www.w3.org/WAI/APA/ -> https://www.w3.org/TR/?title=accessibility%20user%20requirements and others

We could find and fix many of these links on our own site but there may be similar links from other sites so it would be good to redirect them.

**Comment by deniak** [comment]
We do have a few redirects handled by the rewrite system and the links from the pages you listed above should be updated.
That being said, I'm thinking we might need to handle these redirects from symfony so we can update the QS with the right parameters (whether there's one or multiple params).

**Comment by gosko** [comment]
I don't think we need to handle every possible query combination, but it seems worthwhile to handle the simple/common cases given how easy it would be to implement.

https://www.w3.org/TR/?title=webassembly -> https://www.w3.org/TR/?filter-tr-name=webassembly
https://www.w3.org/TR/?tag=data -> https://www.w3.org/TR/?tags[]=data
https://www.w3.org/TR/?status=rec -> https://www.w3.org/TR/?status[]=standard

**Comment by deniak** [comment]
Checking the logs, we still get a few requests with the tag and status filters.
I added these redirects on symfony.
