### ISSUE TITLE
Incorrect link: Validator and Tools - NU Html Checking github

### ISSUE THREAD

**Issue by leevigraham** [w3c/w3c-website#383]
**Describe the issue**

Nu HTML Checker Github and Issue links point to "Link Checker" not "Nu HTML Checker"

![image](https://github.com/w3c/w3c-website/assets/25124/e0fd023b-06ae-40f4-9904-0b4ef098918a)

**URL**

https://www.w3.org/developers/tools/

**Comment by vivienlacourba** [comment]
Fixed.
Thank you for your report!
