### ISSUE TITLE
Some CSS and JS resources are not minified

### ISSUE THREAD

**Issue by JulienWilhelm** [w3c/w3c-website#384]
**Describe the issue**
Some CSS and JS resources are not minified. For instance:
- https://www.w3.org/assets/website-2021/styles/core.css?ver=1.4
- https://www.w3.org/assets/website-2021/styles/advanced.css?ver=1.4
- https://www.w3.org/assets/website-2021/js/main.js?ver=1.4
- https://www.w3.org/assets/website-2021/js/members.js

**To reproduce**
Just open devtools, go to "Network" panel and reload the page to inspect these resources.

**Expected behavior**
Theses files should be minified to reduce bandwitch.

**Comment by gosko** [comment]
We decided to skip minification, as noted in the [project blog](https://w3c.studio24.net/docs/front-end-standards/):

> Do not minify HTML, CSS or JavaScript to help others read the code and learn from it.

The difference in sizes is quite small after compression: for example for core.css the [minified version](https://www.w3.org/assets/website-2021/styles/core.min.css?ver=1.4) is 14.36 kB transferred while the [regular version](https://www.w3.org/assets/website-2021/styles/core.css?ver=1.4) is 22.58 kB transferred.

To reduce bandwidth usage I think it's more important to give long cache lifetimes to these resources, and optimize our images better (issue #288)

**Comment by JulienWilhelm** [comment]
Ok, I hadn't seen that. 
There is always the possibility of separating the sources (readable) from the production (minified), but if it is a wise choice, there is nothing more to say. 
I agree with the other bandwidth reduction leads.
