### ISSUE TITLE
Pagination bar template

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#39]
The current pagination template displays the bar like so:
When on page 1: `<< Previous *1* 2 3 4 5 … 11 Next >>`
When on page 5: `<< Previous 1 2 3 4 *5* … 11 Next >>`
When on page 11: `<< Previous 1 2 3 4 5 … *11* Next >>`
I don't know if that's the intended behavior or if we want to show x items before and after the current one.
If that's the case, the second example would then become: `<< Previous 1 2 3 4 *5* 6 7 8 9 … 11 Next >>`.

There's also a bug when we are not on a page that appears in the bar.
For example, on page 8: `<< Previous 1 2 3 4 5 … 11 Next >>`. The current page is not being displayed at all.
It should probably look like `<< Previous 1 2 3 4 5 … 8 … 11 Next >>` or perhaps `<< Previous 1  …6 7 *8* 9 10 11 Next >>`.

I'm not sure if we have a complete spec of all the possible states, but the template definitely needs to be updated to handle all the possibilities.

**Comment by vivienlacourba** [comment]
cc: @jean-gui
