### ISSUE TITLE
survey results text overlapping with zoom

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#391]
**Describe the issue**
There is a list at the top. When I scroll down, the results overlap with the list.

**URL**
https://www.w3.org/register/tpac2023/registrants#meeting-197

**Additional context**
screen video (Vivaldi browser):

https://github.com/w3c/w3c-website/assets/6991814/1be1c536-1b6d-46f8-be51-05a7b6a0416c

**Comment by FONGNUN23** [comment]
มีรายการอยู่ด้านบน เมื่อฉันเลื่อนลง ผลลัพธ์ซ้อนทับกับรายการ

**Comment by jean-gui** [comment]
The list should not overlap anymore with the content if the browser is narrow or zoomed in a lot.
