### ISSUE TITLE
Add links to bylaws and cert. of incorporation on policies page

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/w3c-website#394]
**Describe the issue**
Suppose you are looking for the W3C bylaws. A reasonable starting place is the "About W3C" menu which has a Policies and legal information entry to:
   https://www.w3.org/policies/

I suggest adding a new section to that page (indeed, the first section) titled "W3C Governance" that includes links to:
 https://www.w3.org/2022/10/w3c-bylaws-20221019
 https://www.w3.org/2022/10/w3c-charter-20221019

**Comment by ianbjacobs** [comment]
Also link to the 1023 information when available.

**Comment by japuiglaucia** [comment]
Add links to bylaws and cert. of incorporation on policies page #394

**Comment by koalie** [comment]
The page "policies and legal information" now includes a [section "Corporation"](https://www.w3.org/policies/#corporation) that points to to a new public page. That page has links to the bylaws, cert of incorporation, Form 1023 and will have more links as more documents become available.
