### ISSUE TITLE
[calendar] Calendar events use giant fonts

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#400]
**Describe the issue**
The What/When section of a calendar event is using a ginormous font size for some reason.

(The thing that should be ginormous (if any) is the Join button... which is at the bottom of the event.)

**To reproduce**
Open an event such as https://www.w3.org/events/meetings/a479f996-24f7-4249-b780-c731ea6e9d9f/20230628T070000/

**Expected behavior**
Expected: Expected some neatly laid out text in a compact and readable format.
Actual: Really big text, poor visual hierarchy.

**Comment by jean-gui** [comment]
The part that uses a big font is the event description. In the [design system](https://design-system.w3.org/templates/event.html) it is supposed to be a very short description. But for these events we don't have control over the size of this description, so it probably makes more sense to move it after the metadata so it would have the same size as the rest of the text (agenda, joining instructions, ...)

@fantasai, how does that sound to you?

**Comment by fantasai** [comment]
I defer to your judgement @jean-gui. :)

**Comment by jean-gui** [comment]
I have moved the description after metadata.

I have also re-added something that got lost with the redesign: an "in-your-face" message at the top of the page when the meeting is in-progress or about to start (you only see the button if you have permission to join):

![Screenshot_20230804_112017](https://github.com/w3c/w3c-website/assets/1479073/38c4eb6e-9829-403d-b92f-bcd915812d73)
