### ISSUE TITLE
Cool URIs don't change

### ISSUE THREAD

**Issue by Calorion** [w3c/w3c-website#406]
**Describe the issue**

<https://www.w3.org/standards/xml/schema.html> is forwarded to <https://www.w3.org/standards/>

**To reproduce**
Visit <https://www.w3.org/standards/xml/schema.html>.

**Expected behavior**

Information about XML schemas appears. 

**Screenshots**

**Additional context**
[Cool URIs don't change](https://www.w3.org/Provider/Style/URI).

**Comment by koalie** [comment]
This page, and a number of other high-level ones that introduced specifications, had not been maintained, or were no longer maintainable, or gave obsolete information.

We redirect those to the W3C Standards and Draft directory where people can look for information related to any specification or technology, and benefit from the latest version or the historical versions, which are better entry points than the former high-level introduction pages.
