### ISSUE TITLE
Add spacing between datetime and location on event cards

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#41]
Add spacing between datetime and location on event cards
<img width="391" alt="Screenshot 2021-10-26 at 09 32 19" src="https://user-images.githubusercontent.com/20167528/140777446-90426370-89ef-4abd-95fe-05fa74c22eb8.png">

**Comment by vivienlacourba** [comment]
Related design system entry https://design-system.w3.org/templates/listings.html#list-of-events

**Comment by JuliaSang** [comment]
@NicolaSaunders Please can you review this ticket, leave advice for @maries24 on how to implement, and then reassign to @maries24 before 8/2/22. Cheers!

**Comment by NicolaSaunders** [comment]
@maries24 In `80-templates/_listing.scss`, I recommend nesting the following declaration within the `.event-list` class styles:

```
.date-location time {

	display: inline-block;
	padding-bottom: rem(10);

}
```

(Feel free to change the `padding-bottom` value as required. There's already a declaration for `.date-location img`, so somewhere near this would make sense.)
