### ISSUE TITLE
TR page should give access to spec history

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#422]
**Describe the issue**
W3C has pages tracking the history of a spec, but it's not possible to get there from the /TR index, which means that for older specs (that don't have this link in their headers), it's impossible to reach.

**URL**
https://www.w3.org/TR/

**Recommended solution**
Provide the history link in the /TR index.

**Additional context**
The /TR index for some reason prioritizes showing the editors (which I can't imagine anyone really cares about having in an index) over links to the spec history or to the authoring WG, which are actually important to show in an index...

CC @plehegar

**Comment by deniak** [comment]
It was decided to remove the history links from the TR page with the [goal to make the page more readable](https://w3c.studio24.net/updates/redesigning-the-landing-page-for-technical-reports/#overwhelming-amount-of-information) especially when you can get the information in the spec itself.
I agree we no longer have a reference to the history for older specs so +1 to add the link back (maybe on the date).

**Comment by fantasai** [comment]
@deniak On which topic, I would remove the Editors and add back the Working Group. Specs are produced by WGs, not by editors.

**Comment by plehegar** [comment]
+1 on adding the link as well.

**Comment by deniak** [comment]
We've just added the history link back to the TR page.

> @deniak On which topic, I would remove the Editors and add back the Working Group. Specs are produced by WGs, not by editors. The WG link gets you to context on how to get involved, and it also works as a good topic filter. Editors gets you... nothing interesting.

@plehegar, what do you think about replacing the list of editors with the WG? We did keep the list as a way to "thank" the editors who wanted to promote their work but I'm not sure this needs to be kept on /TR. Their names are already displayed at the top of the spec and the list of editors is also available from the W3C API.
As @fantasai mentioned, we should probably put the WG forward instead.
Also for [the reasons discussed during the redesign](https://w3c.studio24.net/updates/redesigning-the-landing-page-for-technical-reports/), I would not keep both the editors and the groups.

**Comment by plehegar** [comment]
sgtm, go ahead.

**Comment by deniak** [comment]
The editors list has been replaced with a link to the WG's page.
