### ISSUE TITLE
home page UX issues - add more news from the news section

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#426]
**Describe the issue**
From the home page, I scrolled down to News. Then I wanted to get to other news... I looked all around that section and didn't find how to do that. (eventually I saw the link at the top)

**URL**
https://www.w3.org

**Recommended solution**
In the news section at the bottom, include a link/button to get more news, as in the others sections on that page

**Comment by vivienlacourba** [comment]
>  In the news section at the bottom, include a link/button to get more news, as in the others sections on that page

The "latest News" block is actually an aggregate of recent content that could be news items, blog posts press releases.

The [homepage example in the design system](https://design-system.w3.org/templates/home.html) actually had an intro text for that section e.g. "Highlights from across our News, Press Releases and Blog".

I believe we should add a similar intro text on the current homepage and probably augment it with some links, either:
- linking to the ["News & Events" page](https://www.w3.org/news-events/).
> Highlights from across our [News, Press Releases and Blog](https://www.w3.org/news-events/)"
- or to each individual listing page:
> Highlights from across our [News](https://www.w3.org/news/), [Press Releases](https://www.w3.org/press-releases/) and [Blog](https://www.w3.org/blog/)

**Comment by shawna-slh** [comment]
> I believe we should add a similar intro text on the current homepage and probably augment it with some links, either:

...

> or to each individual listing page:
>> Highlights from across our [News](https://www.w3.org/news/), [Press Releases](https://www.w3.org/press-releases/) and [Blog](https://www.w3.org/blog/)

mild +1 to each individual listing page

**Comment by koalie** [comment]
Done!
