### ISSUE TITLE
Make it easier to find standards

### ISSUE THREAD

**Issue by Secret-chest** [w3c/w3c-website#431]
**Describe the issue**
Currently, to access the web standard specifications, you must click on the "Learn more about Web standards", then on "W3C Standards and Drafts", then _search_ for your standard.

**Expected behavior**

There should be a link in the header, in the Standards submenu, that leads to the list of standards. When you want to do work, having to go through that Standards intro is annoying.

**Comment by gosko** [comment]
There is a item in the Standards menu at the top of every page that links directly to '[W3C standards and drafts](https://www.w3.org/TR/)'
