### ISSUE TITLE
"Icons and descriptions" icon picker broken

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#434]
**Describe the issue**
"Icon" is one of the mandatory fields of the card in the "Icons and descriptions". But the picker is broken. I don't know how to get an icon in there.

**To reproduce**
Put the focus in the "Icon" field. Immediately after a speech bubble appears underneath with text "No icons match your query.", and stays there,  no matter what I type. If I try to copy an icon from an existing card, it disappears from the field and the same speech bubble appears.

**Expected behavior**
When I type, the picker finds the closest match or at least appears with a list of icons to choose from.

**Screenshots**
<img width="596" alt="Screenshot 2023-07-18 at 14 55 42" src="https://github.com/w3c/w3c-website/assets/3716853/9fb446f1-ca02-43c8-87ad-3538f9a974d5">

**Comment by Edherivan** [comment]
> **Describe the issue** "Icon" is one of the mandatory fields of the card in the "Icons and descriptions". But the picker is broken. I don't know how to get an icon in there.
> 
> **To reproduce** Put the focus in the "Icon" field. Immediately after a speech bubble appears underneath with text "No icons match your query.", and stays there, no matter what I type. If I try to copy an icon from an existing card, it disappears from the field and the same speech bubble appears.
> 
> **Expected behavior** When I type, the picker finds the closest match or at least appears with a list of icons to choose from.
> 
> **Screenshots** <img alt="Screenshot 2023-07-18 at 14 55 42" width="596" src="https://user-images.githubusercontent.com/3716853/254270341-9fb446f1-ca02-43c8-87ad-3538f9a974d5.png">
