### ISSUE TITLE
More gracious errors on TPAC reg page

### ISSUE THREAD

**Issue by samuelweiler** [w3c/w3c-website#436]
**Describe the issue**

When an unaffiliated user tries to register for TPAC, instead of being told "you're not eligible to attend TPAC. If you think you are, here's how to sort that out", they get a 403 Forbidden error, specifically:

"Access Denied The server returned a "403 - Forbidden" error. You do not have sufficient privileges to access the page that you requested..."

**To reproduce**

Logged in as a test user, load https://www.w3.org/register/tpac2023/form

**Expected behavior**

I want a gracious error message that tells people how to address the issue.

**Screenshots**
![image](https://github.com/w3c/w3c-website/assets/24963390/3a6499b3-f3c9-47c7-8f2e-db45e7c7a09b)

**Additional context**

**Comment by jean-gui** [comment]
The message is now more informative:
![Screenshot_20230721_161421](https://github.com/w3c/w3c-website/assets/1479073/efc13a43-fce7-411e-b13f-8788f6087ba8)

**Comment by samuelweiler** [comment]
@jean-gui Thank you!
