### ISSUE TITLE
Web Accessibility Reflow Issue(s)

### ISSUE THREAD

**Issue by rwinn1103** [w3c/w3c-website#437]
My name is Robert Winn, and I am a Ph.D. student researching web accessibility. I came across the web page https://www.w3.org/  and realized it contains issues for users attempting to access the page’s various functionalities with keyboard-based assistive technologies. Specifically, several functionalities have been identified that are available to the keyboard in the full-sized version but not when rendering the page with a horizontal viewpoint of 320 pixels (i.e., reflowed version). This is considered an accessibility issue per Web Content Accessibility Guidelines (WCAG). As such, I have attached a document that briefly lists the identified functionalities and the XPaths of the associating elements that are available in the full-sized version but not in the reflow version.
 
 While the majority of the users navigate your website with a mouse, the few that are dependent on keyboards would really benefit from a fix to this problem. I hope this will open up your web platform to a broader audience and better comply with the WCAG standards. Please refer here to learn more about accessible Responsive Web Design https://www.w3.org/WAI/WCAG21/Understanding/reflow.html.

Finding these kinds of problems, learning about their impact on disabled users, and tracking how web companies address them is an important aspect of my research. If you would be so inclined, would you mind letting me know (1) whether you think our findings are beneficial to improving your site’s accessibility for your users and (2) whether you plan to address the issues we discovered? Your feedback would be greatly appreciated and aid in my research on web accessibility. Thank you very much for your time, and I hope to hear from you soon.

Best regards,
Robert Winn
USC PhD Student
[w3.pdf](https://github.com/w3c/w3c-website/files/12099383/w3.pdf)

**Comment by gosko** [comment]
Hi @rwinn1103, thanks for your report.

Based on the links listed in your report I believe your review is based on the previous version of our web site.

Last month we [released a new version of the site](https://www.w3.org/blog/2023/new-w3c-website-deployed/) which has many improvements over the old site, and has been reviewed and tested for accessibility including keyboard navigation.

If you find any issues with the new site you are welcome to create more issues to report them here.
