### ISSUE TITLE
Landing page template - move "Read this in" translation page links

### ISSUE THREAD

**Issue by JuliaSang** [w3c/w3c-website#44]
After discussion with @simonrjones  &  @maries24  we want to move the "Read this in" translation page links directly beneath the H1 on the landing page template - not in a box - since the hero is already in a grey background.

This helps bring these links higher up the page, but still clearly within the current page content.

**Comment by maries24** [comment]
Hi @JuliaSang @simonrjones Could I please get some time from @NicolaSaunders to help on this. It is not just a matter of moving the component. The CSS needs to to be reviewed to make it work in the context of the hero. Thanks.

**Comment by JuliaSang** [comment]
@vivienlacourba - @NicolaSaunders has prototyped the changes discussed above and it has been checked by the team. Before @maries24 implements it in the template bundle and front-end app, please can you review and let us know if you'd like any other changes? 

https://w3c-dev.studio24.dev/landing/index.html

**Comment by vivienlacourba** [comment]
> @vivienlacourba - @NicolaSaunders has prototyped the changes discussed above and it has been checked by the team. Before @maries24 implements it in the template bundle and front-end app, please can you review and let us know if you'd like any other changes?
> 
> https://w3c-dev.studio24.dev/landing/index.html

Visually this looks good and even better to us (@koalie @jean-gui and I).

As this text appear at the beginning of the page content but does not use any specific html semantic, I was wondering how it would get indexed by search engines? (For indexing I woudl think it is secondary info compared to the rest of the page)

**Comment by maries24** [comment]
Hi @vivienlacourba, Good question. I tested using a 'nav' element instead of 'section' and it works as well. @NicolaSaunders Anything against us using a 'nav' element for the in-page translation menu as this might make more sense semantically? Thanks.

**Comment by vivienlacourba** [comment]
@maries24 please note that @gosko also had some interrogations about the use of an `<h2>` around the text "Read this page in" (maybe that comment is moot if this block is now within a `<nav>`?)

```
<gerald> I don't think 'Read this page in' should be in a h2, otherwise LGTM
<gerald> it messes with the outline of the page https://validator.w3.org/nu/?doc=https%3A%2F%2Fbeta.w3.org%2Fecosystems%2F&showoutline=yes#headingoutline
```

**Comment by NicolaSaunders** [comment]
@maries24 I don't have anything against making this use `nav` rather than `section`. Because there are other `nav` elements in use, it will need to have a unique and descriptive `aria-label` added to it - I would suggest `nav aria-label="Translations"`. The aria-label text will need to be translatable in the template bundle.

The `h2` can also be replaced with a simple `span` or `p`, but please note that there are styles currently attached to the `h2` so they will need to be updated to whatever element is used instead.

**Comment by vivienlacourba** [comment]
@maries24 I believe the new HTML semantic for this translation nav menu, should be also deployed on other templates and not only the Landing pages.

For example see this press release https://www-staging.w3.org/press-releases/2021/webrtc-rec/ which still uses the previous markup (`<section>` + `<h2>`).

**Comment by maries24** [comment]
Thanks for pointing that out @vivienlacourba 

I've updated the markup of the translation components on other templates too (and updated the design system accordingly)

**Comment by vivienlacourba** [comment]
Thanks for this update @maries24.

Per @NicolaSaunders' previous comment https://github.com/w3c/w3c-website/issues/44#issuecomment-1054129453 shouldn't the `aria-label="Translations"` be added to the nav? and I understand that this will need to be a translatable string (cc: @jean-gui).

I'm also seeing an horizontal alignment issue between the "Read this page" text and the list of languages (on Firefox 97), see:
- The [design system - Translation component](https://design-system.w3.org/components/translations.html)
![design-system-translation-component](https://user-images.githubusercontent.com/2012282/156769932-e5d0c477-c214-4251-b7b1-31558a114050.png)
- [Press release example](https://www-staging.w3.org/press-releases/2021/webrtc-rec/) (Here the misalignment is present but less pronounced)
![webrtc-pr-translations](https://user-images.githubusercontent.com/2012282/156769949-b17ab0dc-d272-44e8-8107-12ce7e74f294.png)

**Comment by maries24** [comment]
Hi @vivienlacourba I've made these changes now. Sorry, Fridays don't seem to agree with me...
