### ISSUE TITLE
Can't get list of participants

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#449]
**Describe the issue**
The link from the APA homepage to the list of participants yields a page that lists no participants.

**URL**
https://www.w3.org/groups/wg/apa/
https://www.w3.org/WAI/APA/

**Recommended solution**
Fix the templates to spit out the info?

**Additional context**
Doesn't seem that any other groups have participants listed either.

**Comment by xfq** [comment]
I clicked on the 'Participants' link on the right of the page (of the first link), and I could see the list of participants.

Perhaps the link in the bottom left corner of https://www.w3.org/WAI/APA/ should link directly to https://www.w3.org/groups/wg/apa/participants/ ?

/cc @ruoxiran

**Comment by ruoxiran** [comment]
> 

thanks fuqiao, issue fixed.

**Comment by ruoxiran** [comment]
> Fix the templates to spit out the info?
Thanks for the suggestion. The APA website template was established by Michael. Now that he has left W3C, WAI is discussing to synchronize these websites under the WAI domain name. 

Also, I fixed the Participants link to the right page.
