### ISSUE TITLE
Improve quote component

### ISSUE THREAD

**Issue by NicolaSaunders** [w3c/w3c-website#454]
**Describe the issue**
The [quote component](https://design-system.w3.org/components/quote.html) uses the `figure` and `figcaption` elements to hold a blockquote and citation. This follows an [example pattern from MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure#quotations).

This pattern has recently been flagged as [overly verbose for screen reader users](https://adrianroselli.com/2023/07/blockquotes-in-screen-readers.html).

**URL**
https://www.w3.org/about/ (see the Tim Berners-Lee quote, roughly halfway through the page)

**Recommended solution**
Consider replacing the `figure` with `div` and `figcaption` with `footer`, or refactoring the quote component to be closer to the pattern presented at https://adrianroselli.com/2023/07/blockquotes-in-screen-readers.html#Example07

**Comment by vivienlacourba** [comment]
cc: @iadawn

**Comment by NicolaSaunders** [comment]
@iadawn Well, indeed. I just wanted to note the issue and potential solutions here. If it's not needed to hook onto for styling then I wouldn't include the `div`, but I want to be sure in the context of the design system.

**Comment by iadawn** [comment]
I would be for removing it to make the pattern just that little bit cleaner

**Comment by NicolaSaunders** [comment]
Pull request raised at https://github.com/w3c/w3c-website-templates-bundle/pull/123

**Comment by deniak** [comment]
The fix has now been deployed. Thanks @iadawn and @NicolaSaunders
