### ISSUE TITLE
OWL2 docs are missing w3c icon

### ISSUE THREAD

**Issue by bblfish** [w3c/w3c-website#460]
**Describe the issue**
W3C icons are missing (see picture below)

**URL**
[OWL2 RDF Based Semantics](https://www.w3.org/TR/owl2-rdf-based-semantics/)
[OWL2 Overview](https://www.w3.org/TR/owl2-overview/)

**Recommended solution**
link to the new icon, or place the old icon back in the same position

**Additional context**
I am using Safari 17 beta release (so it may (but is unlikely) be a problem with the browser)

<img width="691" alt="Screenshot of Safari 17 on 2023-08-03 at 15 39 34" src="https://github.com/w3c/w3c-website/assets/124506/471a850a-7420-4a32-b646-25426f79e126">

But it also appears on Chrome (though it is less visible there).
<img width="780" alt="Screenshot of Chrome on 2023-08-03 at 15 42 54" src="https://github.com/w3c/w3c-website/assets/124506/63548a26-1951-4c9d-8cd5-e206d57bc49f">

**Comment by deniak** [comment]
@bblfish thanks for the report. This is now fixed.
