### ISSUE TITLE
"accessibility needs" -> "disabilities"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#464]
**Describe the issue**
In
> strive for diversity and inclusion of participants from different geographical locations, cultures, languages, accessibility needs, gender identities, and more.

"accessibility needs" -> "disabilities"

Many people with disabilities prefer this language.

**URL**
https://www.w3.org/mission/
and anywhere else that wording is

**Recommended solution**
"accessibility needs" -> "disabilities"

**Additional context**
https://github.com/w3c/AB-public/pull/99

**Comment by vivienlacourba** [comment]
Fixed.

Doing a [google search for "accessibility needs"](https://www.google.com/search?q=site:www.w3.org+%22accessibility+needs%22) mostly links pages under /WAI/ and no pages from the new site that I could identify.

**Comment by shawna-slh** [comment]
For the record and to inform future usage, note the different use of "accessibility needs" on /WAI/ pages &mdash; it is along _with_ "people with disabilities", e.g.:
* > ...how to better meet the accessibility needs of people with cognitive and learning disabilities [[1](https://www.w3.org/WAI/WCAG2/supplemental/#-cognitive-accessibility-guidance)]
* > These issues overlap with the accessibility needs of people with disabilities." [[2](https://www.w3.org/WAI/older-users/)]
* > Researching the accessibility needs of people with disabilities" [[3](https://www.w3.org/WAI/fundamentals/accessibility-usability-inclusion/)]

Whereas in above, "accessibility needs" was used as a _replacement_ for "disabilities".
