### ISSUE TITLE
Broken link on https://design-system.w3.org 

### ISSUE THREAD

**Issue by moddular** [w3c/w3c-website#475]
**Describe the issue**
The link to `Springer Nature Frontend Playbook` returns a 404 error

**URL**
https://design-system.w3.org

**Recommended solution**
It looks like the file extension used in the link is incorrect,
https://github.com/springernature/frontend-playbook/blob/main/practices/graded-browser-support.html should be https://github.com/springernature/frontend-playbook/blob/main/practices/graded-browser-support.md

**Comment by NicolaSaunders** [comment]
Something is converting the URL in the markdown file for the documentation and replacing the `.md` suffix with a `.html` suffix, whereby breaking the link. Will investigate.

**Comment by jean-gui** [comment]
The PR has been merged. Now waiting on https://github.com/w3c/w3c-website/issues/673 to deploy the fix.
