### ISSUE TITLE
Problem with the Validation Form on Account Creation

### ISSUE THREAD

**Issue by pablorod2** [w3c/w3c-website#476]
Upon creating an account with my mail and default username pablo_rod2 it shows that the mail address is already taken and that the username only accepts alphanumeric and hyphens. The username has an underscore that is a hyphen a number and letters. Then I request the site to send me my password "email already in use" with a response that says "we cannot find an account with that email address" So There is a problem with it I suggest as WWC that the validators for email tld be determined by the IANA and not by a specific programmer.  https://www.iana.org/domains/root/db

mail: pablo@rodriguez.cloud
user: pablo_rod2
![image](https://github.com/w3c/w3c-website/assets/142449621/bfb33ead-359b-4eab-af8d-782ba42d10f9)
![image](https://github.com/w3c/w3c-website/assets/142449621/7fa35d2f-a2b2-425a-948f-e16c782e9637)
![image](https://github.com/w3c/w3c-website/assets/142449621/5fef854a-3249-4ebb-8718-98013b99b75d)

Attaching screenshoots as requested.

**Comment by vivienlacourba** [comment]
Hi @pablorod2, sorry for the delay in answering your comment.

Your W3C Account had previously been disabled, I re-enabled it (note that your username is "pablor2").
You can reset your password at: https://www.w3.org/account/recover/

Regarding your comment underscore (`_`) are not accepted in W3C Account usnernames, only hyphens (`-`) are.
