### ISSUE TITLE
PWE Webpage Broken or Outdated Links on Website

### ISSUE THREAD

**Issue by rachelyager-nyc** [w3c/w3c-website#477]
**Describe the issue**
There are broken and outdated links on the PWE Webpage
**URL**
https://www.w3.org/about/positive-work-environment/
**Recommended solution**
Please review and update the links in the "Education and Training" section as shown below:

Education and Training:
Several resources are, or will be, available:

[MIT Preventing Sexual Harassment online Training](http://training.newmedialearning.com/psh/mit/) (which the W3C staff has taken)
[Email netiquette documents](http://tools.ietf.org/html/rfc1855)
[IRC guidelines](http://www.ircbeginner.com/ircinfo/etiquette.html)
[Codes of Conduct 101 + FAQ](http://www.ashedryden.com/blog/codes-of-conduct-101-faq)
[Geek Feminism Conference anti-harassment/Policy](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy)

**Additional context**
The Email Netiquette link is a 1995 reference that may need updating.

**Comment by koalie** [comment]
Thanks, @rachelyager-nyc 
Fixed!
