### ISSUE TITLE
/TR search 

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#486]
**Describe the issue**
Searching on /TR is very literal. It looks for exact match for the string searched. 

**To reproduce**
For example, someone searched "wcag 2.1" and the search returned zero result. This is because there is no specification with the exact string 'wcag 2.1' in its title. The title of the spec is "Web Content Accessibility Guidelines (WCAG) 2.1”, so searching for “wcag” would surface it, likewise for “(wcag) 2.1”.

**What's the best expected behavior?**
We could opt for matching each of the terms submitted but it would also make the search less precise because if you enter "wcag 2.1", the results would include all the specs having “wcag" in their title (good) but also all the specs that have “2.1” as part of their title (not so good).

Or, we could leave it as is and hope that people who didn't find any result would perhaps try a different term that is less specific.

I have a hunch it is worth showing more results including false positives, than none, but I am looking for more opinions.

**Screenshots**
![](https://lists.w3.org/Archives/Public/public-website-redesign/2023Aug/att-0002/image003.jpeg)

**Comment by koalie** [comment]
cc: @deniak

**Comment by gosko** [comment]
I don't know if there are generally accepted best practices for this but I think most people expect searches with multiple words like wcag 2.1 to be interpreted as a search for "wcag AND 2.1". Hopefully that would be fairly straightforward to implement. (split the search text on spaces, then return items that match each word specified)

Even better would be to support additional types of searches, like the ones near the top of [Google's Advanced Search page](https://www.google.com/advanced_search) which includes the above plus quoted phrases for exact matches, "a OR b", and negative search terms like -wcag but that would be much more work and seems less important.

**Comment by simonrjones** [comment]
I agree improving the TR search would be really helpful. 

I think @gosko's suggestion is a good idea. If this is possible to implement initially that would make the TR search more usable for people. Any more advanced search could be a future task to review.

> I think most people expect searches with multiple words like wcag 2.1 to be interpreted as a search for "wcag AND 2.1". Hopefully that would be fairly straightforward to implement. (split the search text on spaces, then return items that match each word specified)

**Comment by deniak** [comment]
I've implemented @gosko's suggestion, see https://www.w3.org/TR/?filter-tr-name=wcag+2.1.
@koalie if this is good enough for you, feel free to close this issue. I'll create a separate one to improve the search globally on our website.

**Comment by koalie** [comment]
Thank you! (belatedly)
