### ISSUE TITLE
PrivilegedPorts referenced as Priviliged ports

### ISSUE THREAD

**Issue by byersn8** [w3c/w3c-website#499]
**Describe the issue**
PrivilegedPorts referenced as Priviliged ports spelled with i vs e.

**To reproduce**
Page location - [w3.org-PrivilegedPorts.html](https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html)

**Issue Instances**
<h1>Priviliged ports</h1> | non-priviliged account,

**Expected Spelling**
<h1>Privileged ports</h1> | non-privileged account,

Page HTML output 
`
<html><head>
<title>Privileged Ports</title>

</head>
<body>

<a href="../../../"><img alt="W3C" src="../../../Icons/WWW/w3c_48x48.gif"></a>
<a href="../../"><img alt="httpd" src="../../../Icons/WWW/httpd48x.gif"></a>
<a href="Installation.html"><img alt="install" src="../../../Icons/WWW/install48x.gif"></a>

<h1>Priviliged ports</h1>

The TCP/IP port numbers below 1024 are special in that normal users
are not allowed to run servers on them.  This is a security feaure, in
that if you connect to a service on one of these ports you can be
fairly sure that you have the real thing, and not a fake which some
hacker has put up for you. <p>

The normal port number for W3 servers is port 80.  This number has
been assigned to WWW by the Internet Assigned Numbers Authority, IANA.
</p><p>

When you run a server as a test from a non-priviliged account, you
will normally test it on other ports, such as 2784, 5000, 8001 or
8080. </p><p>

</p><hr>

<h2>Under Unix</h2>

The Internet Daemon <code>inetd</code> (running as root) can listen
for incomming conections on port 80 and pass them down to a process
with a safer uid for the server itself. However, the
<code>httpd</code> versions 2.14 and later can be safely run as
<code>root</code> since they automatically change their user-id to
<code>nobody</code> or some other user-id depending on server setup.
<p>

</p><hr>

<h2>Under VMS </h2>

Under UCX, the process running as a server needs BYPASS privilege to
listen to ports below 1024.  This might mean you have to install the
server.  With other TCP/IP packages, privilege of some sort is
similarly required. <p>

</p><p>
</p><hr>
<address><a href="mailto:httpd@w3.org">httpd@w3.org</a>, July 1995</address>

</body></html>
`

**Additional context**
Issue found in additional location identified by w3 internal search - [w3.org/History - PrivilegedPorts.html ](https://www.w3.org/History/19921103-hypertext/hypertext/WWW/Daemon/User/PrivilegedPorts.html)

**Comment by vivienlacourba** [comment]
I fixed both typos.

Thank you for your report.
