### ISSUE TITLE
Home page - narrow width of hero component

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#5]
The current width of the hero component on the [Home page](https://w3c-dev.studio24.dev/home/index.html) leaves a lot of space to the right and causes the heading to be wrapped on desktop and text to be reflowed to very short lines on mobile. Some screen shots using Firefox on OS X:

![Screen Shot 2021-07-13 at 4 54 08 PM](https://user-images.githubusercontent.com/7144396/125539950-4cb69b9c-eb7b-4f94-862d-e060feee78f9.png)
![Screen Shot 2021-07-13 at 4 54 28 PM](https://user-images.githubusercontent.com/7144396/125539958-729277bc-a0d5-47eb-9c28-6b0c1f347b12.png)

Removing the max-width of 81.5% on .hero seems like an improvement, in my opinion. Also the current line-height of 1.4 makes that paragraph feel a bit dense to me. Sample screenshots with unconstrained width and line-height: 1.5:

![Screen Shot 2021-07-13 at 4 54 50 PM](https://user-images.githubusercontent.com/7144396/125539985-23bbeb7e-48ef-4efd-a003-407378353453.png)
![Screen Shot 2021-07-13 at 4 55 51 PM](https://user-images.githubusercontent.com/7144396/125539993-0f4160b7-46b6-40e7-aa4b-0c38b11eafaa.png)

That's still not ideal – maybe it would be good to keep the reduced width for the heading, but not the text? It would be nice if the heading stuck to one line on desktop, so I wonder if it's worthwhile to consider reducing the font size. (I find the heading sizes quite large in general, throughout all the prototypes.)

Test with smaller font on the h1:

![Screen Shot 2021-07-13 at 6 59 25 PM](https://user-images.githubusercontent.com/7144396/125548680-0bdd327d-2a33-47a1-966d-b788b36c2f96.png)

cheers

**Comment by JuliaSang** [comment]
@gosko I think this is a content issue, where the image uploaded has whitespace around it. If the image is replaced with one which has less whitespace, the gap will be reduced. This is something Coralie can control when she enters content into the CMS.

I have marked this as a content issue and assigned to @koalie for when she starts entering content. Let us know if you have any other notes about it. Thanks!

**Comment by vivienlacourba** [comment]
> @gosko I think this is a content issue, where the image uploaded has whitespace around it. If the image is replaced with one which has less whitespace, the gap will be reduced. This is something Coralie can control when she enters content into the CMS.
> 
> I have marked this as a content issue and assigned to @koalie for when she starts entering content. Let us know if you have any other notes about it. Thanks!

Looking again at this issue and I don't see why this is a content issue. @gosko mentioned issues about heading size, font size in general, text wrapping, spacing, and line-eight which is something we already heard several times and from several channels.

FYI here is the latest private feedback [[1](https://lists.w3.org/Archives/Team/team-website-redesign/2021Sep/0008.html)] we received on that topic:

**"The new design is hard to use on a "smaller" screen device (think iPhone 5)  The font size and line heights are too big. I had to set up zoom to 75% to be able to read the website comfortably."**

While I understand that it might be eaiser to look at this when we have real content isnetad of bolierplate text, let's not limit this to be simply a conent related issue.

**Comment by gosko** [comment]
The image on [the home page on the staging site](https://www-staging.w3.org/) has now been replaced with one with no space around it, and display is still suboptimal – the text is still wrapped to very short lines which makes it difficult to read. Also the image feels a bit too high compared to the text, and on the mobile view the image is right up against the 'Find out more about W3C' button.
Desktop:
![Screen Shot of desktop view in Firefox](https://user-images.githubusercontent.com/7144396/151479245-4ee1ed0c-170a-4a57-bde4-95cf760f1727.png)
Mobile:
![Screen Shot of mobile view on a Pixel 2XL simulated in Firefox](https://user-images.githubusercontent.com/7144396/151479302-6f361f47-e840-4cc2-8ad5-5458e02632ca.png)
Current image crop:
![Screen Shot showing current image crop](https://user-images.githubusercontent.com/7144396/151479385-f0c7a28d-b986-4acf-bcb7-898fadb4c2f5.png)

In my opinion it would be worthwhile to make some simple improvements: increase the text width from 81.5% to 85%, and add some space above the image; in the following screenshots, I used 2rem:
![Screen Shot incorporating small adjustments in Firefox desktop](https://user-images.githubusercontent.com/7144396/151479629-d761b118-4faa-4561-96fd-132d6bb55961.png)
![Screen Shot incorporating small adjustments on mobile](https://user-images.githubusercontent.com/7144396/151479686-f4e4e71d-7638-41af-a6da-738ed958bb4a.png)

**Comment by vivienlacourba** [comment]
@JuliaSang based on @gosko test and feedback I'm relabeling this ticket as a design issue to be addressed by Ian. I'm also assigning it to you so that it is on your radar at least until Ian accepts my GitHub invite.

**Comment by gosko** [comment]
Hi @NicolaSaunders @maries24 thanks for this update.

This seems to have introduced a new issue with the mobile view on the [www-staging home page](https://www-staging.w3.org/) as well as other pages like [the E-commerce ecosystem page](https://www-staging.w3.org/ecosystems/e-commerce/): the image at the top is now getting clipped instead of resized. Tested both in Firefox responsive design mode and in Chrome on my phone.

![Screen Shot 2022-02-10 at 8 45 11 AM](https://user-images.githubusercontent.com/7144396/153456239-7d219d75-7159-431b-9aca-078ab5994af4.png)

**Comment by maries24** [comment]
Hi @gosko That should be fixed now.
