### ISSUE TITLE
Staff page generated number not accurate when filtered

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#501]
**Describe the issue**
On the Staff page, when you filter for a Family name starts with, it changes the number of staff to the number with that last name. e.g. "The W3C Team includes **3** people working from locations across the globe. ... With a truly international flavor, the Team includes engineers from more than 10 different countries." :-)

**To reproduce**
https://www.w3.org/staff/?initial=m

**Expected behavior**
In this sentence, "The W3C Team includes 46 people working", the total number will stay the same regardless of what is filtered.

**Screenshots**
![image](https://github.com/w3c/w3c-website/assets/6991814/f489dc43-2d1d-4f6b-a3a7-aac9d68e2528)

**Comment by deniak** [comment]
Thanks for the report. This is now fixed.
