### ISSUE TITLE
Clearer instructions for sending feedback via email

### ISSUE THREAD

**Issue by simonrjones** [w3c/w3c-website#508]
**Describe the issue**
A suggestion after feedback from [Claudio Calvelli](https://lists.w3.org/Archives/Public/public-website-redesign/2023Sep/0000.html).

Some users are reporting difficulties submitting website issues via GitHub. This affects the "Give feedback" link in the beta bar on https://www.w3.org/ and most top-level pages on the site.

**Recommended solution**
One possible option is to link the give feedback link to a page on the w3.org site detailing where people can send feedback. This may be clearer than linking directly to GitHub.

Alternatively, I have also [suggested some rewording on the w3c-website README.md](https://github.com/w3c/w3c-website/pull/507).

**Comment by vivienlacourba** [comment]
Thanks @simonrjones for this suggestion and your PR that I merged. That clarifies the feedback process.
