### ISSUE TITLE
http://www.w3.org/standards/faq.html is gone, but used to explain the "W3C persistence policy"

### ISSUE THREAD

**Issue by Rob--W** [w3c/w3c-website#510]
I was looking for an explanation of the "W3C persistence policy", and a search engine pointed to http://www.w3.org/standards/faq.html#persistence

When I visited that URL, it however redirected to https://www.w3.org/standards/ , which looks like a marketing page without FAQ.

The original content can still be viewed at https://web.archive.org/web/20230601030704/https://www.w3.org/standards/faq.html#persistence

Can the content of the FAQ be restored? If it is already somewhere, can it at least be linked or become a redirect target?

**Comment by Darckorcha-Edu** [comment]
OK you have your agrement for a agent and more I need helps ( multiples) paypal first crypto second and education after help legal and more and more please I supplied you now

**Comment by marcosdodo** [comment]
Traducion

**Comment by japuiglaucia** [comment]
http://www.w3.org/standards/faq.html is gone, but used to explain the "W3C persistence policy" #510

**Comment by koalie** [comment]
Hi @Rob--W 

Thanks for flagging this!
It took me many months, but I was able to sit long enough with it that I moved back relevant entries from the previous FAQ into the "[About Standards](https://www.w3.org/standards/about/)" page which is one link away from the "[Standards](https://www.w3.org/standards/)" page that has more of the marketing high-level information.

In the case that you raised, here's the new link
https://www.w3.org/standards/about/#w3c-persistence-policy
