### ISSUE TITLE
WSG 1.0 - Example link not accessible without paying for account

### ISSUE THREAD

**Issue by CristellaH** [w3c/w3c-website#514]
**Describe the issue**
On the new Web Sustainability Guidelines (WSG) 1.0, exemple 11 is a link to Medium that is not accessible without paying for a membership.
W3C guidelines examples should be free

**URL**
2.11 Avoid Manipulative Patterns
https://w3c.github.io/sustyweb/#example-11 ==> https://uxdesign.cc/10-evil-types-of-dark-ux-patterns-f5a408c43c62

**Recommended solution**
Use another exemple that free to access

**Additional context**

**Comment by dontcallmedom** [comment]
Thank you for your report! 

This repository has been set up to collect feedback specifically on the redesigned W3C Web site. The issue you're reporting is about content created by an independent Community Group; please file this as an issue on their repository https://github.com/w3c/sustyweb/issues
