### ISSUE TITLE
Update the Twitter icon in the group page

### ISSUE THREAD

**Issue by xfq** [w3c/w3c-website#518]
**Describe the issue**

The Twitter icon in https://www.w3.org/groups/wg/i18n-core/tools/ needs to be updated to the new logo. The one at the bottom of the page has been updated, but not the one on the group page.

**To reproduce**

Visit https://www.w3.org/groups/wg/i18n-core/tools/

**Expected behavior**

Use the new "X" logo.

**Screenshots**

<img width="572" alt="twitter" src="https://github.com/w3c/w3c-website/assets/2863444/72e1aa6e-91a7-459e-920c-5d7376b1fff2">

**Additional context**

Maybe we can add Mastodon as well. The bottom of the page has it.

**Comment by deniak** [comment]
@xfq thanks for the report. It's now fixed.
