### ISSUE TITLE
Host error on the WAI page

### ISSUE THREAD

**Issue by JT-Creates** [w3c/w3c-website#519]
**Describe the issue**
https://www.w3.org/WAI/ times out.

**To reproduce**
go to the links that point to the WAI page of the W3C website

**Expected behavior**
Unknown.

**Screenshots**
![image](https://github.com/w3c/w3c-website/assets/84053338/bd473e82-bcc2-4dd4-827c-a67bf17570b2)

**Additional context**
Failed at M-enabling 2023 Sudio B

**Comment by vivienlacourba** [comment]
Thanks for your report.
Those timeout issues (which were note limited to only the /WAI area of the W3C website) have been resolved as of 12 October at 09:30 UTC.
See related incident https://status.w3.org/incidents/wksbpv339v5j
