### ISSUE TITLE
Group filter in Dashboard doesn't work

### ISSUE THREAD

**Issue by iadawn** [w3c/w3c-website#537]
Sorry if the admin section is not part of the CMS. Please do point me in the right direction if necessary.

Using the [Admin dashboard](https://www.w3.org/admin/)

* Select Invited Experts (open menu then select option)
* In Groups Filter type 'Accessibility'
* Only two groups show up:
<img width="407" alt="screenshot of two groups" src="https://github.com/w3c/w3c-website/assets/2444840/5e28f8d6-157e-4725-b484-ac74ea7d7824">

The are  other accessibility groups, including Accessible Platform Architectures Working Group , Accessibility Guidelines Working Group, but they don't show up.

It would be really handy of this filter worked.

**Comment by deniak** [comment]
@iadawn thanks for the report. It's now fixed.
