### ISSUE TITLE
Blog author's profile picture not present

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#542]
**Describe the issue**
The blog author's profile picture is not present at https://www.w3.org/blog/2023/w3c-virtual-workshop-on-secure-the-web-forward-26-28-september-2023/ although I checked and there is a [picture](https://www.w3.org/staff/?initial=d) for François, and other blog posts by the same author (and other authors when they have a profile picture) display the photo (see this [search result](https://www.w3.org/blog/?search=daoust)).

How can I edit or what can I do so that the profile picture is displayed?

**Comment by lcarcone** [comment]
The 'Author Email Address' was empty for this blog post, I added François' email address

**Comment by koalie** [comment]
DOH! and THANKS! I didn't even think to check in the back-end 🤦🏻‍♀️
