### ISSUE TITLE
/TR/xslt/: XSLT 1.0 to self instead of /TR/xslt-10/

### ISSUE THREAD

**Issue by lanodan** [w3c/w3c-website#555]
**Describe the issue**
Without guessing the URL ( <https://www.w3.org/TR/xslt-10/> ) or knowing it in advance it isn't possible to select the specification of "XSLT 1.0" from <https://www.w3.org/TR/xslt/>

**URL**
<https://www.w3.org/TR/xslt/>

**Comment by deniak** [comment]
Thank you for the feedback. This list has been fixed to link to /TR/xslt-10/ instead of /TR/xslt/.
