### ISSUE TITLE
I created account for w3c so I could join a community group I made an account confirmed email I read over documents to be on working group or team . I logged off but when I tried to log back in it says I have no account and when trying to create another it says I've already got an account need help getting back in

### ISSUE THREAD

**Issue by IGhottem** [w3c/w3c-website#557]
**Describe the issue**
A clear and concise description of what the issue is.

**To reproduce**
Steps to reproduce the behavior, including URLs. It's useful to include your web browser and version number to help 
review any potential browser issues.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vivienlacourba** [comment]
Hi @IGhottem

To resolve your W3C Account issue please send an email to the W3C Systems support list at sysreq@w3.org providing any relevant information such as your W3C account username, your full name, the email address you used and approximate period when you created that account.

I'll close this GitHub issue.
