### ISSUE TITLE
Bad link: https://www.w3.org/Consortium/siteindex.html

### ISSUE THREAD

**Issue by simon-grantham** [w3c/w3c-website#558]
The `[W3D Site Map]` [link](https://www.w3.org/Consortium/siteindex.html) provide here: `[W3C](https://www.w3.org/) »  [About W3C](https://www.w3.org/Consortium/) »  [Help and FAQ](https://www.w3.org/Help/) »  404 Not Found` is redirected to the home page.  Cannot get to a site map.

**Comment by koalie** [comment]
The site index, which was available in the previous version of the W3C Website, has been discontinued. It is replaced by the navigation menus.
