### ISSUE TITLE
Wrong Character on W3C Chinese Website

### ISSUE THREAD

**Issue by szw0407** [w3c/w3c-website#562]
**Describe the issue**
Login should be translated as 登录 instead of 登陆 on https://www.w3.org/zh-hans/

**Screenshots**
![image](https://github.com/w3c/w3c-website/assets/107471539/063de74d-7741-4efc-8177-81e91350c2e0)

**Comment by koalie** [comment]
A [fix for this was deployed on 2023-12-22](https://github.com/w3c/w3c-website-templates-bundle/pull/131#issuecomment-1867436250).
