### ISSUE TITLE
Missing role="img" attribute on the SVG images page

### ISSUE THREAD

**Issue by kenji-webdev** [w3c/w3c-website#574]
**Describe the issue**

The example doesn't show the `role="img"` in the `<img>` element, even though there's a paragraph below explaining why it's being used.
![image](https://github.com/w3c/w3c-website/assets/98567681/7ee5e37c-0453-49ab-b6cb-6b625b2a0149)

**URL**
[The URL where this problem occurs.](https://design-system.w3.org/styles/svg-images.html)

**Recommended solution**
Add the `role="img"` attribute to the example

**Comment by NicolaSaunders** [comment]
Fix for this issue is at https://github.com/w3c/w3c-website-templates-bundle/pull/146
