### ISSUE TITLE
Update Node version used for build tools to 16 (LTS)

### ISSUE THREAD

**Issue by simonrjones** [w3c/w3c-website#58]
**Describe the issue**
The [Template bundle repo](https://github.com/w3c/w3c-website-templates-bundle) is setup to use Node v11.10.0, which is no longer supported.

From W3C:

> Since last October, node.js 16 has become the active LTS and that's the version we are running on all our servers. Can you please look at upgrading that requirement? Note the GH action is taking about 3min to run mainly because it has to compile node 11. Using a stable version should speed up the run as it wouldn't have to compile node.

**Recommended solution**
Update Node to use LTS version (curently v16). Please note this will also require changes to build tools.

**Comment by vivienlacourba** [comment]
> [w3c/w3c-website-templates-bundle#53](https://github.com/w3c/w3c-website-templates-bundle/pull/53) should address the issue. Anyone up for reviewing this?

@maries24 agreed to review this.

**Comment by deniak** [comment]
https://github.com/w3c/w3c-website-templates-bundle/pull/53 was merged!
