### ISSUE TITLE
RSS Feed Validator Unavailable

### ISSUE THREAD

**Issue by conrmahr** [w3c/w3c-website#594]
**Describe the issue**
The W3 RSS Feed Validator is posting 503 errors on initial load.

**To reproduce**
Browse to [https://validator.w3.org/feed/](https://validator.w3.org/feed/)

**Expected behavior**
The validator to load.

**Screenshots**
![image](https://github.com/w3c/w3c-website/assets/363781/c3238509-2cf8-480d-a4c5-a27c280b2f24)

**Additional context**
RSS is not dead yet.

**Comment by conrmahr** [comment]
Looks like it's back up!

**Comment by conrmahr** [comment]
Looks like it's back up!

**Comment by koalie** [comment]
Yes, we fixed it a few hours ago! Thanks for reporting it in the first place.
