### ISSUE TITLE
Home page - 'World Wide Web Consortium' not spelled out

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#6]
I was surprised that the W3C acronym is not spelled out on the [prototype home page](https://w3c-dev.studio24.dev/home/index.html). Was that intended? Apologies if this is something that was already discussed and decided!

**Comment by JuliaSang** [comment]
Hi @gosko this is a content question, so will assign this one to @koalie to consider.

**Comment by koalie** [comment]
Fixed! (at long last!)
