### ISSUE TITLE
XML Validation with XSD blocked by Cloudflare as DOS attack

### ISSUE THREAD

**Issue by pgbrandolin** [w3c/w3c-website#601]
**Describe the issue**
I came across a IP block issue when I try to validate a set of electronic invoices with the XSD supplied by Italian Revenue Agency.
Is there a frequency limit of requests that can be forwarded to w3c urls? After experiencing the block I accessed one of the following URLs and I got a message by Cloudflare that my IP would be blocked for a while.

**URL**
I believe that the following element (extracted from the XSD) is related to the issue:
<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd" />

**Recommended solution**
A suggestion about a way to overcome this issue (request frequency limit? Caching?)

**Additional context**
Thank you

**Comment by CS270787** [comment]
J _mte
_

**Comment by gosko** [comment]
We currently allow 100 requests per minute for .xsd files. To avoid being rate-limited you might try reducing the frequency of your requests, or using an [XML Catalog](https://en.wikipedia.org/wiki/XML_catalog).

**Comment by Desmondpsg1976** [comment]
I'm sorry  I let them keep download to secure account  so now which one
should delete.
