### ISSUE TITLE
Improve the TOC component

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#610]
**Describe the issue**
The [TOC component](https://github.com/w3c/w3c-website-templates-bundle/blob/main/templates/components/styles/toc.html.twig) currently takes a `toc_content` block that can be easily overridden with something else that has nothing to do with a TOC.

**Recommended solution**
It would probably be better if it takes an array with a list of ids and use a specific markup so the TOC is consistent everywhere.

**Comment by cklim2024** [comment]
> **Describe the issue**
> The [TOC component](https://github.com/w3c/w3c-website-templates-bundle/blob/main/templates/components/styles/toc.html.twig) currently takes a `toc_content` block that can be easily overridden with something else that has nothing to do with a TOC.
> 
> **Recommended solution**
> It would probably be better if it takes an array with a list of ids and use a specific markup so the TOC is consistent everywhere.
>

**Comment by vivienlacourba** [comment]
@jean-gui will discuss this with @deniak

**Comment by deniak** [comment]
After discussing with @jean-gui, that issue is not specific to the TOC component. We have many components that are using blocks that can be misused.
Also, having a block allows to be flexible with lists that can have subitems so closing this issue for now.
