### ISSUE TITLE
Some examples are hosted on oaa-accessibility.org which redirects to a sketchy boredaf.app domain

### ISSUE THREAD

**Issue by blake-discover** [w3c/w3c-website#613]
**Describe the issue**
The ARIA Techniques document includes links to a `oaa-accessibility.org` domain which is suppose to be part of OpenAjax Alliance. However, all traffic to that domain is being redirected to `boredaf.app`.

**To reproduce**
Navigate to the ARIA5 section and click on one of the links to either of the [examples](https://www.w3.org/TR/WCAG20-TECHS/aria#:~:text=This%20button%20is%20available%20as%20part%20of%20the%20working%20example%20of%20Example%2038%20%2D%20Toolbar%20using%20inline%20images%20for%20visual%20state%2C%20on%20the%20OpenAjax%20Alliance%20site.)

Or visit the `oaa-accessibility.org` site directly: http://www.oaa-accessibility.org/examplep/toolbar1/

**Expected behavior**
Example links should go to a valid domain

**Screenshots**
n/a

**Additional context**
A quick ICANN lookup shows the `oaa-accessibility.org` domain was last updated on `2024-03-02 11:54:29 UTC`; I'm not sure how relevant that is though.

**Comment by daniel-montalvo** [comment]
Hi @blake-discover 

Thank you very much for bringing this to our attention. The 2.0 Techniques page is now fairly outdated. Updates to techniques are now been worked on at https://www.w3.org/TR/WCAG20-TECHS/aria
