### ISSUE TITLE
Cannot create account

### ISSUE THREAD

**Issue by lukertaylor** [w3c/w3c-website#616]
Whenever I try to submit the web form to create an account, I consistently receive the message 'This form has expired. Please submit it again'.

I am using Edge from a MacBook.

<img width="685" alt="image" src="https://github.com/w3c/w3c-website/assets/63965241/1915fd99-aeda-4e67-8c6a-081ad208dfe0">

**Comment by deniak** [comment]
Closing this issue for now. Feel free to re-open if the problem persists.
