### ISSUE TITLE
possible security issue with publicly available config directory

### ISSUE THREAD

**Issue by hersleyhs** [w3c/w3c-website#619]
**Describe the issue**
There is a possible security issue with publicly available config directory. I have not investigated if more are available but at least the config directory is.

**To reproduce**
got to the url: https://www.w3.org/config/

**Expected behavior**
I would expect to not get access by either a no access allowed error or be redirected to a other page

**Screenshots**
![image](https://github.com/w3c/w3c-website/assets/70904973/dca7cf0b-6f2e-4f03-86ed-135eb00d594f)

**Additional context**
when you google "_intitle:"index of" inurl:/config/_" this site is the first result.

**Comment by ChTalhaazhar** [comment]
chaudhary Muhammad talha

**Comment by gosko** [comment]
This is not a security issue. This directory is intended to be public.
