### ISSUE TITLE
XPath cover page link to 1.0 spec links to cover page instead

### ISSUE THREAD

**Issue by jaredkrinke** [w3c/w3c-website#621]
**Describe the issue**
On this page: https://www.w3.org/TR/xpath/

The "XML Path Language (XPath) Version 1.0" link goes to the cover page instead of the 1.0 version of the spec.

**URL**
https://www.w3.org/TR/xpath/

**Recommended solution**
Link should probably go to: https://www.w3.org/TR/xpath-10/

**Additional context**
None

**Comment by deniak** [comment]
Hi @jaredkrinke,

The XPATH TR link is one of the few exceptions we have as the WG decided to point that link to the cover page instead of redirecting to a specific version.
@caribouW3 may know more about the rationale for doing this.

**Comment by jaredkrinke** [comment]
Just to double-check that we're talking about the same thing, I'm talking about the link that is labeled "XML Path Language (XPath) Version 1.0" that is *on* the cover page. Instead of it linking to v1.0 of the spec, it juts circularly links to the cover page (the page that contains the link):

![image](https://github.com/w3c/w3c-website/assets/5257820/b1196566-e43f-421b-b5c8-deeb2fedf7c2)

As a user, I didn't see any way to actually get to the 1.0 spec from the cover page--I just ended up guessing the URL (based on the format of the links to other versions). Searching for the 1.0 spec also yields a link to the cover page. If this is indeed expected, I guess it's not clear to me how I can navigate to the 1.0 spec :)

**Comment by deniak** [comment]
@jaredkrinke sorry, I misunderstood the issue. Indeed, the link was wrong and it has been updated to point to the version 1.0.

Thank you for the report.
