### ISSUE TITLE
Policies document uses lowercase id="copyright" 

### ISSUE THREAD

**Issue by csarven** [w3c/w3c-website#622]
Minor issue (if you want to call it that):

The old reference to https://www.w3.org/Consortium/Legal/ipr-notice#Copyright now redirects to https://www.w3.org/policies/#Copyright (in the browser). Noting that the redirected document includes `id="copyright"` (lowercase "copyright").

This may well be intended going forward but I just wanted to flag it in case it needs any attention. Perhaps as part of other issues / tasks that take fragment identifiers on redirected into account.

See also:
* https://github.com/search?q=org%3Aw3c https%3A%2F%2Fwww.w3.org%2FConsortium%2FLegal%2Fipr-notice%23Copyright&type=code
* https://github.com/search?q=org%3Aw3c+https%3A%2F%2Fwww.w3.org%2Fpolicies%2F%23Copyright&type=code (shows lowercase use, which is good)

This issue may be better in another w3c repository but I couldn't identify one. Move/close issue as you see fit.

/cc @rigow

**Comment by gosko** [comment]
Fixed by adding a span with uppercase Copyright as existed on the old page. Thanks @csarven for the bug report and additional pointers.
