### ISSUE TITLE
How to manage affiliation change requests from the website?

### ISSUE THREAD

**Issue by jandrieu** [w3c/w3c-website#623]
**Describe the issue**
We hired a new employee who is trying to change his affiliation. Unfortunately, he initially did so with his existing account that does not have his company email. 

That triggered an email to me asking me to approve the employee with the incorrect email.

He has since added our company email to his profile at w3.org, but still cannot complete the affiliation change and I have not received any additional emails asking me to verify the affiliation. And, as I mentioned the original email has incorrect information.

Where on the website can I go to review outstanding affiliation requests?

**To reproduce**
Set an email on profile using domain not affiliated with a W3C member. Try to change affiliation to that member. Then add email that is affiliated with a W3C member (and make that the primary email). Then try to affiliate. That triggers a dual error message "An affiliation change request for this use has already been submitted"

**Expected behavior**
I expect either an automated approval because the employee has email from an domain associated with a W3C member, or at least a second verification email with the correct email listed for the employee.

An additional option would be to have the website list outstanding affiliation change requests so that one could review them independent of any email notifications.

**Screenshots**
![image](https://github.com/w3c/w3c-website/assets/186831/636e6eb1-682b-4604-b81d-15c54f03b0b6)

**Additional context**
The employee was a member under a different organization previously.

**Comment by vivienlacourba** [comment]
> We just fixed an issue with the sending of emails that started today at around 12:20 UTC.
> Kevin should have in his mailbox an email to validate his new email address.

I see that Kevin was able to validate his new email address so I'm closing that ticket.
