### ISSUE TITLE
Code Snippet Missing Closing "

### ISSUE THREAD

**Issue by eeellliii1** [w3c/w3c-website#633]
**Describe the issue**
"Example 3: Newspaper Web site" is missing a closing " for the href: `<a href="Stockmarket_05052007.htm>Stock market soars as bullishness prevails</a>`. This prevents the html from properly displaying if pasted into a compiler. This is also the case for the href `<a href="Stockmarket_05052007.htm>More here</a>`.

**URL**
https://onecompiler.com/html/42htarrxc

**Recommended solution**
Add a " to the hrefs, making them: `<a href="Stockmarket_05052007.htm">` and `<a href="Stockmarket_05052007.htm">.` 

**Additional context**
This is my first time reporting an issue, sorry if I did not format this correctly or this is an irrelevant nitpick!

**Comment by koalie** [comment]
This isn't an issue which belongs to our website.
