### ISSUE TITLE
What does "Indivcla" mean when joining as individual to community groups?

### ISSUE THREAD

**Issue by renyuneyun** [w3c/w3c-website#636]
**Describe the issue**
When joining a W3C Community Group, I see the last item is "Indivcla (Required)" (see figure below). However, that does not seem to be a word based on online search. Could anyone explain what it means, and/or if it is a typo?

In principle, I believe we are not expected to agree to something we have no ideas of, right?

**To reproduce**

When joining any community group (e.g. [Solid Community Group](https://www.w3.org/community/solid/), [Notation 3 Community Group](https://www.w3.org/community/n3-dev/)), and look at the "individual" half, it is always there.

**Expected behavior**

A clear and concise description of what this actually means.

**Screenshots**.
![图片](https://github.com/w3c/w3c-website/assets/3293723/827c9615-b127-435b-8cbd-08990707a232)

**Additional context**

Based on the other half of the information (joining on behalf of an organization) and the context, I believe this checkbox roughly means "I agree to ...", but have no idea what the thing to agree to is.

**Comment by deniak** [comment]
@renyuneyun thanks for the report. Indeed, there's an issue with the label of that checkbox. It should be 'Individual CLA (contributor License Agreement)'.

We will fix the label

**Comment by renyuneyun** [comment]
Thanks for the quick reply! That's very helpful.

**Comment by deniak** [comment]
The label has been updated. Thanks again for reporting the issue.
