### ISSUE TITLE
Update terminology business ecosytem template/page 

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#638]
**Describe the issue**
Our colleague @swickr suggested to rephrase one bit that is part of the business ecosystem pages' component "component--members__grid":
Instead of "View all members of the XYZ ecosystem", please rewrite everywhere as "View all members participating in the XYZ ecosystem".

**URL**
https://design-system.w3.org/templates/business-ecosystem.html for the template, and each existing ecosystem pages:
https://www.w3.org/ecosystems/e-commerce/
https://www.w3.org/ecosystems/media/
https://www.w3.org/ecosystems/publishing/
https://www.w3.org/ecosystems/network-communications/
https://www.w3.org/ecosystems/data/
https://www.w3.org/ecosystems/web-of-things/ and
https://www.w3.org/ecosystems/advertising/

**Comment by jean-gui** [comment]
Done for the English version. I have asked our translators to update the Japanese and Chinese ones.
