### ISSUE TITLE
Missing css rule for the attribute/value scope='colgroup'

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#639]
The file https://www.w3.org/assets/website-2021/styles/core.css contains the following rule:
th[scope=col] {
  background-color: #024488;
  color: #fff;
}

We have some pages that also use the value 'colgroup' to specify that a group of columns is a header and they are rendered differently.

Could we add the value 'colgroup' to the rule above ?

**Comment by vivienlacourba** [comment]
Relates to #648

**Comment by vivienlacourba** [comment]
This should not be necessary if the change suggested in #648 is implemented.

**Comment by vivienlacourba** [comment]
Change in #648 was implemented which make this proposed update not needed anymore.
