### ISSUE TITLE
Update class names in access control banner docs

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#649]
The [Access Control Banner component](https://design-system.w3.org/components/access-control-banner.html) in the design system docs says to use `access-control-banner--member` for member-only pages, but that class does not exist in the CSS.

I believe those classes should be updated to match the classes used in the HTML example lower on the page: `banner--access-control acl-member`

**Comment by NicolaSaunders** [comment]
Proposed solution is at https://github.com/w3c/w3c-website-templates-bundle/pull/154
