### ISSUE TITLE
How to deal with favicon?

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#650]
**Describe the issue**
Nowadays, browsers systematically try to fetch a favicon when loading pages. If no icon link tag is provided (see below), then the browser try to look for one at the root of the website which may result in a 404 if it doesn't exists (might be the case for some sub domains).

```html
<link rel="shortcut icon" href="https://www.w3.org/favicon.ico">
```

The different templates in the design system don't include that icon link but it's probably good to add it even if the favicon exists at the root of w3.org. So even if the template is used outside www.w3.org (github.io, different subdomain, etc), we would still have the good W3C favicon.

**Comment by vivienlacourba** [comment]
A concrete example is the authentication portal which uses the new W3C style but at a different domain https://auth.w3.org/

@simonrjones any specific recommendation for favicon or can we simply add the above line to the website template?

**Comment by simonrjones** [comment]
hi @vivienlacourba yes I agree that is worth adding. The example HTML added by @deniak looks perfect to me. 

If possible, can you add an icon for Apple, iOS uses a custom link rel type. Example:

`<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">`

**Comment by vivienlacourba** [comment]
Assigning to @deniak for implementation.
