### ISSUE TITLE
add reports to the Reports page

### ISSUE THREAD

**Issue by shawna-slh** [w3c/w3c-website#651]
**Describe the issue**
Reports page missing reports.

**URL**
[https://www.w3.org/reports/](https://www.w3.org/reports/)

**Recommended solution**
Add relevant reports, e.g.,
* Diversity report 2024
* https://www.w3.org/reports/ai-web-impact/

<br>

_(FYI @tamsinewing555 here's where I filed the issue)_

**Comment by koalie** [comment]
hah! we had put the Diversity report of 2023 and the Strategic Highlights doc of 2022 as fodder so the page would not include just the AI and the Web report which was available at the creation of the report listing page.

The nature of the report listing is to curate documents that "identify future exploration, or to propose ideas for consideration"

As such, I removed the diversity report and strategic highlights doc ruled as out of scope. I added the identity report we published a week or so ago, however. Thanks for the reminder!
