### ISSUE TITLE
Typo in Button Text on W3C Careers Fellows Page

### ISSUE THREAD

**Issue by yashrajbharti** [w3c/w3c-website#659]
**Describe the issue**
There is a typo on the page [W3C Careers Fellows](https://www.w3.org/careers/fellows/). The text on a button reads: `Check is your employer is a W3C member.` The correct text should be `Check if your employer is a W3C member.`

**URL**
[https://www.w3.org/careers/fellows/](https://www.w3.org/careers/fellows/)

**Recommended solution**
Update the button text from "Check __is__ your employer is a W3C member" to "Check __if__ your employer is a W3C member."

**Additional context**
I’ve attached a screenshot highlighting the typo for reference.
  
![Screenshot 2024-09-09 at 8 36 06 AM](https://github.com/user-attachments/assets/80e2d079-feb0-4b78-bee0-b171ac782833)

**Comment by vivienlacourba** [comment]
Fixed. Thanks for your report.
