### ISSUE TITLE
Link to Process and Bylaws from w3.org/about

### ISSUE THREAD

**Issue by fantasai** [w3c/w3c-website#660]
**Describe the issue**
There's  no link to the Bylaws from w3.org/about currently.

**URL**
https://www.w3.org/about/

**Recommended solution**
My suggestion is to just link the words "Process" and "Bylaws" in the final paragraph to their respective documents.

**Additional context**
I'm unsure where the Bylaws live; I believe mmot has an HTML version that we could use?

**Comment by koalie** [comment]
> **Additional context**
> I'm unsure where the Bylaws live;

They live in https://www.w3.org/about/corporation/#documents-of-the-corporation 

That said, I'll add the links as recommended above.

**Comment by koalie** [comment]
There was already links to the Process and Patent Policy in the about page, but I added them again in the earlier section, after the quote from Tim. 
I added a pointer to the Corporation public page on the word "bylaws".
