### ISSUE TITLE
Broken links in DID specification: Decentralized Identifier Extensions

### ISSUE THREAD

**Issue by PeterWaher** [w3c/w3c-website#661]
**Describe the issue**
All thee links provided in the DID specification: Decentralized Identifier Extensions, §3, are broken.

**URL**
<https://www.w3.org/TR/did-spec-registries/#extensions>

**Recommended solution**
Correct links, or create corresponding (placeholder) pages.

**Additional context**
N/A

**Comment by koalie** [comment]
@deniak could you check if this is a mistake we can fix or if this issue needs to be transferred over to https://github.com/w3c/did-extensions/issues for the group / editor to fix? Thanks!

**Comment by deniak** [comment]
There's a related open issue on the ED repo: https://github.com/w3c/did-extensions/issues/575
