### ISSUE TITLE
Excessive ads in site search

### ISSUE THREAD

**Issue by jyasskin** [w3c/w3c-website#663]
**Describe the issue**

I searched for 'aria' on the w3c site, and got the following results page:

![DuckDuckGo search results page for "site:w3.org aria" with 3 ads and no correct result on the first page](https://github.com/user-attachments/assets/4fec6dce-d34b-4bc4-a442-2fc6af2ff7e4)

**To reproduce**

Visit https://www.w3.org/aria, enter "aria" in the resulting search box, and press 'enter'. The results you get seem to depend on your history and maybe your IP address's location.

**Expected behavior**

The correct result should appear in the first half of the first screen. If you're paying for this, it should appear first.

**Comment by gosko** [comment]
Should be fixed. This was only an issue on our legacy site style (as used on the 404 page, sometimes), which will hopefully be going away soon.
