### ISSUE TITLE
Unescaped closing body element in forms documentation

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#664]
The [forms page of the design system documentation](https://design-system.w3.org/styles/forms.html) has an unescaped `</body>` in the considerations section of the auto-complete docs:

> `<p>In practice, add the following script before the closing body tag </body> for the auto-complete to work correctly:</p>`

![screenshot of firefox view source view](https://github.com/user-attachments/assets/503c632f-2234-4295-b5a7-294f25f960ff)

**Comment by NicolaSaunders** [comment]
Fix for this is at https://github.com/w3c/w3c-website-templates-bundle/pull/147

**Comment by NicolaSaunders** [comment]
I can still see this issue present on the [live Design System site](https://design-system.w3.org/styles/forms.html#considerations-2). Does it need a separate deployment or is there a caching issue?
