### ISSUE TITLE
Language options order

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#667]
**Describe the issue**
The list of language options is inconsistent across the different places.
The templates in the design system show "Japanese" and then "Chinese" whereas www.w3.org lists "Chinese" and "Japanese".

Design system:

<img width="1152" alt="Screenshot 2024-09-27 at 12 02 48" src="https://github.com/user-attachments/assets/e598095c-2b70-4484-be2f-d94bb87e5472">

Main website:

<img width="1178" alt="Screenshot 2024-09-27 at 12 03 45" src="https://github.com/user-attachments/assets/5bd7f80c-92fb-4b02-a26a-8ac8754635d2">

**URL**

[Design system basic template](https://design-system.w3.org/code/basic-page.html) vs. [main website](https://www.w3.org/)

**Recommended solution**
Use specific language options order in the `lang-nav` bar.

**Comment by vivienlacourba** [comment]
Assigning to @jean-gui.
I believe they should be ordered by language code with English always being the first entry as it is the main site. Hopefully the CMS already does the right thing and the only place to fix is the design system.

**Comment by vivienlacourba** [comment]
Fixed by PR #152
