### ISSUE TITLE
I'm not receiving calls or text messages via web. 

### ISSUE THREAD

**Issue by Jayother24** [w3c/w3c-website#668]
**Describe the issue**
A clear and concise description of what the problem is.

**URL**
The URL where this problem occurs.
Chrome status has done all type of format changes, and now none of my web messages calls or texts are coming through. I do not appreciate this at all. Please fix
![Screenshot_20240929-162132](https://github.com/user-attachments/assets/af0dab19-aaf1-4988-a297-86f8a07c1b55)

**Recommended solution**
A clear description of how you think the content should be updated.

**Additional context**

"STABLE
Chrome 129
Beta was Aug 21 - Sep 5
Stable 3 weeks ago (Sep 11, 2024) 
FEATURES IN THIS RELEASE:
Deprecated
Deprecate 0.0.0.0 for Private Network Access
Enabled by default
Blob support in WebRTC data channels
Compute Pressure WebDriver extension commands
CSS Anchor Positioning: Unwrapped inset-area()
CSS interpolate-size property and calc-size() function
Intl.DurationFormat
Private Aggregation API: client-side contribution merging
Remove PointerEvent.getCoalescedEvents() from insecure contexts
Rename inset-area to position-area
scheduler.yield()
Snap Events
Update CSS backdrop-filter to use mirror edgeMode
Web Authentication API: JSON serialization methods
WebGPU extended range (HDR) support
In developer trial (Behind a flag)
Deprecate 0.0.0.0 for Private Network Access
Deprecation of CSS Anchor Positioning property `inset-area`
Full and unprefixed box-decoration-break support
Language Detector API
meter element fallback styles
relaunch Intl Locale Info feature in newly added functions
Rename inset-area to position-area
Rewriter API
Summarizer API
Transferable RTCDataChannel to dedicated workers
WebGPU: Dual source blending
Writer API
Origin trial
FileSystemObserver interface
Incorporating navigation initiator into the HTTP cache partition key
Mesh2D Canvas API
Removed
Deprecate the includeShadowRoots argument on DOMParser
Deprecation of non-standard declarative shadow DOM serialization"

**Comment by koalie** [comment]
This isn't related to the W3C website, nor W3C.
