### ISSUE TITLE
The table of content component shouldn't need the clean-list class

### ISSUE THREAD

**Issue by deniak** [w3c/w3c-website#669]
**Describe the issue**

Trying to use the table of content component in a context where we don't have full control of the markup (markdown conversion), we noticed the [example](https://design-system.w3.org/components/toc.html) suggests we need to use the `clean-list` class to remove the list markers. However, this only relies on the fact that the [`ul` has a class](https://github.com/w3c/w3c-website-templates-bundle/blob/main/assets-src/styles/sass/30-base/_lists.scss#L9) whatever its name is.

Now, the `clean-list` class comes handy when you start dealing with sub-list, e.g.

```html
<nav class="toc" aria-labelledby="toc-label">
	<h2 id="toc-label">Page contents</h2>
	<ul>
		<li><a href="#link-to-anchor-1">First heading</a></li>
		<li><a href="#link-to-anchor-2">Second heading</a>
		  <ul>
		    <li><a href="#link-to-anchor-2">First subheading</a></li>
		    <li><a href="#link-to-anchor-2">Second subheading</a></li>
		  </ul>
		</li>
		<li><a href="#link-to-anchor-3">Third heading</a></li>
	</ul>
</nav>
```

If we don't use that `clean-list` class, the sub list shows the markers (see screenshot below).

<img width="265" alt="Screenshot 2024-10-04 at 14 16 27" src="https://github.com/user-attachments/assets/427f1ea5-17ba-46af-977e-48dae71fe867">

**Recommended solution**

To simplify the component so we can use it where we cannot add additional classes to the markup, it would be good to remove the dependency to the `clean-list` class.
Adding a `list-style: none` to the [toc component](https://github.com/w3c/w3c-website-templates-bundle/blob/main/assets-src/styles/sass/50-core-components/_toc.scss#L18) should solve the issue.

A side effect of removing the class from the `ul` is that it creates [additional top-margin](https://github.com/w3c/w3c-website-templates-bundle/blob/main/assets-src/styles/sass/30-base/_lists.scss#L24) on each item of a list that can be quite long. I'm tempted to also remove the top margin but this may cause other problems.

**Comment by deniak** [comment]
Here's a suggestion of what might work well when we have a sub list.

<img width="389" alt="Screenshot 2024-10-07 at 10 32 19" src="https://github.com/user-attachments/assets/e3f3d9b8-8373-4519-9a98-5c51a57d8645">

Summary the changes:
* decrease the line height for each item to 1.0
* `margin-left: 2em; list-style: circle; border-left: none;` to each sub items
* removing top/bottom margin

**Comment by NicolaSaunders** [comment]
Thanks for raising this @deniak 

There is a partial cross over with [issue #671](https://github.com/w3c/w3c-website/issues/671) and the proposed solution, which I am currently working on. I will need to add some custom styles for sublists to restore bullets and spacing.

**Comment by vivienlacourba** [comment]
> There is a partial cross over with [issue #671](https://github.com/w3c/w3c-website/issues/671) and the proposed solution, which I am currently working on. I will need to add some custom styles for sublists to restore bullets and spacing.

@NicolaSaunders, as @deniak mentioned please note that this issue popped-up in a context where we don't have full control of the produced markup (the markup is automatically produced by the jekyll-toc plugin and possible customization is quite limited).
So in the context of a TOC navigation menu all styling should rely on the presence of the parent `<nav class="toc">` without requiring individual TOC entries to have specific classes.

**Comment by NicolaSaunders** [comment]
Proposed solution for this issue and [issue #671](https://github.com/w3c/w3c-website/issues/671) is at https://github.com/w3c/w3c-website-templates-bundle/pull/150
