### ISSUE TITLE
On localized site the "Laest news" entries text is in English

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#672]
On the localized versions of the W3C homepage the "Latest news" section is displaying item titles and content in English (while the links on those items are correctly pointing to the localized version)

This issue might also exists for the "Recent activities" component on the ecosystem pages which are not yet localized:
e.g. https://www.w3.org/ecosystems/media/

Screenshot of the issue on the Japanese homepage:
https://www.w3.org/ja/ 

![image](https://github.com/user-attachments/assets/a02ead48-b95f-4280-ae9e-e86a2049ad19)

**Comment by jean-gui** [comment]
Fixed, see https://www.w3.org/ja/ and https://www.w3.org/zh-hans/
