### ISSUE TITLE
[Frontend & CraftCMS] Clear cache for a single page URL

### ISSUE THREAD

**Issue by maries24** [w3c/w3c-website#75]
Use case:

User updates page in CraftCMS

We want this to clear the cache on the frontend

Varnish does this via purge requests, we may be able to use a Craft plugin for thisa

Frontend data layer needs to clear cache by URL (e.g. any cached data from APIs)

See https://3.basecamp.com/3091560/buckets/15695452/messages/4279351514

**Comment by vivienlacourba** [comment]
This was completed by @simonrjones
