### ISSUE TITLE
Update GraphQL tokens on staging

### ISSUE THREAD

**Issue by maries24** [w3c/w3c-website#76]
Hi @jean-gui  and @AlanJIsaacson  

I was trying to update the GraphQL tokens on staging (so they would be different than on dev). But somehow I can’t find the corresponding environment variable in the .env file on the server.

Am I missing something?

Thanks!

**Comment by jean-gui** [comment]
CRAFTCMS_API_READ_TOKEN and CRAFTCMS_API_PUBLISH_TOKEN are defined in .env.local

**Comment by maries24** [comment]
Thanks @jean-gui

**Comment by maries24** [comment]
Done and tested
