### ISSUE TITLE
Evangelists component (copy)

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#77]
**Describe the issue**
In case there is a single evangelist for a given business ecosystem, the existing copy ("Our $ecosystem Evangelists") doesn't work so well because it uses the plural.

**To reproduce**
See for example on the E-Commerce page, near the bottom of https://www-staging.w3.org/ecosystems/e-commerce/

**Expected behavior**
Could it say instead "From our Evangelists team:"?

**Additional context**
Evangelists are expected to fill the "job title" field of their W3C Profile with the ecosystem(s) they operate in, and the geography. So removing the hard-coded ecosystem from the copy isn't too bad.

Thanks!

**Comment by vivienlacourba** [comment]
> In case there is a single evangelist for a given business ecosystem, the existing copy ("Our $ecosystem Evangelists") doesn't work so well because it uses the plural.

@koalie, as discussed yesterday, if there is only one evangelist it is easy to use singular here and use e.g. "Our E-commerce Evangelist" instead of "Our E-commerce Evangelists".

**Comment by jean-gui** [comment]
The sentence is now correctly pluralized.
