### ISSUE TITLE
Order in which "active groups" are displayed

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#78]
**Describe the issue**
The "active groups" component for business ecosystem landing pages lists the groups according to the wrong hierarchy (possibly sorted alphabetically?)

**Examples**
[Automotive ecosystem landing page](https://www-staging.w3.org/ecosystems/automotive-transportation/)
[E-commerce ecosystem landing page](https://www-staging.w3.org/ecosystems/e-commerce/)

**Recommended solution**
The nested groups should start first with any Working Group, then Interest Group, and lastly Business Group and Community Group.

**Comment by vivienlacourba** [comment]
So first ordering should be by group type then by name.
