### ISSUE TITLE
Global header - Keyboard navigation and links to the homepage

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#8]
_Example: https://w3c-dev.studio24.dev/default/index.html_

While testing keyboard navigation I noticed that in the header there are 2 links pointing to the homepage:
- One on the W3C logo
- One in the navigation breadcrumb on the `Home` root entry

In order not to iterate on 2 identical links, should one of those links have a `tabindex="-1"`?

**Comment by NicolaSaunders** [comment]
Hi @vivienlacourba - I don't believe this is an issue because the two links to home sit within separate `nav` elements, which act as landmark navigation for keyboard users. Users don't have to tab through every link, they can choose to skip over the breadcrumb navigation.

**Comment by vivienlacourba** [comment]
Ok @NicolaSaunders, it was really a question, so as you don't believe that this is an issue, I'm happy to close this issue.
