### ISSUE TITLE
E-Commerce ecosystem page review

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#82]
@koalie started to work on: https://www-staging.w3.org/ecosystems/e-commerce/

She wondered if the following had been implemented:
- If there is no evangelists, a default generic busdev contact should be displayed

Small things to fix:
- In featured Members "43 member organisations" s/organisations/organizations/
- For evangelists when it exists their @w3.org should be displayed even if that is not their primary (Paul Rodgers displayed email his currently his primary email address which is paul.rodgers@vendorcom.com)

**Comment by vivienlacourba** [comment]
> If there is no evangelists, a default generic busdev contact should be displayed.

@koalie can you indicate which info should be displayed? and whether it should be a group contact (e.g. "W3C Membership Team") or a given person (e.g. "Alan Bird" as busdev lead).

**Comment by koalie** [comment]
> @koalie can you indicate which info should be displayed? and whether it should be a group contact (e.g. "W3C Membership Team") or a given person (e.g. "Alan Bird" as busdev lead).

Alan Bird as busdev lead. Displaying similar to Evangelists, if possible.
(Via Alan:  "If no Evangelist exists just point them to me and I'll sort things out as they come in.")

Thanks!

**Comment by koalie** [comment]
> * For evangelists when it exists their @w3.org should be displayed even if that is not their primary (Paul Rodgers displayed email his currently his primary email address which is [paul.rodgers@vendorcom.com](mailto:paul.rodgers@vendorcom.com))

I've [drawn our attention](https://lists.w3.org/Archives/Team/team-website-redesign/2021Dec/0004.html) to that fact that Evangelists then should *use* their @w3.org email.

**Comment by jean-gui** [comment]
2nd and 3rd bullets done

**Comment by jean-gui** [comment]
1st bullet also done. It displays bizdev lead info (without phone number) if there's no evangelists.
