### ISSUE TITLE
Ecosystem testimonial content type review

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#83]
With @koalie we noticed that [the ecosystem testimonials](https://cms-dev.w3.org/admin/entries/testimonial) included `()` in their entry name even when they had all their fields set.

What do those parenthesis mean?

Also when [creating a new ecosystem testimonial](https://cms-dev.w3.org/admin/entries/testimonial/13260?site=default&draftId=582&fresh=1) none of the fields appear to be mandatory allowing to create a totally empty entry.

I think the following info should be required (see related section in the [Specification document](https://docs.google.com/document/d/1NRXvIO4kDs2leAFVF-zqJxNKGMbrRDL3MaQDOjp4WHI/edit#bookmark=id.slfc1gghao5g)):
- Ecosystem
- Author Name
- Quote for carousel

For the "Quote for carousel" description text:
> **Quote for carousel**
> Shorter version of the quote that can be used in a testimonial carousel. (In that context, quote have a character limit of 180 to comfortably fit in a small screen).

I suggest removing the prefix "Shorter version of the ", as there is only one quote here.

**Comment by vivienlacourba** [comment]
To get rid of the empty `()` see: https://craftcms.com/docs/3.x/entries.html#dynamic-entry-titles

**Comment by jean-gui** [comment]
This will be fixed when we switch to Craft 4, see https://github.com/w3c/w3c-website-craft/pull/27
