### ISSUE TITLE
Change content propagation method to 'Let each entry choose which sites it should be saved to'

### ISSUE THREAD

**Issue by maries24** [w3c/w3c-website#84]
When importing blog posts, entries are saved in all languages as opposed to only in English.

This must be due to the section’s [“Propagation Method” setting](https://craftcms.com/docs/3.x/sites.html#propagating-entries-across-all-enabled-sites).
Recommended this is set to  “Let each entry choose which sites it should be saved to”.

**Comment by maries24** [comment]
Hi @vivienlacourba,

The propagation method was already set to 'Let each entry choose which sites it should be saved to' for each content types.
So that's not the issue. I have set the default status of entries to 'Disabled' for all languages except English in case that helps. 

Will message the Craft team as well.

**Comment by maries24** [comment]
So moved to done but not closing the issue yet.

**Comment by vivienlacourba** [comment]
This was actually due to a bug in the Feed Me plugin https://github.com/craftcms/feed-me/issues/1084
It got addressed after I pinged the Craft team.
