### ISSUE TITLE
meta generator element uses incorrect attribute

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#86]
**Describe the issue**
The pages on the [design system site](https://design-system.w3.org/) include this markup:

`<meta name="generator" value="https://github.com/studio24/design-system">`

The `value=` attribute should be `content=`

**URL**
https://design-system.w3.org/ and all subpages

**Recommended solution**
Replace `value` with `content` in [one-col.twig](https://github.com/studio24/design-system/blob/main/templates/layouts/one-col.html.twig) and [two-col.twig](https://github.com/studio24/design-system/blob/main/templates/layouts/two-col.html.twig)

**Additional context**
n/a

**Comment by simonrjones** [comment]
Fixed in design-system repo, and updated in the w3c-website-templates-bundle repo. 

Prod design system site updated at https://design-system.w3.org/
