### ISSUE TITLE
blockquotes are not styled as blockquotes by default

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#87]
_(Links updated to point to beta site)_

**Describe the issue**
Blockquote elements are not styled as blockquotes by default: they lack indentation or other markers to indicate the text is quoted.

**URL**
https://beta.w3.org/blog/2008/email-address-obfuscation/

This page has a number of blockquote elements that are not styled correctly: one in the body of the post and some in a comment. For example in [this comment](https://beta.w3.org/blog/2008/email-address-obfuscation/#comment-80978) it isn't clear which text is quoted and which is original.

![screenshot of a comment including blockquotes](https://user-images.githubusercontent.com/7144396/145112991-21748944-a41c-4096-8bc7-ac1301e6f6e8.png)

(this page also has several other unrelated issues because the blog content importing is still a work in progress. Also I think access is restricted to specific IP addresses – not sure who currently has access to it)

The following simple test markup demonstrates the issue as well, including an unexpected difference in font style depending whether the blockquote has p elements inside it:
```
<p>Test paragraph.</p>
<blockquote>Test blockquote.</blockquote>
<p>Test paragraph.</p>
<blockquote>
<p>Test blockquote with p element inside.</p>
<p>Another paragraph inside the same blockquote element.</p>
</blockquote>
<p>Test paragraph.</p>
```

![screenshot of test markup](https://user-images.githubusercontent.com/7144396/145113839-b90755ed-e3c8-4102-99ee-134c052fd747.png)

I expect this is happening because most of the styling is done on the `figure` element in the [Quote component](https://design-system.w3.org/components/quote.html) but I believe it's important for blockquotes to be styled as blockquotes whether they are used a part of the Quote component or not.

**Recommended solution**
Update the styling of `blockquote`s so they always appear as blockquotes, for example by adding a margin and/or a bar or other quote markers (but simply adding a margin would be a huge improvement)

**Comment by lcarcone** [comment]
+1 to have a consistent way to style blockquotes by default

We have a lot a imported content that contain blockquotes with and without paragraph inside ( sometimes both cases in the same post like https://www-staging.w3.org/blog/2020/css-x/ ) and it is difficult to figure out there are blockquotes.

**Comment by NicolaSaunders** [comment]
This is a very good point. Adjusting the Sass at `/assets-src/styles/sass/30-base/_quotes.scss` as follows should help:

```
blockquote {

	@include txt-saturn;

	@include stack(1rem);

        padding: 0 rem(40);
        quotes: auto;

	> * {

		font-weight: bold;

	}

        p:first-child:before {

	        content: open-quote;

        }

        p:last-of-type:after {

	        content: close-quote;

        }

	cite {

		font-size: 1rem;
		font-style: normal;
		font-weight: normal;

	}

}
```

We should probably negate some of these styles for a `blockquote` used within the quote component, by adjusting the Sass at `/assets-src/styles/sass/50-core-components/_quotes.scss` as follows:

```
.component--quote {

	@include stack(1rem);

	margin-inline-start: rem(10);
	padding: rem(20);
	position: relative;

	&::before {

		background-color: $w3c-blue;
		border-radius: rem(5);
		content: '';
		height: 100%;
		left: rem(-10);
		position: absolute;
		top: 0;
		width: rem(10);

	}

	> * {
		max-width: rem(630);
	}

	blockquote {

	        color: $w3c-blue;
                padding: 0;
                quotes: none;

	}

}
```

**Comment by NicolaSaunders** [comment]
My proposed solution to this can be found in the branch [hotfix/#87-blockquotes](https://github.com/w3c/w3c-website-templates-bundle/tree/hotfix/%2387-blockquotes).

This implements the CSS changes suggested in my earlier comment.

**Comment by deniak** [comment]
Fixed by https://github.com/w3c/w3c-website-templates-bundle/pull/101

**Comment by gosko** [comment]
I appreciate the update but I don't think generic blockquotes should be displayed like [pull quotes](https://en.wikipedia.org/wiki/Pull_quote). The result seems a bit out of place for simple quoted text:

<img width="752" alt="screenshot of text alternating with quoted text" src="https://github.com/w3c/w3c-website/assets/7144396/6283c77d-ac31-4a2e-9e03-53859ea5d723">

I think blockquotes should have a simpler display by default:

<img width="748" alt="screenshot of simplified text alternating with quoted text" src="https://github.com/w3c/w3c-website/assets/7144396/13ac9783-a2cb-470f-acd9-a539d7df32c7">

And in the cases where we want a quote to appear like a pull quote, we should use the [Quote component](https://design-system.w3.org/components/quote.html).

**Comment by deniak** [comment]
@gosko I just merged @NicolaSaunders's fix. `blockquote` should now appear as you suggested.

**Comment by gosko** [comment]
Excellent! Thanks very much @NicolaSaunders and @deniak
