### ISSUE TITLE
Display blog comments in chronological order

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#88]
**Describe the issue**
Blog comments are currently displayed in reverse chronological order, which is confusing with threaded comments:

- Comment A - posted Dec 1
  - Comment C (replying to B) - posted Dec 5
  - Comment B (replying to A) - posted Dec 3
 
**To reproduce**
For example, [this comment thread](https://www-dev.w3.org/blog/2008/email-address-obfuscation/#comment-13205)

**Expected behavior**
Display comments in chronological order as done on our current blogs.

**Comment by jean-gui** [comment]
Done.
