### ISSUE TITLE
Commenting on blog post returns user to the wrong section of the page

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#89]
**Describe the issue**
When I post a comment on a blog, following successful post the browser returns me to the 'Post a new comment' section of the page without any indication about what happened.

**To reproduce**

- Browse to [this link](https://www-dev.w3.org/blog/2008/email-address-obfuscation/#respond)
- Enter a comment (fill in Comment, Name, Email address, click 'Post comment')
- Wonder what happened to your comment

If you then scroll to the top of the page, there is a box at the top that says 'Success / Your comment has successfully been saved and will be moderated before becoming visible. Back to comments'

But by default it returns you to the #respond fragment which leaves you at the bottom of the page.

Tested in the latest stable Firefox and Chrome on OS X.

**Expected behavior**
I expected posting the form to return an indication whether my comment was received.

**Comment by vivienlacourba** [comment]
@jean-gui, can a success message be added after the submission of a comment?

**Comment by gosko** [comment]
The success message is there, it's just hidden due to the scroll position.

**Comment by jean-gui** [comment]
Fixed. You should now be brought to the top of the page after submitting a comment
