### ISSUE TITLE
Alert messages

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-website#9]
https://w3c-dev.studio24.dev/form-errors.html shows a box at the top containing all errors messages as a list.
Does this box allow any markup inside, and does it style it properly? It seems that a paragraph will simply be black, hinting that there is indeed no special styling for elements other than lists.

We also use alert boxes to display messages other than errors: success (green), warning (yellow) and informational (blue) messages. Does this component support those other kinds of messages? Or is there another component for these?

Example success message using the main website template:
![success](https://user-images.githubusercontent.com/1479073/125984969-d84475a3-0dc1-4c87-8d45-eea9d9c29a05.png)

Example warning using the main website template:
![warning](https://user-images.githubusercontent.com/1479073/125984970-05e0e54f-677e-419b-8022-8c164cda7f02.png)

Example informational message using the bootstrap template:
![info](https://user-images.githubusercontent.com/1479073/125985045-c91aa678-7a2b-4d6d-b19d-a4c5a2a2df91.png)

**Comment by JuliaSang** [comment]
Hi @jean-gui 

The box you are looking at is specifically for listing form errors, as per the GOVUK design system pattern. It has not been intended for anything else.

We have not designed a separate message / warning / notice box. This is a feature request and if needed we could do it in a future phase.

**Comment by vivienlacourba** [comment]
Hi @JuliaSang,

All our applications rely on those type of messages, they need to be part of the design system as they are critical for W3C Systems Team to implement forms that are in scope pages such as group pages or W3C Account workflow, but also for our other applications.
You actually experienced those various messages when you created your own W3C Account.

Note that we had actually mentioned this early in the project when we discussed forms requirements (see the "Forms" and "Call notes" sections of this [April 2020 internal basecamp discussion](https://3.basecamp.com/3091560/buckets/15695452/messages/2606510766)).

Thanks.

**Comment by NicolaSaunders** [comment]
@jean-gui @vivienlacourba I have just added a notes component, for which I have modified the basic pattern of the form validation error summary.  You can find examples of "notes" with an informative message, success message, warning message and error message at https://w3c-dev.studio24.dev/notes.html
