### ISSUE TITLE
Display precise timestamps on blog comments

### ISSUE THREAD

**Issue by gosko** [w3c/w3c-website#90]
[Blog comments on www-dev](https://www-dev.w3.org/blog/) are currently displayed with timestamps like '13 minutes ago', '8 days ago', '4 years ago'.

These dates/times are relative to the time the page was generated, so if you open a page and come back to it 2 days later it will still say '13 minutes ago' which is no longer accurate.

Also because these pages will be cached and regenerated only when there is new content, all the timestamps will constantly be displaying dates/times relative to the most recent comment or content update, which may be unrelated to the time the page is being viewed.

In addition to this issue with timestamps being frozen/obsolete, there is currently no way to view the precise timestamp for a given comment: there may be a number of comments listed as '8 days ago' but you can't tell if they were posted hours or minutes apart, and at what time of day.

Most other systems that tidy up precise date/timestamps like this seem to do so by shipping a precise timestamp in the body of the page then use javascript to simplify it or make it relative to the user's current state.

If timestamps are simplified in this way, it's important for the precise date/timestamp to remain available as well – most sites I have seen make the more precise timestamp available if you hover over the simplified version. (this is done for example on github, reddit, twitter)

If we can't do that it would be better to simply return the precise date/timestamp, and not bother with trying to clean it up to a relativized version.

In addition to fixing this for blog comments I think it would be good to make more precise dates/times available for blog posts themselves; currently they say 'Published: 15 November 2021' with no info available about the time it was posted. It would be nice to display a more precise time on hover if there's a way to make that accessible.

**Comment by vivienlacourba** [comment]
Per today's discussion @jean-gui will add the timezone

**Comment by jean-gui** [comment]
Relative timestamps are now computed with Javascript while absolute ones appear as tooltips when hovering. I've also added the timezone to these absolute timestamps.

I'm not sure about the need to show times for blog posts when hovering. @gosko What purpose would that serve?

**Comment by gosko** [comment]
I agree precise timestamps are not necessary for the blog posts. I thought it might be interesting in some cases, but usually not and most other blogs I checked just now don't seem to have precise timestamps. Thanks for improving the timestamps on comments, LGTM!
