### ISSUE TITLE
Alumni - Duplicate Entry name

### ISSUE THREAD

**Issue by lcarcone** [w3c/w3c-website#91]
**Describe the issue**
The name of an Alumni entry is generated from the given name only, which leads to duplicates as we have several alumni with the same given name. 
Could it also contain the family name ?

The slug of an Alumni entry is also based on the given name, so it is not unique. Shouldn't it be ?

**To reproduce**
See https://cms-dev.w3.org/admin/entries/alumni

**Comment by vivienlacourba** [comment]
> The slug of an Alumni entry is also based on the given name, so it is not unique. Shouldn't it be?

I agree I think it should be unique. That would also be useful as we could use it as an html id in the page to reference a particular section of the page as done today for several entries of [the current W3C Alumni page](https://www.w3.org/People/Alumni#bratt).

Could the default slug value be generated based on the concatenation of the given and family names? e.g. `{given}-{family}` (note that this does not ensure to necessarily generate a unique value if there are homonymous).

**Comment by jean-gui** [comment]
@lcarcone Note that you can add the family name column in the admin

**Comment by jean-gui** [comment]
It's indeed possible to concatenate given and family names in the title, but we will have to manually set family names for all existing alumni, or re-import them.

Regarding slugs, it seems that Craft doesn't enforce their uniqueness, but rather the uniqueness of URLs. This makes sense as slugs are only meant to be used as part of URLs. But as we don't have URLs for individual alumni, then this uniqueness cannot be enforced.
So if we want uniqueness, we could assign URLs to alumni in Craft, even if we're not going to use them. The question is, do we have use cases for making these slugs unique?

**Comment by jean-gui** [comment]
I've implemented the change, and made slugs unique so we can use them as ids in the alumni page.
