### ISSUE TITLE
Links in l-cluster are not vertically aligned properly

### ISSUE THREAD

**Issue by jean-gui** [w3c/w3c-website#92]
**Describe the issue**
Combining basic links with buttons (or links styled as buttons) results in improper vertical alignment:
![Screenshot_20220111_134016](https://user-images.githubusercontent.com/1479073/148944283-9953e26f-eda8-4748-9af1-4943204969c8.png)
On this screenshot, "Leave the group" should be vertically aligned with the text of the other two buttons.
The following code was used to produce this:
```html
<div class="l-cluster">
    <div>
        <a class="button" title="Join Audio Working Group" href="/groups/wg/audio/join/">Join the group</a>
        <a href="/groups/wg/audio/change/" class="button button--alt">Manage your organization's participation</a>
        <a title="Leave Audio Working Group" href="/groups/wg/audio/leave/">Leave the group</a>
    </div>
</div>
```

I've tried using the class `.button--ghost` for this third link but it then doesn't look like a link anymore, which I believe is problematic UX-wise.

**Comment by JuliaSang** [comment]
@NicolaSaunders Please can you review this ticket, leave advice for @maries24 on how to implement, and then reassign to @maries24 before 8/2/22. Cheers!

**Comment by NicolaSaunders** [comment]
@maries24 If you take a look at https://design-system.w3.org/code/button-cluster.html you will notice that the cluster layout has been given the additional class `component--members__cta` which is styled as follows:

```
.component--members__cta > * {

	align-items: center;

}
```

I recommend this technique as a solution in instances where the cluster layout is used to contain items of variable height and requiring even vertical alignment.

**Comment by jean-gui** [comment]
That does work indeed, but that class name seems extremely specific. Shouldn't it be renamed to something more generic?

**Comment by NicolaSaunders** [comment]
Oh, I wasn't suggesting using this specific class, just identifying the technique so it can be applied to the case in question.

**Comment by maries24** [comment]
@jean-gui @NicolaSaunders I'm creating a class .l-cluster--vertical-align that aligns elements vertically within a cluster. This will be added to the page on clusters of the design system.
