### ISSUE TITLE
<abbr> and <dfn> tags are not allowed

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#93]
**Describe the issue**
The `<abbr>` HTML tag is not allowed in the Craft CMS editor.

In a Text component it is not possible to use the `<abbr>` tag. The HTML editor has no icon for that. And it is also not possible to use it when switching the editor to source mode.

**To reproduce**
Create a new page, use the Text component, and try to use an <abbr> tag for example copying the example from:
https://developer.mozilla.org/en/docs/Web/HTML/Element/abbr

**Expected behavior**
It should be possible to `<abbr>` both using an editor icon and when editing in "source" mode.

cc: @koalie

**Comment by vivienlacourba** [comment]
Same issue with `<dfn>` cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn

I updated the issue title accordingly.

**Comment by vivienlacourba** [comment]
I note that those tags are described in this test page created by Studio 24: https://www-dev.w3.org/landing-page/w3c-mission-default/#examples-of-other-html-elements

**Comment by maries24** [comment]
Work done but not deployed yet. Waiting for issue with HTML purifier to be sorted first (see [issue 104](https://github.com/w3c/w3c-website/projects/1#card-76262993))
