### ISSUE TITLE
It is not possible to set the language of specific text or component

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#95]
**Describe the issue**

It is not possible to set the language of specific text either:
- for an entire block using the Text and Blockquote components
- for a given set or word or paragraph using the HTML editor (no icon for that and not possible when switching to source mode)

**To reproduce**

Create a new page add a Blockquote component -> You cannot set a specific language of for this component.

Create a new page add a Text component -> There is no option to set the language of this component.

In the HTML editor -> There is no icon to enable you to set the language of specific word/sentence/paragraph.

In the HTML editor -> Switch to source mode and try to enter the following markup:
```html
<p>In French "Hello" is <span lang="fr">"Salut"</span>.</p>
<p lang="fr">Salut les amis!<p>
```
Then untoggle and toggle back the source mode and you will notice that the `<span>` tag and the `lang` attributes got automatically stripped by the editor.

**Comment by maries24** [comment]
Work done but not deployed yet. Waiting for issue with HTML purifier to be sorted first (see [issue 104](Work done but not deployed yet. Waiting for issue with HTML purifier to be sorted first (see issue 104)))

**Comment by maries24** [comment]
Hi @vivienlacourba 

I have modified the CKEditor configuration to allow adding 'lang' attributes to any element. So at least content authors can now add that attribute manually.

There is now also a 'language' button implemented using the [CKEditor language plugin](https://ckeditor.com/cke4/addon/language). It does however require to manually enter the list of allowed languages in the `web/ckeditor/configs/config_default.js` file via the 'config.language_list' option (I couldn't see a wildcard option to add them all in one go). I have added a few for the time being so we can check it is working. Happy to add more later.

As for adding a language attribute to the whole blockquote and text components, can I suggest creating a specific card for that and addressing it at  a later stage? That one requires more extensive work as it involves changes in Craft and in the front-end application. Also, the use case of multilingual testimonials on the ecosystem pages has been address already (in that context the language attribute is automatically assigned to the whole testimonial). Not sure whether that is one of the things you had in mind when making that request.

PS: the CKEditor config file can persist quite stubbornly in browsers. If you cannot see the changes above, please try clearing your cache.

**Comment by vivienlacourba** [comment]
Hi @maries24 

> I have modified the CKEditor configuration to allow adding 'lang' attributes to any element. So at least content authors can now add that attribute manually.

I noticed that CKEditor requires the `dir` attribute to also be present when setting the `lang` attribute on a `<span>`. This looks like a bug as @r12a confirmed me that usng lang without dir was correct.
I filled an issue in the CKEditor bug tracker: https://github.com/ckeditor/ckeditor4/issues/5085

I also noticed that if several `<p>` were surrounded by a `<div>` then even if the `<div>` block is selected the `lang` will be set on each individual `<p>` instead of on the selected `<div>`.
Related bug: https://github.com/ckeditor/ckeditor4/issues/935

> There is now also a 'language' button implemented using the [CKEditor language plugin](https://ckeditor.com/cke4/addon/language). It does however require to manually enter the list of allowed languages in the `web/ckeditor/configs/config_default.js` file via the 'config.language_list' option (I couldn't see a wildcard option to add them all in one go). I have added a few for the time being so we can check it is working. Happy to add more later.

Yes, I also think that is good for now.

> As for adding a language attribute to the whole blockquote and text components, can I suggest creating a specific card for that and addressing it at a later stage? That one requires more extensive work as it involves changes in Craft and in the front-end application.

OK. I created #128.

> Also, the use case of multilingual testimonials on the ecosystem pages has been address already (in that context the language attribute is automatically assigned to the whole testimonial). Not sure whether that is one of the things you had in mind when making that request.

My use case was for testimonials which are present in press releases.
