### ISSUE TITLE
Blockquote and Text components don't have the same width

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#96]
**Describe the issue**

I indicated to  @JuliaSang that those 2 components had different width, she thought it was a bug and that the blockquote component should have the same width as the text component.

**URL**

https://www-dev.w3.org/ux-issues-demo/

**Comment by koalie** [comment]
The width of the "heading" and "description" elements in the "Images and descriptions" flexible component also do not make use of the full width of the viewport (I mean the max width other components of the design use).

This can be viewed here (and screenshot underneath, look for the red rectangle):
[https://www-staging.w3.org/ecosystems/](https://www-staging.w3.org/ecosystems/)

<img width="663" alt="Screenshot 2022-01-13 at 17 55 00 " src="https://user-images.githubusercontent.com/3716853/149374302-75fde1c3-0353-4d27-b555-22407bee54eb.png">

**Comment by JuliaSang** [comment]
@vivienlacourba - to confirm on the blockquote image it is only at a certain breakpoint (around 900 px) that the blockquote width needs to be adjusted. Larger screens and smaller screens it is OK. I've attached a screenshot to show where it is broken

![screencapture-www-dev-w3-org-ux-issues-demo-2022-01-19-08_55_10](https://user-images.githubusercontent.com/20167528/150097521-06497d2c-6b75-4c08-9e9e-869e7c351097.png)

**Comment by vivienlacourba** [comment]
> @vivienlacourba - to confirm on the blockquote image it is only at a certain breakpoint (around 900 px) that the blockquote width needs to be adjusted. Larger screens and smaller screens it is OK. I've attached a screenshot to show where it is broken

@JuliaSang the text component and the quote component always have a different width, it is just that its is more visible when the main menu gets reduced. And looking a bit more it appears that the Image and Quote have the same width (I adjusted the issue title accordingly).
So the issue is that the Text component uses a smaller width that the other.
