### ISSUE TITLE
Incorrect "Browse archives: All" link for news

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/w3c-website#99]
On news listings pages (such as [[1]](https://www-staging.w3.org/news/) or [[2]](https://www-staging.w3.org/news/1994/)), the `"Browse archives: All"` link is incorrect as it leads to:
https://www-staging.w3.org/blog/
instead of:
https://www-staging.w3.org/news/

**Comment by jean-gui** [comment]
Fixed
